import { join } from 'node:path';
import { existsSync } from 'node:fs';
import AgentuityBuilder from './plugin';
import { getFilesRecursively } from './file';

interface BuildOptions {
    rootDir: string;
    dev?: boolean;
}

export async function build({ dev = false, rootDir }: BuildOptions) {
    const appFile = join(rootDir, 'app.ts');
    const f = Bun.file(appFile);
    if (!(await f.exists())) {
        throw new Error(`App file not found at expected location: ${appFile}`);
    }
    const outDir = join(rootDir, '.agentuity');
    const srcDir = join(rootDir, 'src');

    const entrypoints: string[] = [];

    for (const folder of ['apis', 'agents', 'web']) {
        const dir = join(srcDir, folder);
        if (!existsSync(dir)) {
            if (folder === 'agents') {
                throw new Error(`Expected directory not found: ${dir}`);
            }
            continue;
        }
        const files = await getFilesRecursively(dir);
        for (const filename of files) {
            if (/\.[jt]sx?$/.test(filename)) {
                entrypoints.push(filename);
            }
        }
    }

    entrypoints.push(appFile); // always do this last

    const config: Bun.BuildConfig = {
        entrypoints,
        root: rootDir,
        outdir: outDir,
        bytecode: dev ? false : true,
        sourcemap: 'external',
        env: 'AGENTUITY_PUBLIC_*',
        plugins: [AgentuityBuilder],
        target: 'bun',
        banner: '// Auto-generated by Agentuity - do not edit manually',
    };

    await Bun.build(config);
}
