import type { BunPlugin } from 'bun';
import { dirname, normalize, basename, join } from 'node:path';
import { existsSync, writeFileSync } from 'node:fs';

function toCamelCase(str: string): string {
    return str
        .replace(/[-_\s]+(.)?/g, (_, char) => (char ? char.toUpperCase() : ''))
        .replace(/^(.)/, (char) => char.toLowerCase());
}

function toPascalCase(str: string): string {
    const camel = toCamelCase(str);
    return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function generateAgentRegistry(
    srcDir: string,
    agentInfo: Array<{ name: string; path: string }>
) {
    const imports = agentInfo
        .map(({ name, path }) => {
            const camelName = toCamelCase(name);
            return `import ${camelName}Agent from '${path.replace(
                '../agents/',
                './'
            )}';`;
        })
        .join('\n');

    const registry = agentInfo
        .map(({ name }) => {
            const camelName = toCamelCase(name);
            return `  ${camelName}: ${camelName}Agent,`;
        })
        .join('\n');

    const typeExports = agentInfo
        .map(({ name }) => {
            const camelName = toCamelCase(name);
            const pascalName = toPascalCase(name);
            return `export type ${pascalName}AgentRunner = AgentRunner<typeof ${camelName}Agent['inputSchema'], typeof ${camelName}Agent['outputSchema'], typeof ${camelName}Agent['stream'] extends true ? true : false>;`;
        })
        .join('\n');

    const generatedContent = `// Auto-generated by Agentuity - do not edit manually
${imports}
import type { AgentRunner } from '@agentuity/server';

export const agentRegistry = {
${registry}
} as const;

export type AgentName = keyof typeof agentRegistry;
export type AgentRegistry = typeof agentRegistry;

// Typed runners for each agent
${typeExports}

// Augment Context to provide strongly-typed agents
declare module "hono" {
	interface Context {
	   agent: {
	     [K in AgentName]: AgentRunner<AgentRegistry[K]['inputSchema'], AgentRegistry[K]['outputSchema'], AgentRegistry[K]['stream'] extends true ? true : false>;
	   };
  }
}
`;

    const generatedPath = join(srcDir, 'agents', 'index.generated.ts');
    // console.log(`Writing agent registry to ${generatedPath}`);

    writeFileSync(generatedPath, generatedContent, 'utf-8');

    // console.log(`Generated agent registry at ${generatedPath}`);

    // Generate types-only file for client-side usage
    const typesOnlyContent = `// Auto-generated by Agentuity - do not edit manually
// Types-only file - safe for client-side imports
${agentInfo
    .map(({ name, path }) => {
        const camelName = toCamelCase(name);
        return `import type ${camelName}Agent from '${path.replace(
            '../agents/',
            './'
        )}';`;
    })
    .join('\n')}

export type AgentRegistry = {
${agentInfo
    .map(({ name }) => {
        const camelName = toCamelCase(name);
        return `  ${camelName}: typeof ${camelName}Agent;`;
    })
    .join('\n')}
};

export type AgentName = keyof AgentRegistry;
`;

    const typesOnlyPath = join(srcDir, 'agents', 'index.types.ts');
    writeFileSync(typesOnlyPath, typesOnlyContent, 'utf-8');
    // console.log(`Generated agent types at ${typesOnlyPath}`);
}

const AgentuityBuilder: BunPlugin = {
    name: 'Agentuity Bundler',
    setup(build) {
        const rootDir = build.config.root ?? '.';
        const srcDir = join(rootDir, 'src');
        const outDir = build.config.outdir ?? '.agentuity';
        const routes: Set<string> = new Set();
        const agentInfo: Array<{ name: string; path: string }> = [];

        build.onResolve(
            { filter: /\/route\.ts$/, namespace: 'file' },
            async (args) => {
                const importPath = args.path
                    .replace(rootDir, '')
                    .replace('.ts', '')
                    .replace('/src/', './');
                routes.add(importPath);
                return args;
            }
        );

        build.onLoad(
            {
                filter: new RegExp(join(rootDir, 'app.ts')),
                namespace: 'file',
            },
            async (args) => {
                const inserts: string[] = [];

                // First pass: collect agent info and generate route setup
                for (const route of routes) {
                    const name = basename(dirname(route));
                    const agent = route.replace(/\/route$/, '/agent');
                    const hasAgent = existsSync(join(srcDir, agent + '.ts'));
                    const agentPath = route
                        .replace(/\/route$/, '/*')
                        .replace('/agents', '/agent')
                        .replace('./', '/');
                    const routePath = route
                        .replace(/\/route$/, '')
                        .replace('/apis/', '/api/')
                        .replace('/apis', '/api')
                        .replace('/agents', '/agent')
                        .replace('/agents', '/agent')
                        .replace('./', '/');

                    // console.log({ route, hasAgent, agentPath, routePath });

                    if (hasAgent) {
                        agentInfo.push({ name, path: `.${agent}` });
                    }

                    let buffer = `await (async() => {
    const { createAgentMiddleware, getApp, registerAgent } = await import('@agentuity/server');
    const app = getApp()!;
    const route = require('./src/${route}').default;`;
                    if (hasAgent) {
                        buffer += `
    const agent = require('./src/${agent}').default;
    app.all("${agentPath}", createAgentMiddleware());
    registerAgent("${name}", agent);`;
                    }
                    buffer += `
    app.route("${routePath}", route);
})();`;
                    inserts.push(buffer);
                }

                const indexFile = join(rootDir, 'web', 'app.tsx');
                const client = join(rootDir, 'web', 'client.js'); // TODO: generate this
                if (existsSync(indexFile) && existsSync(client)) {
                    const uniqid = Math.random().toString(36);
                    const clientjs = join(outDir, 'web', 'client.js');
                    inserts.unshift(`(() => {
    const { renderToString } = require('react-dom/server');
    const { serveStatic } = require('hono/bun');
    const { getApp } = require('@agentuity/server');
    const env = getApp()!;
    const routehtml = renderToString(require("./web/app").default);
    app.get("/", (c) => c.html(\`<html><body><div id="root">\${routehtml}</div><script src="/web/${uniqid}/client.js" type="module"></script></body></html>\`));
    app.get("/web/${uniqid}/client.js", (c) => new Response(Bun.file('${clientjs}'), { type: 'text/javascript', headers: { 'Cache-Control': 'public, max-age=31536000, immutable' } }));
    app.get('/public/*', serveStatic({ root: '${dirname(indexFile)}' }));
})();`);
                }

                // Generate agents.generated.ts file
                generateAgentRegistry(srcDir, agentInfo);

                const file = Bun.file(args.path);
                let contents = await file.text();
                let inserted = false;
                const index = contents.indexOf(' createApp(');
                if (index > 0) {
                    const endSemi = contents.indexOf(');', index);
                    if (endSemi > 0) {
                        contents =
                            contents.slice(0, endSemi + 2) +
                            '\n\n' +
                            inserts.join('\n') +
                            contents.slice(endSemi + 2);
                        inserted = true;
                    }
                }
                if (!inserted) {
                    contents += `\n${inserts.join('\n')}`;
                }

                // console.log(contents);
                return {
                    contents,
                    loader: 'ts',
                };
            }
        );
    },
};

export default AgentuityBuilder;
