/**
 * Cryptographic hashing helpers.
 *
 * Replacements for the CLI's previous `Bun.CryptoHasher` and
 * `Bun.hash.xxHash64` usages, backed by Node's native `node:crypto`.
 *
 * The `shortHash16` function intentionally swaps in a SHA-256
 * truncation for the previous xxHash64-based "project domain id". See
 * PLAN.md \u00a78 for context on the behavior change: cache keys derived
 * via this helper will not match values previously computed by Bun's
 * xxHash64. The site is local-cache-only and not security-relevant,
 * so the one-time invalidation is acceptable.
 */

import { createHash } from 'node:crypto';

/** Hex-encoded SHA-1 of a UTF-8 string or buffer. */
export function sha1Hex(input: string | Uint8Array): string {
	return createHash('sha1').update(input).digest('hex');
}

/** Hex-encoded SHA-256 of a UTF-8 string or buffer. */
export function sha256Hex(input: string | Uint8Array): string {
	return createHash('sha256').update(input).digest('hex');
}

/**
 * Deterministic, 16-hex-character hash of a string. Backed by
 * SHA-256 truncated to the first 16 hex digits.
 *
 * Replaces previous calls of the form
 *   `Bun.hash.xxHash64(s).toString(16).padStart(16, '0')`
 * with a Node-portable computation that produces a string of the
 * same length and shape (16 lowercase hex chars).
 *
 * Note: cache keys generated by this function will *not* match
 * those previously generated by xxHash64. Treat the change as a
 * one-time cache invalidation.
 */
export function shortHash16(input: string | Uint8Array): string {
	return sha256Hex(input).slice(0, 16);
}
