/**
 * Auto-generated sandbox script metadata.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Edit the source files in src/run/ and run: bun run scripts/generate-sandbox-scripts.ts
 *
 * @generated
 */

/** Valid script names (scripts are baked into the sandbox snapshot) */
export const SCRIPT_NAMES: ReadonlySet<string> = new Set([
	'agent-calls',
	'ai-gateway',
	'chat',
	'cron',
	'durable-stream',
	'evals',
	'handler-context',
	'hello',
	'kv',
	'model-arena',
	'objectstore',
	'sse-stream',
	'streaming',
	'vector',
]);

/** Default inputs for each script (extracted from source files) */
export const SCRIPT_DEFAULTS: Record<string, unknown> = {
	'agent-calls': { name: 'World' },
	'ai-gateway': { prompt: 'Tell me a joke' },
	chat: { message: 'Hello!' },
	cron: {},
	'durable-stream': { content: 'Hello world' },
	evals: { question: 'What is TypeScript?' },
	'handler-context': {},
	hello: { name: 'World' },
	kv: {},
	'model-arena': { prompt: 'Write a haiku about coding' },
	objectstore: {},
	'sse-stream': { prompt: 'Tell me a story' },
	streaming: { prompt: 'Tell me a story' },
	vector: { query: 'comfortable chair' },
};
