import type { Service } from '../api-reference.ts';

const service: Service = {
	name: 'Object Storage',
	slug: 'object-storage',
	description: 'Store and manage files and binary objects in buckets',
	endpoints: [
		{
			id: 'list-objects',
			title: 'List Objects',
			method: 'GET',
			path: '/storage/objects/{bucket}',
			description: 'List objects in a bucket with optional prefix and pagination.',
			pathParams: [{ name: 'bucket', type: 'string', description: 'Bucket name' }],
			queryParams: [
				{
					name: 'prefix',
					type: 'string',
					description: 'Only return keys with this prefix',
					required: false,
				},
				{
					name: 'limit',
					type: 'number',
					description: 'Maximum objects to return',
					required: false,
				},
				{
					name: 'offset',
					type: 'number',
					description: 'Offset for pagination',
					required: false,
				},
			],
			requestBody: null,
			responseDescription: 'Paginated object listing.',
			responseFields: [
				{ name: 'objects', type: 'array', description: 'List of object metadata records' },
				{
					name: 'objects[].bucket_name',
					type: 'string',
					description: 'Bucket containing the object',
				},
				{ name: 'objects[].key', type: 'string', description: 'Object key' },
				{ name: 'objects[].size', type: 'number', description: 'Object size in bytes' },
				{ name: 'objects[].etag', type: 'string', description: 'Entity tag' },
				{ name: 'objects[].content_type', type: 'string', description: 'MIME content type' },
				{
					name: 'objects[].last_modified',
					type: 'string',
					description: 'Last modified timestamp',
				},
				{ name: 'total', type: 'number', description: 'Total matching objects' },
				{ name: 'prefix', type: 'string', description: 'Applied prefix filter' },
				{ name: 'limit', type: 'number', description: 'Applied limit' },
				{ name: 'offset', type: 'number', description: 'Applied offset' },
			],
			statuses: [
				{ code: 200, description: 'Object list returned' },
				{ code: 401, description: 'Unauthorized' },
			],
			examplePath: '/storage/objects/my-bucket?prefix=images/&limit=50',
		},
		{
			id: 'delete-objects',
			title: 'Delete Objects',
			method: 'DELETE',
			path: '/storage/objects/{bucket}',
			description:
				'Delete objects by key or by prefix. `key` and `prefix` are mutually exclusive query parameters.',
			pathParams: [{ name: 'bucket', type: 'string', description: 'Bucket name' }],
			queryParams: [
				{
					name: 'key',
					type: 'string',
					description: 'Delete a single object key',
					required: false,
				},
				{
					name: 'prefix',
					type: 'string',
					description: 'Delete all objects matching prefix',
					required: false,
				},
			],
			requestBody: null,
			responseDescription: 'JSON response with deleted object count.',
			responseFields: [
				{ name: 'deleted_count', type: 'number', description: 'Number of objects deleted' },
			],
			statuses: [
				{ code: 200, description: 'Delete operation completed' },
				{ code: 401, description: 'Unauthorized' },
			],
			examplePath: '/storage/objects/my-bucket?key=images/photo.jpg',
		},
		{
			id: 'generate-presigned-url',
			title: 'Generate Presigned URL',
			method: 'GET',
			path: '/storage/presign/{bucket}',
			description: 'Generate a time-limited URL for uploading or downloading an object.',
			pathParams: [{ name: 'bucket', type: 'string', description: 'Bucket name' }],
			queryParams: [
				{ name: 'key', type: 'string', description: 'Object key to access', required: true },
				{
					name: 'operation',
					type: 'string',
					description: 'Operation type: `download` or `upload` (default: `download`)',
					required: false,
				},
			],
			requestBody: null,
			responseDescription: 'JSON response containing presigned URL and expiry.',
			responseFields: [
				{ name: 'presigned_url', type: 'string', description: 'Temporary signed URL' },
				{ name: 'expiry_seconds', type: 'number', description: 'URL expiry in seconds' },
			],
			statuses: [
				{ code: 200, description: 'Presigned URL generated' },
				{ code: 401, description: 'Unauthorized' },
			],
			examplePath: '/storage/presign/my-bucket?key=images/photo.jpg&operation=download',
		},
		{
			id: 'get-bucket-stats',
			title: 'Get Bucket Stats',
			method: 'GET',
			path: '/storage/stats/{bucket}',
			description: 'Get object count and total size for a bucket.',
			pathParams: [{ name: 'bucket', type: 'string', description: 'Bucket name' }],
			queryParams: [],
			requestBody: null,
			responseDescription: 'Bucket-level usage and activity statistics.',
			responseFields: [
				{ name: 'bucket_name', type: 'string', description: 'Bucket name' },
				{ name: 'object_count', type: 'number', description: 'Total number of objects' },
				{ name: 'total_size', type: 'number', description: 'Total size in bytes' },
				{
					name: 'last_event_at',
					type: 'string | null',
					description: 'Last activity timestamp (ISO 8601)',
				},
			],
			statuses: [
				{ code: 200, description: 'Bucket stats returned' },
				{ code: 401, description: 'Unauthorized' },
			],
			examplePath: '/storage/stats/my-bucket',
		},
		{
			id: 'get-storage-analytics',
			title: 'Get Storage Analytics',
			method: 'GET',
			path: '/storage/analytics',
			description: 'Get aggregated analytics across buckets and daily snapshots.',
			pathParams: [],
			queryParams: [
				{
					name: 'days',
					type: 'number',
					description: 'Days of history to include (default: 180)',
					required: false,
				},
			],
			requestBody: null,
			responseDescription: 'Analytics summary, per-bucket breakdown, and daily trend data.',
			responseFields: [
				{ name: 'summary', type: 'object', description: 'Overall storage summary' },
				{
					name: 'summary.total_object_count',
					type: 'number',
					description: 'Total objects across buckets',
				},
				{
					name: 'summary.total_size',
					type: 'number',
					description: 'Total bytes across buckets',
				},
				{
					name: 'summary.estimated_monthly_cost',
					type: 'number',
					description: 'Estimated monthly storage cost',
				},
				{
					name: 'summary.cost_per_gb_month',
					type: 'number',
					description: 'Cost per GB-month used in estimate',
				},
				{ name: 'buckets', type: 'array', description: 'Per-bucket stats' },
				{ name: 'daily', type: 'array', description: 'Daily usage snapshots' },
				{ name: 'days', type: 'number', description: 'Applied history window in days' },
			],
			statuses: [
				{ code: 200, description: 'Analytics returned' },
				{ code: 401, description: 'Unauthorized' },
			],
			examplePath: '/storage/analytics?days=30',
		},
		{
			id: 'get-bucket-config',
			title: 'Get Bucket Config',
			method: 'GET',
			path: '/bucket/config/{bucket}',
			description: 'Retrieve effective configuration for a bucket.',
			pathParams: [{ name: 'bucket', type: 'string', description: 'Bucket name' }],
			queryParams: [],
			requestBody: null,
			responseDescription: 'Bucket configuration settings and location metadata.',
			responseFields: [
				{ name: 'bucket_name', type: 'string', description: 'Bucket name' },
				{
					name: 'storage_tier',
					type: 'string | null',
					description: '`STANDARD`, `INFREQUENT_ACCESS`, or `ARCHIVE`',
				},
				{ name: 'ttl', type: 'number | null', description: 'Default object TTL in seconds' },
				{
					name: 'public',
					type: 'boolean | null',
					description: 'Whether objects are publicly accessible',
				},
				{
					name: 'cache_control',
					type: 'string | null',
					description: 'Default Cache-Control header',
				},
				{ name: 'cors', type: 'object | null', description: 'CORS configuration' },
				{
					name: 'additional_headers',
					type: 'object | null',
					description: 'Additional response headers',
				},
				{
					name: 'bucket_location',
					type: 'string | null',
					description: 'Bucket storage location/region',
				},
			],
			statuses: [
				{ code: 200, description: 'Bucket config returned' },
				{ code: 401, description: 'Unauthorized' },
			],
			examplePath: '/bucket/config/my-bucket',
		},
		{
			id: 'update-bucket-config',
			title: 'Update Bucket Config',
			method: 'PUT',
			path: '/bucket/config/{bucket}',
			description: 'Update bucket configuration fields. Omitted fields remain unchanged.',
			pathParams: [{ name: 'bucket', type: 'string', description: 'Bucket name' }],
			queryParams: [],
			requestBody: {
				description: 'Partial bucket config update payload.',
				fields: [
					{
						name: 'storage_tier',
						type: 'string',
						description: 'Storage tier override',
						required: false,
					},
					{
						name: 'ttl',
						type: 'number | null',
						description: 'Default TTL in seconds',
						required: false,
					},
					{
						name: 'public',
						type: 'boolean',
						description: 'Public access setting',
						required: false,
					},
					{
						name: 'cache_control',
						type: 'string',
						description: 'Default Cache-Control header',
						required: false,
					},
					{ name: 'cors', type: 'object', description: 'CORS configuration', required: false },
					{
						name: 'additional_headers',
						type: 'object',
						description: 'Additional response headers',
						required: false,
					},
				],
			},
			responseDescription: 'Updated bucket configuration object.',
			responseFields: [
				{ name: 'bucket_name', type: 'string', description: 'Bucket name' },
				{ name: 'storage_tier', type: 'string | null', description: 'Configured storage tier' },
				{ name: 'ttl', type: 'number | null', description: 'Configured TTL' },
				{ name: 'public', type: 'boolean | null', description: 'Configured public access' },
				{
					name: 'cache_control',
					type: 'string | null',
					description: 'Configured Cache-Control',
				},
				{ name: 'cors', type: 'object | null', description: 'Configured CORS settings' },
				{
					name: 'additional_headers',
					type: 'object | null',
					description: 'Configured custom headers',
				},
				{ name: 'bucket_location', type: 'string | null', description: 'Bucket location' },
			],
			statuses: [
				{ code: 200, description: 'Bucket config updated' },
				{ code: 401, description: 'Unauthorized' },
			],
			examplePath: '/bucket/config/my-bucket',
			exampleBody: { ttl: 86400, public: true, cache_control: 'max-age=3600' },
		},
		{
			id: 'delete-bucket-config',
			title: 'Delete Bucket Config',
			method: 'DELETE',
			path: '/bucket/config/{bucket}',
			description: 'Delete custom bucket config and reset to defaults.',
			pathParams: [{ name: 'bucket', type: 'string', description: 'Bucket name' }],
			queryParams: [],
			requestBody: null,
			responseDescription: 'Empty response on success.',
			statuses: [
				{ code: 200, description: 'Bucket config deleted/reset' },
				{ code: 401, description: 'Unauthorized' },
			],
			examplePath: '/bucket/config/my-bucket',
		},
	],
};

export default service;
