// Auto-generated by scripts/generate-nav-data.ts — DO NOT EDIT

export interface NavItem {
	title: string;
	url?: string;
	isActive?: boolean;
	/** Short description from MDX frontmatter, used in search results */
	description?: string;
	/** Nested items for subsections */
	items?: NavItem[];
}

export interface NavSection {
	title: string;
	url?: string;
	items: NavItem[];
	/** If true, items are hidden from sidebar but still used for breadcrumb/search */
	hideItems?: boolean;
}

export const navData: NavSection[] = [
	{
		title: 'Home',
		url: '/',
		hideItems: true,
		items: [],
	},
	{
		title: 'SDK Explorer',
		url: '/explorer',
		hideItems: true,
		items: [
			{
				title: 'Hello Agent',
				url: '/explorer/hello',
				description: 'Your first agent - send input, get output',
			},
			{
				title: 'Handler Context',
				url: '/explorer/handler-context',
				description: "See what's available inside your agent handler",
			},
			{
				title: 'Chat',
				url: '/explorer/chat',
				description: 'Conversation memory that persists across messages',
			},
			{
				title: 'KV Storage',
				url: '/explorer/key-value',
				description: 'Store and retrieve data by key, with auto-expiration',
			},
			{
				title: 'Vector Search',
				url: '/explorer/vector-storage',
				description: 'Find content by meaning, not just keywords',
			},
			{
				title: 'Object Storage',
				url: '/explorer/object-storage',
				description: 'Store files with presigned URLs for sharing',
			},
			{
				title: 'AI Gateway',
				url: '/explorer/ai-gateway',
				description: 'Use any AI provider with a single API key',
			},
			{
				title: 'Text Stream',
				url: '/explorer/streaming',
				description: "Stream responses as they're generated",
			},
			{
				title: 'SSE Stream',
				url: '/explorer/sse-stream',
				description: 'Structured streaming with event types and auto-reconnect',
			},
			{
				title: 'Durable Streams',
				url: '/explorer/durable-stream',
				description: 'Generate content and get a permanent, shareable URL',
			},
			{
				title: 'Agent Calls',
				url: '/explorer/agent-calls',
				description: 'Call agents from routes or other agents',
			},
			{
				title: 'Cron Jobs',
				url: '/explorer/cron',
				description: 'Run tasks on a schedule with cron expressions',
			},
			{
				title: 'Model Arena',
				url: '/explorer/model-arena',
				description: 'Compare AI models using another AI as judge',
			},
			{
				title: 'Queues',
				url: '/explorer/queue',
				description: 'Publish, consume, retry, and inspect dead-letter messages',
			},
			{
				title: 'Email',
				url: '/explorer/email',
				description: 'Send transactional emails with platform-managed delivery',
			},
			{
				title: 'Database',
				url: '/explorer/database',
				description: 'Query PostgreSQL with Drizzle ORM and typed schema definitions',
			},
		],
	},
	{
		title: 'Get Started',
		url: '/get-started',
		items: [
			{
				title: 'What is Agentuity?',
				url: '/get-started/what-is-agentuity',
				description: 'The full-stack platform for building, deploying, and operating AI agents',
			},
			{
				title: 'Installation',
				url: '/get-started/installation',
				description: 'Set up your development environment',
			},
			{
				title: 'Quickstart',
				url: '/get-started/quickstart',
				description: 'Build your first agent in 5 minutes',
			},
			{
				title: 'Project Structure',
				url: '/get-started/project-structure',
				description: 'Understand how Agentuity projects are organized',
			},
			{
				title: 'App Configuration',
				url: '/get-started/app-configuration',
				description: 'Configure your Agentuity project',
			},
		],
	},
	{
		title: 'Agents',
		url: '/agents',
		items: [
			{
				title: 'When to Use',
				url: '/agents/when-to-use',
				description: 'When to create an agent vs handling requests directly in routes',
			},
			{
				title: 'Creating Agents',
				url: '/agents/creating-agents',
				description: 'Build agents with createAgent(), schemas, and handlers',
			},
			{
				title: 'Schema Libraries',
				url: '/agents/schema-libraries',
				description: 'Choose from built-in, Zod, Valibot, or ArkType for validation',
			},
			{
				title: 'AI Gateway',
				url: '/agents/ai-gateway',
				description: 'Automatic LLM routing with observability and cost tracking',
			},
			{
				title: 'AI SDK Integration',
				url: '/agents/ai-sdk-integration',
				description: 'Generate text, structured data, and streams with the Vercel AI SDK',
			},
			{
				title: 'Streaming Responses',
				url: '/agents/streaming-responses',
				description: 'Return real-time LLM output with streaming agents',
			},
			{
				title: 'State Management',
				url: '/agents/state-management',
				description: 'Request and thread state for stateful agents',
			},
			{
				title: 'Calling Other Agents',
				url: '/agents/calling-other-agents',
				description: 'Build multi-agent systems with type-safe agent-to-agent communication',
			},
			{
				title: 'Standalone Execution',
				url: '/agents/standalone-execution',
				description:
					'Execute agents programmatically for cron jobs, bots, CLI tools, and background workers',
			},
			{
				title: 'Events & Lifecycle',
				url: '/agents/events-lifecycle',
				description: 'Lifecycle hooks for monitoring and extending agent behavior',
			},
		],
	},
	{
		title: 'Routes',
		url: '/routes',
		items: [
			{
				title: 'HTTP',
				url: '/routes/http',
				description: 'Define GET, POST, and other HTTP endpoints with Hono',
			},
			{
				title: 'Middleware',
				url: '/routes/middleware',
				description: 'Add authentication, validation, and request processing to your routes',
			},
			{
				title: 'Calling Agents',
				url: '/routes/calling-agents',
				description: 'Import and invoke agents from your routes',
			},
			{
				title: 'Cron',
				url: '/routes/cron',
				description: 'Run tasks on a schedule with the cron() middleware',
			},
			{
				title: 'WebSockets',
				url: '/routes/websockets',
				description: 'Real-time bidirectional communication with the websocket middleware',
			},
			{
				title: 'SSE',
				url: '/routes/sse',
				description: 'Stream updates from server to client using SSE middleware',
			},
			{
				title: 'Using WebRTC',
				url: '/routes/webrtc',
				description: 'Peer-to-peer audio, video, and data channels with the webrtc middleware',
			},
			{
				title: 'Using Explicit Routing',
				url: '/routes/explicit-routing',
				description:
					'Pass your own Hono router to createApp() when you need custom mount paths or an exported router type',
			},
		],
	},
	{
		title: 'Frontend',
		url: '/frontend',
		items: [
			{
				title: 'React Hooks',
				url: '/frontend/react-hooks',
				description: 'Provider, auth, analytics, and WebRTC hooks from @agentuity/react',
			},
			{
				title: 'RPC Client',
				url: '/frontend/rpc-client',
				description:
					'Type-safe API calls from any JavaScript environment using hc() from hono/client',
			},
			{
				title: 'Provider Setup',
				url: '/frontend/provider-setup',
				description: 'Legacy AgentuityProvider setup for @agentuity/react apps',
			},
			{
				title: 'Authentication',
				url: '/frontend/authentication',
				description: 'Add user authentication with Agentuity Auth',
			},
			{
				title: 'Deployment Scenarios',
				url: '/frontend/deployment-scenarios',
				description:
					'Deploy your frontend alongside agents or separately on Vercel, Netlify, etc.',
			},
			{
				title: 'Static Rendering',
				url: '/frontend/static-rendering',
				description:
					'Pre-render your frontend to static HTML for faster page loads and better SEO',
			},
			{
				title: 'Advanced Hooks',
				url: '/frontend/advanced-hooks',
				description:
					'Advanced WebRTC callbacks plus low-level WebSocket and SSE client utilities',
			},
		],
	},
	{
		title: 'Services',
		url: '/services',
		items: [
			{
				title: 'Database',
				url: '/services/database',
				items: [
					{
						title: 'Postgres',
						url: '/services/database/postgres',
						description: 'Auto-reconnecting PostgreSQL client for serverless environments',
					},
					{
						title: 'Drizzle',
						url: '/services/database/drizzle',
						description: 'Type-safe database access with Drizzle ORM',
					},
				],
			},
			{
				title: 'Storage',
				url: '/services/storage',
				items: [
					{
						title: 'Key-Value',
						url: '/services/storage/key-value',
						description:
							'Fast, ephemeral storage for caching, session data, and configuration',
					},
					{
						title: 'Vector',
						url: '/services/storage/vector',
						description: 'Semantic search and retrieval for knowledge bases and RAG systems',
					},
					{
						title: 'Object',
						url: '/services/storage/object',
						description: "Durable file storage using Bun's native S3 APIs",
					},
					{
						title: 'Durable Streams',
						url: '/services/storage/durable-streams',
						description:
							'Streaming storage for large exports, audit logs, and real-time data',
					},
					{
						title: 'Custom',
						url: '/services/storage/custom',
						description:
							'Local development storage and bringing your own storage implementations',
					},
				],
			},
			{
				title: 'Queues',
				url: '/services/queues',
				description:
					'Publish messages for async processing, webhooks, and event-driven workflows',
			},
			{
				title: 'Email',
				url: '/services/email',
				description:
					'Send and receive emails with managed addresses, destinations, and delivery tracking',
			},
			{
				title: 'Webhooks',
				url: '/services/webhooks',
				description:
					'Create webhook endpoints to receive HTTP callbacks with delivery tracking and retry',
			},
			{
				title: 'Schedules',
				url: '/services/schedules',
				description: 'Create platform-managed cron jobs with HTTP and sandbox destinations',
			},
			{
				title: 'Tasks',
				url: '/services/tasks',
				description:
					'Track work items, issues, and agent activity with built-in lifecycle management',
			},
			{
				title: 'Authentication',
				url: '/services/authentication',
				description: 'Session auth, API keys, and bearer tokens for agents and routes',
			},
			{
				title: 'Coder',
				url: '/services/coder',
				description:
					'Manage AI coding sessions that run in cloud sandboxes with full lifecycle, replay, and reconnect support',
			},
			{
				title: 'Observability',
				url: '/services/observability',
				items: [
					{
						title: 'Logging',
						url: '/services/observability/logging',
						description: 'Structured logging for agents and routes',
					},
					{
						title: 'Tracing',
						url: '/services/observability/tracing',
						description:
							'OpenTelemetry spans for performance debugging and operation tracking',
					},
					{
						title: 'Sessions & Debugging',
						url: '/services/observability/sessions-debugging',
						description: 'Debug agents using session IDs, CLI commands, and trace timelines',
					},
					{
						title: 'Web Analytics',
						url: '/services/observability/web-analytics',
						description:
							'Track page views, user engagement, and custom events in your frontend',
					},
				],
			},
			{
				title: 'Sandbox',
				url: '/services/sandbox',
				items: [
					{
						title: 'SDK Usage',
						url: '/services/sandbox/sdk-usage',
						description: 'Programmatic API for creating and managing sandboxes',
					},
					{
						title: 'Snapshots',
						url: '/services/sandbox/snapshots',
						description: 'Save and restore sandbox filesystem states for faster cold starts',
					},
				],
			},
		],
	},
	{
		title: 'Cookbook',
		url: '/cookbook',
		items: [
			{
				title: 'Tutorials',
				items: [
					{
						title: 'Understanding Agents',
						url: '/cookbook/tutorials/understanding-agents',
						description:
							'Learn how AI agents use tools, run in loops with stopping conditions, and leverage LLMs to complete tasks autonomously',
					},
					{
						title: 'RAG Agent',
						url: '/cookbook/tutorials/rag-agent',
						description:
							'Create a retrieval-augmented generation agent with vector search and citations',
					},
				],
			},
			{
				title: 'Patterns',
				items: [
					{
						title: 'Coder',
						items: [
							{
								title: 'Manage Sessions',
								url: '/cookbook/patterns/creating-coder-sessions-with-sdk',
								description:
									'Create a Coder session, read its state, and manage its lifecycle with CoderClient',
							},
							{
								title: 'Loop-Mode Sessions',
								url: '/cookbook/patterns/creating-loop-mode-coder-sessions',
								description:
									'Create a loop-mode Coder session and inspect its workflow state with getLoopState',
							},
							{
								title: 'Built-In Agents',
								url: '/cookbook/patterns/choosing-built-in-agents-for-a-coder-session',
								description:
									'Use agentSlugs and defaultAgent to choose which built-in Coder agents are available in a session',
							},
							{
								title: 'Attach Skills',
								url: '/cookbook/patterns/attaching-skills-to-a-coder-session',
								description:
									'Save skills, group them into buckets, and attach them to a Coder session with CoderClient',
							},
							{
								title: 'Use Workspaces',
								url: '/cookbook/patterns/using-workspaces-to-reuse-repos-skills-and-agent-selection',
								description:
									'Store reusable Coder selections in a workspace and attach them to sessions with workspaceId',
							},
							{
								title: 'Reconnect Sessions',
								url: '/cookbook/patterns/preparing-coder-sessions-for-remote-attach',
								description:
									'Use listConnectableSessions and prepareSessionForRemoteAttach to find sessions you can still reconnect to',
							},
							{
								title: 'Observe Sessions',
								url: '/cookbook/patterns/observing-a-coder-session-through-the-hub',
								description:
									"Subscribe to a session's live event stream, page through its event history, and hydrate a client from the durable replay stream",
							},
						],
					},
					{
						title: 'Autonomous Research',
						url: '/cookbook/patterns/autonomous-research',
						description:
							'Build a recursive research loop using the Anthropic SDK with native tool calling',
					},
					{
						title: 'Background Tasks',
						url: '/cookbook/patterns/background-tasks',
						description: 'Use waitUntil to run work after responding to the client',
					},
					{
						title: 'Chat with History',
						url: '/cookbook/patterns/chat-with-history',
						description:
							'Build a chat agent that remembers previous messages using thread state',
					},
					{
						title: 'Cron with Storage',
						url: '/cookbook/patterns/cron-with-storage',
						description: 'Cache scheduled task results in KV for later retrieval',
					},
					{
						title: 'Hono RPC + TanStack',
						url: '/cookbook/patterns/hono-rpc-tanstack-query',
						description:
							'Get end-to-end type safety between your Agentuity API routes and React frontend using Hono RPC and TanStack Query',
					},
					{
						title: 'LLM as a Judge',
						url: '/cookbook/patterns/llm-as-a-judge',
						description:
							'Use LLMs to evaluate and score agent outputs for quality, safety, and compliance',
					},
					{
						title: 'Server Utilities',
						url: '/cookbook/patterns/server-utilities',
						description:
							'Use storage, queues, logging, and error handling utilities from external backends like Next.js or Express',
					},
					{
						title: 'Product Search',
						url: '/cookbook/patterns/product-search',
						description: 'Semantic product search with metadata filtering',
					},
					{
						title: 'Tailwind Setup',
						url: '/cookbook/patterns/tailwind-setup',
						description: 'Add Tailwind CSS styling to your Agentuity frontend',
					},
					{
						title: 'Web Exploration',
						url: '/cookbook/patterns/web-exploration',
						description:
							'Run a headless browser in a sandbox to let agents browse, screenshot, and extract web content',
					},
					{
						title: 'Webhook Handler',
						url: '/cookbook/patterns/webhook-handler',
						description:
							'Handle incoming webhooks with signature verification and background processing',
					},
				],
			},
			{
				title: 'Integrations',
				items: [
					{
						title: 'Mastra',
						url: '/cookbook/integrations/mastra',
						description:
							'Deploy Mastra agents on Agentuity with persistent state, observability, and the AI Gateway',
					},
					{
						title: 'LangChain',
						url: '/cookbook/integrations/langchain',
						description:
							"Build LangChain agents with Agentuity's deployment runtime, persistent storage, and observability",
					},
					{
						title: 'OpenAI Agents SDK',
						url: '/cookbook/integrations/openai-agents',
						description:
							"Run OpenAI Agents SDK tool calling, handoffs, and structured output on Agentuity's deployment runtime",
					},
					{
						title: 'Claude Agent SDK',
						url: '/cookbook/integrations/claude-agent',
						description:
							'Build conversational code intelligence agents with Claude Agent SDK and Agentuity sandboxes',
					},
					{
						title: 'Chat SDK',
						url: '/cookbook/integrations/chat-sdk',
						description:
							'Build multi-platform chatbots for Slack and Discord with Chat SDK and Agentuity agents',
					},
					{
						title: 'Next.js',
						url: '/cookbook/integrations/nextjs',
						description:
							'Connect a Next.js frontend to an Agentuity backend using rewrites and direct router types',
					},
					{
						title: 'TanStack Start',
						url: '/cookbook/integrations/tanstack-start',
						description:
							'Connect a TanStack Start frontend to an Agentuity backend using a Vite proxy and direct router types',
					},
					{
						title: 'Turborepo',
						url: '/cookbook/integrations/turborepo',
						description:
							'Add Agentuity as a workspace app, share schemas across packages, and import router types directly',
					},
				],
			},
		],
	},
	{
		title: 'Community',
		url: '/community',
		items: [
			{
				title: 'Inbound Email Agent',
				url: '/community/inbound-email-agent',
				description: 'Create an AI email auto-responder with Agentuity + Inbound webhooks.',
			},
		],
	},
	{
		title: 'Reference',
		url: '/reference',
		items: [
			{
				title: 'API Reference',
				url: '/reference/api',
				items: [
					{
						title: 'API Keys',
						url: '/reference/api/api-keys',
						description: 'Create and manage API keys for authentication',
					},
					{
						title: 'Coder',
						url: '/reference/api/coder',
						description:
							'Manage Coder sessions, custom agents, session data, loop state, and known users through the REST API',
					},
					{
						title: 'Databases',
						url: '/reference/api/database',
						description: 'Execute queries, inspect tables, and monitor database performance',
					},
					{
						title: 'Durable Streams',
						url: '/reference/api/streams',
						description: 'Create durable, resumable data streams with public URLs',
					},
					{
						title: 'Emails',
						url: '/reference/api/email',
						description:
							'Send and receive emails with managed addresses and webhook destinations',
					},
					{
						title: 'Key-Value Storage',
						url: '/reference/api/key-value',
						description: 'Store and retrieve arbitrary data by key within namespaces',
					},
					{
						title: 'Machines',
						url: '/reference/api/machines',
						description: 'Manage compute nodes and organization authentication enrollment',
					},
					{
						title: 'Message Queues',
						url: '/reference/api/queues',
						description:
							'Publish, consume, and manage messages with worker and pub/sub queues',
					},
					{
						title: 'OAuth Applications',
						url: '/reference/api/oauth',
						description:
							'Manage OAuth 2.0/OIDC applications, client credentials, user consent, and authorization scopes',
					},
					{
						title: 'Object Storage',
						url: '/reference/api/object-storage',
						description: 'Store and manage files and binary objects in buckets',
					},
					{
						title: 'Organizations',
						url: '/reference/api/organizations',
						description:
							'Manage organizations, environment variables, and org-level resources',
					},
					{
						title: 'Projects',
						url: '/reference/api/projects',
						description:
							'Full project lifecycle management including deployments, agents, environment variables, and hostnames',
					},
					{
						title: 'Regions',
						url: '/reference/api/regions',
						description: 'List available cloud regions and manage per-region resources',
					},
					{
						title: 'Sandboxes',
						url: '/reference/api/sandboxes',
						description:
							'Create and manage isolated execution environments with full lifecycle, file system, snapshot, and checkpoint support',
					},
					{
						title: 'Schedules',
						url: '/reference/api/schedules',
						description:
							'Create and manage cron-based scheduled jobs with destinations and delivery tracking',
					},
					{
						title: 'Sessions',
						url: '/reference/api/sessions',
						description:
							'View agent execution sessions with timing, cost, and observability data',
					},
					{
						title: 'Tasks',
						url: '/reference/api/tasks',
						description:
							'Full-featured task management with epics, features, bugs, comments, tags, attachments, and activity tracking',
					},
					{
						title: 'Threads',
						url: '/reference/api/threads',
						description: 'Manage conversation threads for agent session state and user data',
					},
					{
						title: 'Users',
						url: '/reference/api/user',
						description: 'Get authenticated user information and organization memberships',
					},
					{
						title: 'Vector Search',
						url: '/reference/api/vector',
						description: 'Semantic search with automatic embedding generation',
					},
					{
						title: 'Webhooks',
						url: '/reference/api/webhooks',
						description:
							'Manage webhook endpoints, destinations, receipts, deliveries, and analytics',
					},
				],
			},
			{
				title: 'CLI',
				url: '/reference/cli',
				items: [
					{
						title: 'AI Commands',
						url: '/reference/cli/ai-commands',
						description:
							'CLI commands for AI agents, IDE integration, and schema inspection.',
					},
					{
						title: 'Build Configuration',
						url: '/reference/cli/build-configuration',
						description:
							'Customize the build process with Vite plugins and build-time constants',
					},
					{
						title: 'Claude Code Plugin',
						url: '/reference/cli/claude-code-plugin',
						description:
							'Install the Agentuity plugin for Claude Code to get auto-activated skills for deploying and building on Agentuity.',
					},
					{
						title: 'Coder',
						url: '/reference/cli/coder',
						description: 'Start and manage AI coding sessions connected to the Coder Hub',
					},
					{
						title: 'Configuration',
						url: '/reference/cli/configuration',
						description: 'Manage environment variables, secrets, and API keys from the CLI.',
					},
					{
						title: 'Debugging',
						url: '/reference/cli/debugging',
						description:
							'SSH into containers, inspect sessions, and troubleshoot issues in your deployed agents.',
					},
					{
						title: 'Deployment',
						url: '/reference/cli/deployment',
						description:
							'Deploy your agents to Agentuity Cloud with automatic infrastructure provisioning.',
					},
					{
						title: 'Development',
						url: '/reference/cli/development',
						description:
							'Run the development server with hot reload, type checking, and public URL support.',
					},
					{
						title: 'Getting Started',
						url: '/reference/cli/getting-started',
						description:
							'Install the Agentuity CLI and authenticate to start building agents.',
					},
					{
						title: 'Git Integration',
						url: '/reference/cli/git-integration',
						description:
							'Link your GitHub account and repositories to enable preview deployments and CI/CD.',
					},
					{
						title: 'Infrastructure Monitoring',
						url: '/reference/cli/monitoring',
						description:
							'Monitor machine health and resource usage from the CLI in real time or as a snapshot',
					},
					{
						title: 'Managing OAuth Apps',
						url: '/reference/cli/oauth',
						description:
							'Create and manage OAuth/OIDC applications for third-party integrations from the CLI',
					},
					{
						title: 'OpenCode Plugin',
						url: '/reference/cli/opencode-plugin',
						description:
							'Install the Agentuity plugin for OpenCode to enable AI-assisted development with specialized agents',
					},
					{
						title: 'Profiles',
						url: '/reference/cli/profiles',
						description:
							'Use separate CLI profiles for different accounts, organizations, and environments.',
					},
					{
						title: 'Sandbox',
						url: '/reference/cli/sandbox',
						description: 'Create and manage isolated execution environments from the CLI',
					},
					{
						title: 'Storage',
						url: '/reference/cli/storage',
						description:
							'Manage Key-Value, S3, Vector, Database, and Stream storage from the CLI.',
					},
				],
			},
			{
				title: 'SDK Reference',
				url: '/reference/sdk-reference',
				items: [
					{
						title: 'Agents',
						url: '/reference/sdk-reference/agents',
						description:
							'Define agents with createAgent(), configure schemas, and write handlers',
					},
					{
						title: 'Application Entry',
						url: '/reference/sdk-reference/application-entry',
						description:
							'Initialize your Agentuity app with createApp() and configure the runtime entry file',
					},
					{
						title: 'Coder',
						url: '/reference/sdk-reference/coder',
						description: 'Manage AI coding sessions, workspaces, and skills with CoderClient',
					},
					{
						title: 'Communication',
						url: '/reference/sdk-reference/communication',
						description: 'Call agents from routes or other agents with type-safe imports',
					},
					{
						title: 'Context API',
						url: '/reference/sdk-reference/context-api',
						description: 'Storage, logging, and services available via the ctx.* object',
					},
					{
						title: 'Email Service',
						url: '/reference/sdk-reference/email-service',
						description: 'Send emails and manage addresses with ctx.email',
					},
					{
						title: 'Events',
						url: '/reference/sdk-reference/events',
						description: 'Lifecycle hooks for monitoring agent, session, and thread events',
					},
					{
						title: 'Observability',
						url: '/reference/sdk-reference/observability',
						description:
							'Structured logging and OpenTelemetry tracing via ctx.logger and ctx.tracer',
					},
					{
						title: 'Queue Service',
						url: '/reference/sdk-reference/queue-service',
						description: 'Publish messages and manage queues with ctx.queue',
					},
					{
						title: 'Router',
						url: '/reference/sdk-reference/router',
						description: 'HTTP endpoints, middleware, WebSocket, SSE, and cron handlers',
					},
					{
						title: 'Runtime Utilities',
						url: '/reference/sdk-reference/advanced',
						description:
							'File imports, standalone execution, context detection, process lifecycle, and build metadata',
					},
					{
						title: 'Sandbox Service',
						url: '/reference/sdk-reference/sandbox-service',
						description: 'Run code in isolated containers with ctx.sandbox',
					},
					{
						title: 'Schedule Service',
						url: '/reference/sdk-reference/schedule-service',
						description: 'Create and manage cron-based scheduled jobs with ctx.schedule',
					},
					{
						title: 'Schema',
						url: '/reference/sdk-reference/schema',
						description: 'Type-safe runtime validation with StandardSchema support',
					},
					{
						title: 'Storage',
						url: '/reference/sdk-reference/storage',
						description: 'KV, Vector, Database, Object, and Stream storage reference',
					},
					{
						title: 'Task Service',
						url: '/reference/sdk-reference/task-service',
						description: 'Track work items with lifecycle management via ctx.task',
					},
				],
			},
			{
				title: 'Standalone Packages',
				url: '/reference/standalone-packages',
				description:
					'Use Agentuity services from any Node.js or Bun application without the full runtime',
			},
			{
				title: 'GitHub App',
				url: '/reference/github-app',
				description:
					'How the Agentuity GitHub App automates deployments from your repositories.',
			},
			{
				title: 'Gravity Network',
				url: '/reference/gravity-network',
				description: "The layered infrastructure powering Agentuity's services",
			},
			{
				title: 'Migration Guide',
				url: '/reference/migration-guide',
				description:
					'Migrate from v1 to v2 for explicit routing, Hono-native routers, and standard Vite config.',
			},
		],
	},
];

// Recursively search for a nav item by URL
function findItemByUrl(items: NavItem[], url: string): NavItem | undefined {
	for (const item of items) {
		if (item.url === url) {
			return item;
		}
		if (item.items) {
			const found = findItemByUrl(item.items, url);
			if (found) return found;
		}
	}
	return undefined;
}

// Helper to find current nav item and section
export function findCurrentNav(currentPage: string): { section?: NavSection; item?: NavItem } {
	const url = currentPage === 'home' ? '/' : `/${currentPage}`;
	for (const section of navData) {
		// Check section URL
		if (section.url === url) {
			return { section };
		}
		// Check items recursively
		const item = findItemByUrl(section.items, url);
		if (item) {
			return { section, item };
		}
	}
	return {};
}

// Recursively collect all leaf nav items (items with URLs, no sub-items or sub-items without URLs)
function collectLeafItems(
	items: NavItem[],
	sectionTitle: string
): Array<NavItem & { section: string }> {
	const result: Array<NavItem & { section: string }> = [];
	for (const item of items) {
		// If item has a URL, it's navigable
		if (item.url) {
			result.push({ ...item, url: item.url, section: sectionTitle });
		}
		// Also recurse into nested items
		if (item.items) {
			result.push(...collectLeafItems(item.items, sectionTitle));
		}
	}
	return result;
}

// Get flat list of all nav items for prev/next navigation
export function getAllNavItems(): Array<NavItem & { section: string; url: string }> {
	const items: Array<NavItem & { section: string; url: string }> = [];
	for (const section of navData) {
		items.push(
			...(collectLeafItems(section.items, section.title) as Array<
				NavItem & { section: string; url: string }
			>)
		);
	}
	return items;
}

// Helper to find prev/next pages
export function findPrevNext(currentPage: string): {
	prev?: NavItem & { section: string; url: string };
	next?: NavItem & { section: string; url: string };
} {
	const allItems = getAllNavItems();
	const url = currentPage === 'home' ? '/' : `/${currentPage}`;
	const currentIndex = allItems.findIndex((item) => item.url === url);

	if (currentIndex === -1) {
		return {};
	}

	return {
		prev: currentIndex > 0 ? allItems[currentIndex - 1] : undefined,
		next: currentIndex < allItems.length - 1 ? allItems[currentIndex + 1] : undefined,
	};
}

// Find the full breadcrumb chain from root section to current page
export function findBreadcrumbChain(currentPage: string): Array<{ title: string; url?: string }> {
	const url = currentPage === 'home' ? '/' : `/${currentPage}`;

	// Home page — no breadcrumbs
	if (url === '/') return [];

	for (const section of navData) {
		// Check if this is the section index page
		if (section.url === url) {
			return [{ title: section.title, url: section.url }];
		}

		// Recursively search items, accumulating ancestors
		const chain = findChainInItems(section.items, url, [
			{ title: section.title, url: section.url },
		]);
		if (chain) return chain;
	}

	return [];
}

// Recursive helper — searches NavItem[] for a matching URL, building up the ancestor chain
function findChainInItems(
	items: NavItem[],
	targetUrl: string,
	ancestors: Array<{ title: string; url?: string }>
): Array<{ title: string; url?: string }> | null {
	for (const item of items) {
		if (item.url === targetUrl) {
			return [...ancestors, { title: item.title, url: item.url }];
		}
		if (item.items) {
			const chain = findChainInItems(item.items, targetUrl, [
				...ancestors,
				{ title: item.title, url: item.url },
			]);
			if (chain) return chain;
		}
	}
	return null;
}

// Check if any item in the tree is active (matches current URL)
export function hasActiveChild(items: NavItem[], currentUrl: string): boolean {
	for (const item of items) {
		if (item.url === currentUrl) return true;
		if (item.items && hasActiveChild(item.items, currentUrl)) return true;
	}
	return false;
}
