/// <reference types="hono" />
// Auto-generated by Agentuity - do not edit manually
import vectorAgent from '../agent/vector/agent';
import keyvalueAgent from '../agent/keyvalue/agent';
import objectstoreAgent from '../agent/objectstore/agent';
import streamAgent from '../agent/stream/agent';
import type { AgentRunner, Logger } from '@agentuity/runtime';
import type { KeyValueStorage, ObjectStorage, StreamStorage, VectorStorage } from '@agentuity/core';
import type { Agent } from '@agentuity/react';

/**
 * Registry of all agents in this application.
 * Provides strongly-typed access to agent metadata and runner functions.
 * Auto-generated from your agent files during build.
 */
export const agentRegistry = {
  vector: vectorAgent,
  keyvalue: keyvalueAgent,
  objectstore: objectstoreAgent,
  stream: streamAgent,
} as const;

// Local type aliases for Hono augmentation
type LocalAgentName = keyof typeof agentRegistry;
type LocalAgentRegistry = typeof agentRegistry;

// Typed runners for each agent
export type VectorAgentRunner = AgentRunner<typeof vectorAgent['inputSchema'], typeof vectorAgent['outputSchema'], typeof vectorAgent['stream'] extends true ? true : false>;
export type KeyvalueAgentRunner = AgentRunner<typeof keyvalueAgent['inputSchema'], typeof keyvalueAgent['outputSchema'], typeof keyvalueAgent['stream'] extends true ? true : false>;
export type ObjectstoreAgentRunner = AgentRunner<typeof objectstoreAgent['inputSchema'], typeof objectstoreAgent['outputSchema'], typeof objectstoreAgent['stream'] extends true ? true : false>;
export type StreamAgentRunner = AgentRunner<typeof streamAgent['inputSchema'], typeof streamAgent['outputSchema'], typeof streamAgent['stream'] extends true ? true : false>;

// Augment @agentuity/runtime types with strongly-typed agents from this project
declare module "@agentuity/runtime" {
	// Augment the AgentRegistry interface with project-specific strongly-typed agents
	export interface AgentRegistry {
		vector: AgentRunner<typeof vectorAgent['inputSchema'], typeof vectorAgent['outputSchema'], typeof vectorAgent['stream'] extends true ? true : false>;
		keyvalue: AgentRunner<typeof keyvalueAgent['inputSchema'], typeof keyvalueAgent['outputSchema'], typeof keyvalueAgent['stream'] extends true ? true : false>;
		objectstore: AgentRunner<typeof objectstoreAgent['inputSchema'], typeof objectstoreAgent['outputSchema'], typeof objectstoreAgent['stream'] extends true ? true : false>;
		stream: AgentRunner<typeof streamAgent['inputSchema'], typeof streamAgent['outputSchema'], typeof streamAgent['stream'] extends true ? true : false>;
	}
}

// Augment Hono Context to provide strongly-typed agents and runtime services
// Note: Properties are added to Context via middleware in @agentuity/runtime
declare module "hono" {
	interface Context {
		agentName: LocalAgentName;
		agent: {
	   vector: AgentRunner<LocalAgentRegistry['vector']['inputSchema'], LocalAgentRegistry['vector']['outputSchema'], LocalAgentRegistry['vector']['stream'] extends true ? true : false>;
	   keyvalue: AgentRunner<LocalAgentRegistry['keyvalue']['inputSchema'], LocalAgentRegistry['keyvalue']['outputSchema'], LocalAgentRegistry['keyvalue']['stream'] extends true ? true : false>;
	   objectstore: AgentRunner<LocalAgentRegistry['objectstore']['inputSchema'], LocalAgentRegistry['objectstore']['outputSchema'], LocalAgentRegistry['objectstore']['stream'] extends true ? true : false>;
	   stream: AgentRunner<LocalAgentRegistry['stream']['inputSchema'], LocalAgentRegistry['stream']['outputSchema'], LocalAgentRegistry['stream']['stream'] extends true ? true : false>;
		};
		waitUntil: (promise: Promise<void> | (() => void | Promise<void>)) => void;
		logger: Logger;
		kv: KeyValueStorage;
		objectstore: ObjectStorage;
		stream: StreamStorage;
		vector: VectorStorage;
	}
}

// Augment @agentuity/react types with strongly-typed agents from this project
declare module '@agentuity/react' {
	interface AgentRegistry {
		'vector': Agent<typeof vectorAgent['inputSchema'], typeof vectorAgent['outputSchema']>;
		'keyvalue': Agent<typeof keyvalueAgent['inputSchema'], typeof keyvalueAgent['outputSchema']>;
		'objectstore': Agent<typeof objectstoreAgent['inputSchema'], typeof objectstoreAgent['outputSchema']>;
		'stream': Agent<typeof streamAgent['inputSchema'], typeof streamAgent['outputSchema']>;
	}
}
