// Auto-generated by Agentuity - do not edit manually
import sessionBasicAgent from '../agent/session/session-basic';
import sessionEventsAgent from '../agent/session/session-events';
import v1DataProcessorAgent from '../agent/v1/data/agent';
import websocketEchoAgent from '../agent/websocket/echo-agent';
import evalsBasicAgent from '../agent/evals/basic';
import simpleAgent from '../agent/basic/basic-simple';
import asyncAgent from '../agent/basic/basic-async';
import noOutputAgent from '../agent/basic/basic-no-output';
import noInputAgent from '../agent/basic/basic-no-input';
import lifecycleWaituntilAgent from '../agent/lifecycle/waituntil';
import utilsStringHelperAgent from '../agent/utils/helpers/agent';
import cliAgent from '../agent/cli/agent';
import stateReaderAgent from '../agent/state/reader-agent';
import stateWriterAgent from '../agent/state/writer-agent';
import stateAgent from '../agent/state/agent';
import storageKvIsolationAgent from '../agent/storage/kv/isolation';
import storageKvTypesAgent from '../agent/storage/kv/types';
import storageKvCrudAgent from '../agent/storage/kv/crud';
import storageStreamMetadataAgent from '../agent/storage/stream/metadata';
import storageStreamTypesAgent from '../agent/storage/stream/types';
import storageStreamCrudAgent from '../agent/storage/stream/crud';
import storageBinaryUploadDownloadAgent from '../agent/storage/binary/upload-download';
import storageVectorSearchAgent from '../agent/storage/vector/search';
import storageVectorCrudAgent from '../agent/storage/vector/crud';
import schemaOptionalAgent from '../agent/schema/optional';
import schemaTypesAgent from '../agent/schema/types';
import schemaComplexAgent from '../agent/schema/complex';
import resilienceCrashAttemptsAgent from '../agent/resilience/crash-attempts';
import routingMethodsAgent from '../agent/routing/routing-methods';
import routingPostAgent from '../agent/routing/routing-post';
import routingGetAgent from '../agent/routing/routing-get';
import eventsThreadAgent from '../agent/events/thread-events';
import errorsStructuredAgent from '../agent/errors/structured';
import errorsPropagationAgent from '../agent/errors/propagation';
import routingParamsAgent from '../agent/routing/routing-params';
import errorsValidationAgent from '../agent/errors/validation';
import eventsAgentAgent from '../agent/events/agent-events';
import eventsRemovalAgent from '../agent/events/listener-removal';
import eventsSessionAgent from '../agent/events/session-events';
import eventsMultipleAgent from '../agent/events/multiple-listeners';
import routingHeadersAgent from '../agent/routing/routing-headers';
import type { AgentRunner } from '@agentuity/runtime';

/**
 * Registry of all agents in this application.
 * Provides strongly-typed access to agent metadata and runner functions.
 * Auto-generated from your agent files during build.
 */
export const agentRegistry = {
  sessionBasic: sessionBasicAgent,
  sessionEvents: sessionEventsAgent,
  v1DataProcessor: v1DataProcessorAgent,
  websocketEcho: websocketEchoAgent,
  evalsBasic: evalsBasicAgent,
  simple: simpleAgent,
  async: asyncAgent,
  noOutput: noOutputAgent,
  noInput: noInputAgent,
  lifecycleWaituntil: lifecycleWaituntilAgent,
  utilsStringHelper: utilsStringHelperAgent,
  cli: cliAgent,
  stateReader: stateReaderAgent,
  stateWriter: stateWriterAgent,
  state: stateAgent,
  storageKvIsolation: storageKvIsolationAgent,
  storageKvTypes: storageKvTypesAgent,
  storageKvCrud: storageKvCrudAgent,
  storageStreamMetadata: storageStreamMetadataAgent,
  storageStreamTypes: storageStreamTypesAgent,
  storageStreamCrud: storageStreamCrudAgent,
  storageBinaryUploadDownload: storageBinaryUploadDownloadAgent,
  storageVectorSearch: storageVectorSearchAgent,
  storageVectorCrud: storageVectorCrudAgent,
  schemaOptional: schemaOptionalAgent,
  schemaTypes: schemaTypesAgent,
  schemaComplex: schemaComplexAgent,
  resilienceCrashAttempts: resilienceCrashAttemptsAgent,
  routingMethods: routingMethodsAgent,
  routingPost: routingPostAgent,
  routingGet: routingGetAgent,
  eventsThread: eventsThreadAgent,
  errorsStructured: errorsStructuredAgent,
  errorsPropagation: errorsPropagationAgent,
  routingParams: routingParamsAgent,
  errorsValidation: errorsValidationAgent,
  eventsAgent: eventsAgentAgent,
  eventsRemoval: eventsRemovalAgent,
  eventsSession: eventsSessionAgent,
  eventsMultiple: eventsMultipleAgent,
  routingHeaders: routingHeadersAgent,
} as const;

export type AgentName = keyof typeof agentRegistry;

// Typed runners for each agent
export type SessionBasicAgentRunner = AgentRunner<typeof sessionBasicAgent['inputSchema'], typeof sessionBasicAgent['outputSchema'], typeof sessionBasicAgent['stream'] extends true ? true : false>;
export type SessionEventsAgentRunner = AgentRunner<typeof sessionEventsAgent['inputSchema'], typeof sessionEventsAgent['outputSchema'], typeof sessionEventsAgent['stream'] extends true ? true : false>;
export type V1DataProcessorAgentRunner = AgentRunner<typeof v1DataProcessorAgent['inputSchema'], typeof v1DataProcessorAgent['outputSchema'], typeof v1DataProcessorAgent['stream'] extends true ? true : false>;
export type WebsocketEchoAgentRunner = AgentRunner<typeof websocketEchoAgent['inputSchema'], typeof websocketEchoAgent['outputSchema'], typeof websocketEchoAgent['stream'] extends true ? true : false>;
export type EvalsBasicAgentRunner = AgentRunner<typeof evalsBasicAgent['inputSchema'], typeof evalsBasicAgent['outputSchema'], typeof evalsBasicAgent['stream'] extends true ? true : false>;
export type SimpleAgentRunner = AgentRunner<typeof simpleAgent['inputSchema'], typeof simpleAgent['outputSchema'], typeof simpleAgent['stream'] extends true ? true : false>;
export type AsyncAgentRunner = AgentRunner<typeof asyncAgent['inputSchema'], typeof asyncAgent['outputSchema'], typeof asyncAgent['stream'] extends true ? true : false>;
export type NoOutputAgentRunner = AgentRunner<typeof noOutputAgent['inputSchema'], typeof noOutputAgent['outputSchema'], typeof noOutputAgent['stream'] extends true ? true : false>;
export type NoInputAgentRunner = AgentRunner<typeof noInputAgent['inputSchema'], typeof noInputAgent['outputSchema'], typeof noInputAgent['stream'] extends true ? true : false>;
export type LifecycleWaituntilAgentRunner = AgentRunner<typeof lifecycleWaituntilAgent['inputSchema'], typeof lifecycleWaituntilAgent['outputSchema'], typeof lifecycleWaituntilAgent['stream'] extends true ? true : false>;
export type UtilsStringHelperAgentRunner = AgentRunner<typeof utilsStringHelperAgent['inputSchema'], typeof utilsStringHelperAgent['outputSchema'], typeof utilsStringHelperAgent['stream'] extends true ? true : false>;
export type CliAgentRunner = AgentRunner<typeof cliAgent['inputSchema'], typeof cliAgent['outputSchema'], typeof cliAgent['stream'] extends true ? true : false>;
export type StateReaderAgentRunner = AgentRunner<typeof stateReaderAgent['inputSchema'], typeof stateReaderAgent['outputSchema'], typeof stateReaderAgent['stream'] extends true ? true : false>;
export type StateWriterAgentRunner = AgentRunner<typeof stateWriterAgent['inputSchema'], typeof stateWriterAgent['outputSchema'], typeof stateWriterAgent['stream'] extends true ? true : false>;
export type StateAgentRunner = AgentRunner<typeof stateAgent['inputSchema'], typeof stateAgent['outputSchema'], typeof stateAgent['stream'] extends true ? true : false>;
export type StorageKvIsolationAgentRunner = AgentRunner<typeof storageKvIsolationAgent['inputSchema'], typeof storageKvIsolationAgent['outputSchema'], typeof storageKvIsolationAgent['stream'] extends true ? true : false>;
export type StorageKvTypesAgentRunner = AgentRunner<typeof storageKvTypesAgent['inputSchema'], typeof storageKvTypesAgent['outputSchema'], typeof storageKvTypesAgent['stream'] extends true ? true : false>;
export type StorageKvCrudAgentRunner = AgentRunner<typeof storageKvCrudAgent['inputSchema'], typeof storageKvCrudAgent['outputSchema'], typeof storageKvCrudAgent['stream'] extends true ? true : false>;
export type StorageStreamMetadataAgentRunner = AgentRunner<typeof storageStreamMetadataAgent['inputSchema'], typeof storageStreamMetadataAgent['outputSchema'], typeof storageStreamMetadataAgent['stream'] extends true ? true : false>;
export type StorageStreamTypesAgentRunner = AgentRunner<typeof storageStreamTypesAgent['inputSchema'], typeof storageStreamTypesAgent['outputSchema'], typeof storageStreamTypesAgent['stream'] extends true ? true : false>;
export type StorageStreamCrudAgentRunner = AgentRunner<typeof storageStreamCrudAgent['inputSchema'], typeof storageStreamCrudAgent['outputSchema'], typeof storageStreamCrudAgent['stream'] extends true ? true : false>;
export type StorageBinaryUploadDownloadAgentRunner = AgentRunner<typeof storageBinaryUploadDownloadAgent['inputSchema'], typeof storageBinaryUploadDownloadAgent['outputSchema'], typeof storageBinaryUploadDownloadAgent['stream'] extends true ? true : false>;
export type StorageVectorSearchAgentRunner = AgentRunner<typeof storageVectorSearchAgent['inputSchema'], typeof storageVectorSearchAgent['outputSchema'], typeof storageVectorSearchAgent['stream'] extends true ? true : false>;
export type StorageVectorCrudAgentRunner = AgentRunner<typeof storageVectorCrudAgent['inputSchema'], typeof storageVectorCrudAgent['outputSchema'], typeof storageVectorCrudAgent['stream'] extends true ? true : false>;
export type SchemaOptionalAgentRunner = AgentRunner<typeof schemaOptionalAgent['inputSchema'], typeof schemaOptionalAgent['outputSchema'], typeof schemaOptionalAgent['stream'] extends true ? true : false>;
export type SchemaTypesAgentRunner = AgentRunner<typeof schemaTypesAgent['inputSchema'], typeof schemaTypesAgent['outputSchema'], typeof schemaTypesAgent['stream'] extends true ? true : false>;
export type SchemaComplexAgentRunner = AgentRunner<typeof schemaComplexAgent['inputSchema'], typeof schemaComplexAgent['outputSchema'], typeof schemaComplexAgent['stream'] extends true ? true : false>;
export type ResilienceCrashAttemptsAgentRunner = AgentRunner<typeof resilienceCrashAttemptsAgent['inputSchema'], typeof resilienceCrashAttemptsAgent['outputSchema'], typeof resilienceCrashAttemptsAgent['stream'] extends true ? true : false>;
export type RoutingMethodsAgentRunner = AgentRunner<typeof routingMethodsAgent['inputSchema'], typeof routingMethodsAgent['outputSchema'], typeof routingMethodsAgent['stream'] extends true ? true : false>;
export type RoutingPostAgentRunner = AgentRunner<typeof routingPostAgent['inputSchema'], typeof routingPostAgent['outputSchema'], typeof routingPostAgent['stream'] extends true ? true : false>;
export type RoutingGetAgentRunner = AgentRunner<typeof routingGetAgent['inputSchema'], typeof routingGetAgent['outputSchema'], typeof routingGetAgent['stream'] extends true ? true : false>;
export type EventsThreadAgentRunner = AgentRunner<typeof eventsThreadAgent['inputSchema'], typeof eventsThreadAgent['outputSchema'], typeof eventsThreadAgent['stream'] extends true ? true : false>;
export type ErrorsStructuredAgentRunner = AgentRunner<typeof errorsStructuredAgent['inputSchema'], typeof errorsStructuredAgent['outputSchema'], typeof errorsStructuredAgent['stream'] extends true ? true : false>;
export type ErrorsPropagationAgentRunner = AgentRunner<typeof errorsPropagationAgent['inputSchema'], typeof errorsPropagationAgent['outputSchema'], typeof errorsPropagationAgent['stream'] extends true ? true : false>;
export type RoutingParamsAgentRunner = AgentRunner<typeof routingParamsAgent['inputSchema'], typeof routingParamsAgent['outputSchema'], typeof routingParamsAgent['stream'] extends true ? true : false>;
export type ErrorsValidationAgentRunner = AgentRunner<typeof errorsValidationAgent['inputSchema'], typeof errorsValidationAgent['outputSchema'], typeof errorsValidationAgent['stream'] extends true ? true : false>;
export type EventsAgentAgentRunner = AgentRunner<typeof eventsAgentAgent['inputSchema'], typeof eventsAgentAgent['outputSchema'], typeof eventsAgentAgent['stream'] extends true ? true : false>;
export type EventsRemovalAgentRunner = AgentRunner<typeof eventsRemovalAgent['inputSchema'], typeof eventsRemovalAgent['outputSchema'], typeof eventsRemovalAgent['stream'] extends true ? true : false>;
export type EventsSessionAgentRunner = AgentRunner<typeof eventsSessionAgent['inputSchema'], typeof eventsSessionAgent['outputSchema'], typeof eventsSessionAgent['stream'] extends true ? true : false>;
export type EventsMultipleAgentRunner = AgentRunner<typeof eventsMultipleAgent['inputSchema'], typeof eventsMultipleAgent['outputSchema'], typeof eventsMultipleAgent['stream'] extends true ? true : false>;
export type RoutingHeadersAgentRunner = AgentRunner<typeof routingHeadersAgent['inputSchema'], typeof routingHeadersAgent['outputSchema'], typeof routingHeadersAgent['stream'] extends true ? true : false>;

// Strongly-typed AgentRegistry interface for this project
export interface AgentRegistry {
	sessionBasic: AgentRunner<typeof sessionBasicAgent['inputSchema'], typeof sessionBasicAgent['outputSchema'], typeof sessionBasicAgent['stream'] extends true ? true : false>;
	sessionEvents: AgentRunner<typeof sessionEventsAgent['inputSchema'], typeof sessionEventsAgent['outputSchema'], typeof sessionEventsAgent['stream'] extends true ? true : false>;
	v1DataProcessor: AgentRunner<typeof v1DataProcessorAgent['inputSchema'], typeof v1DataProcessorAgent['outputSchema'], typeof v1DataProcessorAgent['stream'] extends true ? true : false>;
	websocketEcho: AgentRunner<typeof websocketEchoAgent['inputSchema'], typeof websocketEchoAgent['outputSchema'], typeof websocketEchoAgent['stream'] extends true ? true : false>;
	evalsBasic: AgentRunner<typeof evalsBasicAgent['inputSchema'], typeof evalsBasicAgent['outputSchema'], typeof evalsBasicAgent['stream'] extends true ? true : false>;
	simple: AgentRunner<typeof simpleAgent['inputSchema'], typeof simpleAgent['outputSchema'], typeof simpleAgent['stream'] extends true ? true : false>;
	async: AgentRunner<typeof asyncAgent['inputSchema'], typeof asyncAgent['outputSchema'], typeof asyncAgent['stream'] extends true ? true : false>;
	noOutput: AgentRunner<typeof noOutputAgent['inputSchema'], typeof noOutputAgent['outputSchema'], typeof noOutputAgent['stream'] extends true ? true : false>;
	noInput: AgentRunner<typeof noInputAgent['inputSchema'], typeof noInputAgent['outputSchema'], typeof noInputAgent['stream'] extends true ? true : false>;
	lifecycleWaituntil: AgentRunner<typeof lifecycleWaituntilAgent['inputSchema'], typeof lifecycleWaituntilAgent['outputSchema'], typeof lifecycleWaituntilAgent['stream'] extends true ? true : false>;
	utilsStringHelper: AgentRunner<typeof utilsStringHelperAgent['inputSchema'], typeof utilsStringHelperAgent['outputSchema'], typeof utilsStringHelperAgent['stream'] extends true ? true : false>;
	cli: AgentRunner<typeof cliAgent['inputSchema'], typeof cliAgent['outputSchema'], typeof cliAgent['stream'] extends true ? true : false>;
	stateReader: AgentRunner<typeof stateReaderAgent['inputSchema'], typeof stateReaderAgent['outputSchema'], typeof stateReaderAgent['stream'] extends true ? true : false>;
	stateWriter: AgentRunner<typeof stateWriterAgent['inputSchema'], typeof stateWriterAgent['outputSchema'], typeof stateWriterAgent['stream'] extends true ? true : false>;
	state: AgentRunner<typeof stateAgent['inputSchema'], typeof stateAgent['outputSchema'], typeof stateAgent['stream'] extends true ? true : false>;
	storageKvIsolation: AgentRunner<typeof storageKvIsolationAgent['inputSchema'], typeof storageKvIsolationAgent['outputSchema'], typeof storageKvIsolationAgent['stream'] extends true ? true : false>;
	storageKvTypes: AgentRunner<typeof storageKvTypesAgent['inputSchema'], typeof storageKvTypesAgent['outputSchema'], typeof storageKvTypesAgent['stream'] extends true ? true : false>;
	storageKvCrud: AgentRunner<typeof storageKvCrudAgent['inputSchema'], typeof storageKvCrudAgent['outputSchema'], typeof storageKvCrudAgent['stream'] extends true ? true : false>;
	storageStreamMetadata: AgentRunner<typeof storageStreamMetadataAgent['inputSchema'], typeof storageStreamMetadataAgent['outputSchema'], typeof storageStreamMetadataAgent['stream'] extends true ? true : false>;
	storageStreamTypes: AgentRunner<typeof storageStreamTypesAgent['inputSchema'], typeof storageStreamTypesAgent['outputSchema'], typeof storageStreamTypesAgent['stream'] extends true ? true : false>;
	storageStreamCrud: AgentRunner<typeof storageStreamCrudAgent['inputSchema'], typeof storageStreamCrudAgent['outputSchema'], typeof storageStreamCrudAgent['stream'] extends true ? true : false>;
	storageBinaryUploadDownload: AgentRunner<typeof storageBinaryUploadDownloadAgent['inputSchema'], typeof storageBinaryUploadDownloadAgent['outputSchema'], typeof storageBinaryUploadDownloadAgent['stream'] extends true ? true : false>;
	storageVectorSearch: AgentRunner<typeof storageVectorSearchAgent['inputSchema'], typeof storageVectorSearchAgent['outputSchema'], typeof storageVectorSearchAgent['stream'] extends true ? true : false>;
	storageVectorCrud: AgentRunner<typeof storageVectorCrudAgent['inputSchema'], typeof storageVectorCrudAgent['outputSchema'], typeof storageVectorCrudAgent['stream'] extends true ? true : false>;
	schemaOptional: AgentRunner<typeof schemaOptionalAgent['inputSchema'], typeof schemaOptionalAgent['outputSchema'], typeof schemaOptionalAgent['stream'] extends true ? true : false>;
	schemaTypes: AgentRunner<typeof schemaTypesAgent['inputSchema'], typeof schemaTypesAgent['outputSchema'], typeof schemaTypesAgent['stream'] extends true ? true : false>;
	schemaComplex: AgentRunner<typeof schemaComplexAgent['inputSchema'], typeof schemaComplexAgent['outputSchema'], typeof schemaComplexAgent['stream'] extends true ? true : false>;
	resilienceCrashAttempts: AgentRunner<typeof resilienceCrashAttemptsAgent['inputSchema'], typeof resilienceCrashAttemptsAgent['outputSchema'], typeof resilienceCrashAttemptsAgent['stream'] extends true ? true : false>;
	routingMethods: AgentRunner<typeof routingMethodsAgent['inputSchema'], typeof routingMethodsAgent['outputSchema'], typeof routingMethodsAgent['stream'] extends true ? true : false>;
	routingPost: AgentRunner<typeof routingPostAgent['inputSchema'], typeof routingPostAgent['outputSchema'], typeof routingPostAgent['stream'] extends true ? true : false>;
	routingGet: AgentRunner<typeof routingGetAgent['inputSchema'], typeof routingGetAgent['outputSchema'], typeof routingGetAgent['stream'] extends true ? true : false>;
	eventsThread: AgentRunner<typeof eventsThreadAgent['inputSchema'], typeof eventsThreadAgent['outputSchema'], typeof eventsThreadAgent['stream'] extends true ? true : false>;
	errorsStructured: AgentRunner<typeof errorsStructuredAgent['inputSchema'], typeof errorsStructuredAgent['outputSchema'], typeof errorsStructuredAgent['stream'] extends true ? true : false>;
	errorsPropagation: AgentRunner<typeof errorsPropagationAgent['inputSchema'], typeof errorsPropagationAgent['outputSchema'], typeof errorsPropagationAgent['stream'] extends true ? true : false>;
	routingParams: AgentRunner<typeof routingParamsAgent['inputSchema'], typeof routingParamsAgent['outputSchema'], typeof routingParamsAgent['stream'] extends true ? true : false>;
	errorsValidation: AgentRunner<typeof errorsValidationAgent['inputSchema'], typeof errorsValidationAgent['outputSchema'], typeof errorsValidationAgent['stream'] extends true ? true : false>;
	eventsAgent: AgentRunner<typeof eventsAgentAgent['inputSchema'], typeof eventsAgentAgent['outputSchema'], typeof eventsAgentAgent['stream'] extends true ? true : false>;
	eventsRemoval: AgentRunner<typeof eventsRemovalAgent['inputSchema'], typeof eventsRemovalAgent['outputSchema'], typeof eventsRemovalAgent['stream'] extends true ? true : false>;
	eventsSession: AgentRunner<typeof eventsSessionAgent['inputSchema'], typeof eventsSessionAgent['outputSchema'], typeof eventsSessionAgent['stream'] extends true ? true : false>;
	eventsMultiple: AgentRunner<typeof eventsMultipleAgent['inputSchema'], typeof eventsMultipleAgent['outputSchema'], typeof eventsMultipleAgent['stream'] extends true ? true : false>;
	routingHeaders: AgentRunner<typeof routingHeadersAgent['inputSchema'], typeof routingHeadersAgent['outputSchema'], typeof routingHeadersAgent['stream'] extends true ? true : false>;
}
