// Auto-generated by Agentuity - do not edit manually
import type agent_statePersistenceAgent from '@agents/state/agent';
import type agent_stateReaderAgent from '@agents/state/reader-agent';
import type agent_stateWriterAgent from '@agents/state/writer-agent';

export interface RouteRegistry {
  'GET /api/test/run': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'GET /api/test/suites': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'GET /api/test/list': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'GET /api/health': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'POST /api/agent/state': {
    inputSchema: typeof agent_statePersistenceAgent extends { inputSchema?: infer I } ? I : never;
    outputSchema: typeof agent_statePersistenceAgent extends { outputSchema?: infer O } ? O : never;
    stream: typeof agent_statePersistenceAgent extends { stream?: infer S } ? S : false;
  };
  'POST /api/agent/state-reader': {
    inputSchema: typeof agent_stateReaderAgent extends { inputSchema?: infer I } ? I : never;
    outputSchema: typeof agent_stateReaderAgent extends { outputSchema?: infer O } ? O : never;
    stream: typeof agent_stateReaderAgent extends { stream?: infer S } ? S : false;
  };
  'POST /api/agent/state-writer': {
    inputSchema: typeof agent_stateWriterAgent extends { inputSchema?: infer I } ? I : never;
    outputSchema: typeof agent_stateWriterAgent extends { outputSchema?: infer O } ? O : never;
    stream: typeof agent_stateWriterAgent extends { stream?: infer S } ? S : false;
  };
  'POST /api/auth/login': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'POST /api/auth/logout': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'GET /api/auth/verify': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'GET /api/my-service/status': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'GET /api/my-service/info': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'GET /api/users/profile': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'PATCH /api/users/profile': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'DELETE /api/users/profile': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'GET /api/custom-name/custom': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  'POST /api/custom-name/test': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
}

export interface WebSocketRouteRegistry {
  '/api/ws/echo': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  '/api/ws/broadcast': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  '/api/ws/counter': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
}

export interface SSERouteRegistry {
  '/api/sse/simple': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  '/api/sse/events': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  '/api/sse/counter': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  '/api/sse/long-lived': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  '/api/sse/abort-test': {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
}
