// Auto-generated by Agentuity - do not edit manually
import type agent_statePersistenceAgent from '@agents/state/agent';
import type agent_stateReaderAgent from '@agents/state/reader-agent';
import type agent_stateWriterAgent from '@agents/state/writer-agent';

export interface RouteRegistry {
  getApiTestRun: {
    method: 'GET';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  getApiTestSuites: {
    method: 'GET';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  getApiTestList: {
    method: 'GET';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  getApiHealth: {
    method: 'GET';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  postApiAgentState: {
    method: 'POST';
    inputSchema: typeof agent_statePersistenceAgent extends { inputSchema?: infer I } ? I : never;
    outputSchema: typeof agent_statePersistenceAgent extends { outputSchema?: infer O } ? O : never;
    stream: typeof agent_statePersistenceAgent extends { stream?: infer S } ? S : false;
  };
  postApiAgentStateReader: {
    method: 'POST';
    inputSchema: typeof agent_stateReaderAgent extends { inputSchema?: infer I } ? I : never;
    outputSchema: typeof agent_stateReaderAgent extends { outputSchema?: infer O } ? O : never;
    stream: typeof agent_stateReaderAgent extends { stream?: infer S } ? S : false;
  };
  postApiAgentStateWriter: {
    method: 'POST';
    inputSchema: typeof agent_stateWriterAgent extends { inputSchema?: infer I } ? I : never;
    outputSchema: typeof agent_stateWriterAgent extends { outputSchema?: infer O } ? O : never;
    stream: typeof agent_stateWriterAgent extends { stream?: infer S } ? S : false;
  };
  postApiAuthLogin: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  postApiAuthLogout: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  getApiAuthVerify: {
    method: 'GET';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  getApiMyServiceStatus: {
    method: 'GET';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  getApiMyServiceInfo: {
    method: 'GET';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  getApiUsersProfile: {
    method: 'GET';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  patchApiUsersProfile: {
    method: 'PATCH';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  deleteApiUsersProfile: {
    method: 'DELETE';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  getApiCustomNameCustom: {
    method: 'GET';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  postApiCustomNameTest: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
}

export interface WebSocketRouteRegistry {
  postApiWsEcho: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  postApiWsBroadcast: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  postApiWsCounter: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
}

export interface SSERouteRegistry {
  postApiSseSimple: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  postApiSseEvents: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  postApiSseCounter: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  postApiSseLongLived: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  postApiSseAbortTest: {
    method: 'POST';
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
}
