// Auto-generated by Agentuity - do not edit manually
import type agent_statePersistenceAgent from '@agents/state/agent';
import type agent_stateReaderAgent from '@agents/state/reader-agent';
import type agent_stateWriterAgent from '@agents/state/writer-agent';

export interface RouteRegistry {
  get: {
    api: {
      test: {
        run: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
        suites: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
        list: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
      };
      health: {
        inputSchema: never;
        outputSchema: never;
        stream: false;
      };
      auth: {
        verify: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
      };
      my-service: {
        status: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
        info: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
      };
      users: {
        profile: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
      };
      custom-name: {
        custom: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
      };
    };
  };
  post: {
    api: {
      agent: {
        state: {
          inputSchema: typeof agent_statePersistenceAgent extends { inputSchema?: infer I } ? I : never;
          outputSchema: typeof agent_statePersistenceAgent extends { outputSchema?: infer O } ? O : never;
          stream: typeof agent_statePersistenceAgent extends { stream?: infer S } ? S : false;
        };
        state-reader: {
          inputSchema: typeof agent_stateReaderAgent extends { inputSchema?: infer I } ? I : never;
          outputSchema: typeof agent_stateReaderAgent extends { outputSchema?: infer O } ? O : never;
          stream: typeof agent_stateReaderAgent extends { stream?: infer S } ? S : false;
        };
        state-writer: {
          inputSchema: typeof agent_stateWriterAgent extends { inputSchema?: infer I } ? I : never;
          outputSchema: typeof agent_stateWriterAgent extends { outputSchema?: infer O } ? O : never;
          stream: typeof agent_stateWriterAgent extends { stream?: infer S } ? S : false;
        };
      };
      auth: {
        login: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
        logout: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
      };
      custom-name: {
        test: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
      };
    };
  };
  patch: {
    api: {
      users: {
        profile: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
      };
    };
  };
  delete: {
    api: {
      users: {
        profile: {
          inputSchema: never;
          outputSchema: never;
          stream: false;
        };
      };
    };
  };
}

export interface WebSocketRouteRegistry {
  api_ws_echo: {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  api_ws_broadcast: {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  api_ws_counter: {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
}

export interface SSERouteRegistry {
  api_sse_simple: {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  api_sse_events: {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  api_sse_counter: {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  api_sse_long-lived: {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
  api_sse_abort-test: {
    inputSchema: never;
    outputSchema: never;
    stream: false;
  };
}
