/// <reference types="hono" />
// Auto-generated by Agentuity - do not edit manually
import vectorAgent from '../agent/vector/agent';
import testMultipleUnderscoresAgent from '../agent/test__multiple___underscores/agent';
import testMultipleDashesAgent from '../agent/test-multiple--dashes/agent';
import testAgentWithSpacesAgent from '../agent/test agent with spaces/agent';
import streamAgent from '../agent/stream/agent';
import objectstoreAgent from '../agent/objectstore/agent';
import myTestAgentAgent from '../agent/my-test-agent/agent';
import keyvalueAgent from '../agent/keyvalue/agent';
import evalrunAgent from '../agent/evalrun/agent';
import type { AgentRunner, Logger } from '@agentuity/runtime';
import type { KeyValueStorage, ObjectStorage, StreamStorage, VectorStorage } from '@agentuity/core';
import type { Agent } from '@agentuity/react';

/**
 * Registry of all agents in this application.
 * Provides strongly-typed access to agent metadata and runner functions.
 * Auto-generated from your agent files during build.
 */
export const agentRegistry = {
  vector: vectorAgent,
  testMultipleUnderscores: testMultipleUnderscoresAgent,
  testMultipleDashes: testMultipleDashesAgent,
  testAgentWithSpaces: testAgentWithSpacesAgent,
  stream: streamAgent,
  objectstore: objectstoreAgent,
  myTestAgent: myTestAgentAgent,
  keyvalue: keyvalueAgent,
  evalrun: evalrunAgent,
} as const;

// Local type aliases for Hono augmentation
type LocalAgentName = keyof typeof agentRegistry;
type LocalAgentRegistry = typeof agentRegistry;

// Typed runners for each agent
export type VectorAgentRunner = AgentRunner<typeof vectorAgent['inputSchema'], typeof vectorAgent['outputSchema'], typeof vectorAgent['stream'] extends true ? true : false>;
export type TestMultipleUnderscoresAgentRunner = AgentRunner<typeof testMultipleUnderscoresAgent['inputSchema'], typeof testMultipleUnderscoresAgent['outputSchema'], typeof testMultipleUnderscoresAgent['stream'] extends true ? true : false>;
export type TestMultipleDashesAgentRunner = AgentRunner<typeof testMultipleDashesAgent['inputSchema'], typeof testMultipleDashesAgent['outputSchema'], typeof testMultipleDashesAgent['stream'] extends true ? true : false>;
export type TestAgentWithSpacesAgentRunner = AgentRunner<typeof testAgentWithSpacesAgent['inputSchema'], typeof testAgentWithSpacesAgent['outputSchema'], typeof testAgentWithSpacesAgent['stream'] extends true ? true : false>;
export type StreamAgentRunner = AgentRunner<typeof streamAgent['inputSchema'], typeof streamAgent['outputSchema'], typeof streamAgent['stream'] extends true ? true : false>;
export type ObjectstoreAgentRunner = AgentRunner<typeof objectstoreAgent['inputSchema'], typeof objectstoreAgent['outputSchema'], typeof objectstoreAgent['stream'] extends true ? true : false>;
export type MyTestAgentAgentRunner = AgentRunner<typeof myTestAgentAgent['inputSchema'], typeof myTestAgentAgent['outputSchema'], typeof myTestAgentAgent['stream'] extends true ? true : false>;
export type KeyvalueAgentRunner = AgentRunner<typeof keyvalueAgent['inputSchema'], typeof keyvalueAgent['outputSchema'], typeof keyvalueAgent['stream'] extends true ? true : false>;
export type EvalrunAgentRunner = AgentRunner<typeof evalrunAgent['inputSchema'], typeof evalrunAgent['outputSchema'], typeof evalrunAgent['stream'] extends true ? true : false>;

// Augment @agentuity/runtime types with strongly-typed agents from this project
declare module "@agentuity/runtime" {
	// Augment the AgentRegistry interface with project-specific strongly-typed agents
	export interface AgentRegistry {
		vector: AgentRunner<typeof vectorAgent['inputSchema'], typeof vectorAgent['outputSchema'], typeof vectorAgent['stream'] extends true ? true : false>;
		testMultipleUnderscores: AgentRunner<typeof testMultipleUnderscoresAgent['inputSchema'], typeof testMultipleUnderscoresAgent['outputSchema'], typeof testMultipleUnderscoresAgent['stream'] extends true ? true : false>;
		testMultipleDashes: AgentRunner<typeof testMultipleDashesAgent['inputSchema'], typeof testMultipleDashesAgent['outputSchema'], typeof testMultipleDashesAgent['stream'] extends true ? true : false>;
		testAgentWithSpaces: AgentRunner<typeof testAgentWithSpacesAgent['inputSchema'], typeof testAgentWithSpacesAgent['outputSchema'], typeof testAgentWithSpacesAgent['stream'] extends true ? true : false>;
		stream: AgentRunner<typeof streamAgent['inputSchema'], typeof streamAgent['outputSchema'], typeof streamAgent['stream'] extends true ? true : false>;
		objectstore: AgentRunner<typeof objectstoreAgent['inputSchema'], typeof objectstoreAgent['outputSchema'], typeof objectstoreAgent['stream'] extends true ? true : false>;
		myTestAgent: AgentRunner<typeof myTestAgentAgent['inputSchema'], typeof myTestAgentAgent['outputSchema'], typeof myTestAgentAgent['stream'] extends true ? true : false>;
		keyvalue: AgentRunner<typeof keyvalueAgent['inputSchema'], typeof keyvalueAgent['outputSchema'], typeof keyvalueAgent['stream'] extends true ? true : false>;
		evalrun: AgentRunner<typeof evalrunAgent['inputSchema'], typeof evalrunAgent['outputSchema'], typeof evalrunAgent['stream'] extends true ? true : false>;
	}
}

// Augment Hono Context to provide strongly-typed agents and runtime services
// Note: Properties are added to Context via middleware in @agentuity/runtime
declare module "hono" {
	interface Context {
		agentName: LocalAgentName;
		agent: {
	   vector: AgentRunner<LocalAgentRegistry['vector']['inputSchema'], LocalAgentRegistry['vector']['outputSchema'], LocalAgentRegistry['vector']['stream'] extends true ? true : false>;
	   testMultipleUnderscores: AgentRunner<LocalAgentRegistry['testMultipleUnderscores']['inputSchema'], LocalAgentRegistry['testMultipleUnderscores']['outputSchema'], LocalAgentRegistry['testMultipleUnderscores']['stream'] extends true ? true : false>;
	   testMultipleDashes: AgentRunner<LocalAgentRegistry['testMultipleDashes']['inputSchema'], LocalAgentRegistry['testMultipleDashes']['outputSchema'], LocalAgentRegistry['testMultipleDashes']['stream'] extends true ? true : false>;
	   testAgentWithSpaces: AgentRunner<LocalAgentRegistry['testAgentWithSpaces']['inputSchema'], LocalAgentRegistry['testAgentWithSpaces']['outputSchema'], LocalAgentRegistry['testAgentWithSpaces']['stream'] extends true ? true : false>;
	   stream: AgentRunner<LocalAgentRegistry['stream']['inputSchema'], LocalAgentRegistry['stream']['outputSchema'], LocalAgentRegistry['stream']['stream'] extends true ? true : false>;
	   objectstore: AgentRunner<LocalAgentRegistry['objectstore']['inputSchema'], LocalAgentRegistry['objectstore']['outputSchema'], LocalAgentRegistry['objectstore']['stream'] extends true ? true : false>;
	   myTestAgent: AgentRunner<LocalAgentRegistry['myTestAgent']['inputSchema'], LocalAgentRegistry['myTestAgent']['outputSchema'], LocalAgentRegistry['myTestAgent']['stream'] extends true ? true : false>;
	   keyvalue: AgentRunner<LocalAgentRegistry['keyvalue']['inputSchema'], LocalAgentRegistry['keyvalue']['outputSchema'], LocalAgentRegistry['keyvalue']['stream'] extends true ? true : false>;
	   evalrun: AgentRunner<LocalAgentRegistry['evalrun']['inputSchema'], LocalAgentRegistry['evalrun']['outputSchema'], LocalAgentRegistry['evalrun']['stream'] extends true ? true : false>;
		};
		waitUntil: (promise: Promise<void> | (() => void | Promise<void>)) => void;
		logger: Logger;
		kv: KeyValueStorage;
		objectstore: ObjectStorage;
		stream: StreamStorage;
		vector: VectorStorage;
	}
}

// Augment @agentuity/react types with strongly-typed agents from this project
declare module '@agentuity/react' {
	interface AgentRegistry {
		'vector': Agent<typeof vectorAgent['inputSchema'], typeof vectorAgent['outputSchema']>;
		'test__multiple___underscores': Agent<typeof testMultipleUnderscoresAgent['inputSchema'], typeof testMultipleUnderscoresAgent['outputSchema']>;
		'test-multiple--dashes': Agent<typeof testMultipleDashesAgent['inputSchema'], typeof testMultipleDashesAgent['outputSchema']>;
		'test agent with spaces': Agent<typeof testAgentWithSpacesAgent['inputSchema'], typeof testAgentWithSpacesAgent['outputSchema']>;
		'stream': Agent<typeof streamAgent['inputSchema'], typeof streamAgent['outputSchema']>;
		'objectstore': Agent<typeof objectstoreAgent['inputSchema'], typeof objectstoreAgent['outputSchema']>;
		'my-test-agent': Agent<typeof myTestAgentAgent['inputSchema'], typeof myTestAgentAgent['outputSchema']>;
		'keyvalue': Agent<typeof keyvalueAgent['inputSchema'], typeof keyvalueAgent['outputSchema']>;
		'evalrun': Agent<typeof evalrunAgent['inputSchema'], typeof evalrunAgent['outputSchema']>;
	}
}
