#!/usr/bin/env bun
/**
 * Generates src/api/sandbox/scripts.ts from src/run/*.ts files.
 *
 * This eliminates manual duplication - edit src/run/*.ts and run this script.
 *
 * Usage: bun run scripts/generate-sandbox-scripts.ts
 */
import { readdir, readFile, writeFile } from 'fs/promises';
import { basename, join } from 'path';

const RUN_DIR = 'src/run';
const OUTPUT_FILE = 'src/api/sandbox/scripts.ts';

// Files to exclude from sandbox scripts (not meant for sandbox execution)
const EXCLUDED_FILES = ['invoke.ts', 'AGENTS.md', 'README.md'];

interface ScriptInfo {
	name: string;
	defaultInput: unknown;
}

/**
 * Extract default input from script content.
 * Looks for the Usage comment which has the canonical example:
 * Usage: bun run src/run/hello.ts '{"name":"World"}'
 */
function extractDefaultInput(content: string): unknown {
	// Match: Usage: bun run src/run/<name>.ts '{"key":"value"}'
	const usageMatch = content.match(/\* Usage: bun run src\/run\/\S+\.ts\s+'({[^']*})'/);
	if (usageMatch?.[1]) {
		try {
			return JSON.parse(usageMatch[1]);
		} catch {
			// Fall through to other patterns
		}
	}

	// Fallback: process.argv[2] ?? '{"name":"World"}'
	const argvMatch = content.match(/process\.argv\[2\]\s*(?:\?\?|\|\|)\s*['"`]({[^'"`]*})['"`]/);
	if (argvMatch?.[1]) {
		try {
			const parsed = JSON.parse(argvMatch[1]);
			// Only use if it has actual values (not just {})
			if (Object.keys(parsed).length > 0) {
				return parsed;
			}
		} catch {
			// Fall through
		}
	}

	return {};
}

async function generateScripts(): Promise<void> {
	const files = await readdir(RUN_DIR);
	const scripts: ScriptInfo[] = [];

	for (const file of files.sort()) {
		if (!file.endsWith('.ts') || EXCLUDED_FILES.includes(file)) {
			continue;
		}

		const name = basename(file, '.ts');
		const filePath = join(RUN_DIR, file);
		const content = await readFile(filePath, 'utf-8');
		const defaultInput = extractDefaultInput(content);

		scripts.push({ name, defaultInput });
	}

	// Generate the output file
	const output = `/**
 * Auto-generated sandbox script metadata.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Edit the source files in src/run/ and run: bun run scripts/generate-sandbox-scripts.ts
 *
 * @generated
 */

/** Valid script names (scripts are baked into the sandbox snapshot) */
export const SCRIPT_NAMES: ReadonlySet<string> = new Set([
${scripts.map(({ name }) => `\t'${name}',`).join('\n')}
]);

/** Default inputs for each script (extracted from source files) */
export const SCRIPT_DEFAULTS: Record<string, unknown> = {
${scripts.map(({ name, defaultInput }) => `\t'${name}': ${JSON.stringify(defaultInput)},`).join('\n')}
};
`;

	await writeFile(OUTPUT_FILE, output);
	console.log(`Generated ${OUTPUT_FILE} with ${scripts.length} scripts:`);
	for (const { name } of scripts) {
		console.log(`  - ${name}`);
	}
}

generateScripts().catch((err) => {
	console.error('Failed to generate scripts:', err);
	process.exit(1);
});
