// Auto-generated by Agentuity bundler - do not edit manually
// Types-only file - safe for client-side imports
import type { Agent } from '@agentuity/server';
import type websocketAgent from './websocket/agent';
import type sseAgent from './sse/agent';
import type smsAgent from './sms/agent';
import type asyncAgent from './async/agent';
import type simpleAgent from './simple/agent';
import type emailAgent from './email/agent';
import type readableStreamAgent from './readable-stream/agent';
import type cronAgent from './cron/agent';

export type AgentRegistry = {
	websocket: typeof websocketAgent;
	sse: typeof sseAgent;
	sms: typeof smsAgent;
	async: typeof asyncAgent;
	simple: typeof simpleAgent;
	email: typeof emailAgent;
	readableStream: typeof readableStreamAgent;
	cron: typeof cronAgent;
};

export type AgentName = keyof AgentRegistry;
