// Auto-generated by Agentuity - do not edit manually
import helloAgent from '../agents/hello/agent';
import type { AgentRunner, Logger } from '@agentuity/runtime';
import type { KeyValueStorage, ObjectStorage, StreamStorage, VectorStorage } from '@agentuity/core';

export const agentRegistry = {
  hello: helloAgent,
} as const;

export type AgentName = keyof typeof agentRegistry;
export type AgentRegistry = typeof agentRegistry;

// Typed runners for each agent
export type HelloAgentRunner = AgentRunner<typeof helloAgent['inputSchema'], typeof helloAgent['outputSchema'], typeof helloAgent['stream'] extends true ? true : false>;

// Augment Context to provide strongly-typed agents
declare module "hono" {
	interface Context {
	   agentName: AgentName;
	   agent: {
	     [K in AgentName]: AgentRunner<AgentRegistry[K]['inputSchema'], AgentRegistry[K]['outputSchema'], AgentRegistry[K]['stream'] extends true ? true : false>;
	   };
	   waitUntil: (promise: Promise<void> | (() => void | Promise<void>)) => void;
	   logger: Logger;
	   kv: KeyValueStorage;
	   objectstore: ObjectStorage;
	   stream: StreamStorage;
	   vector: VectorStorage;
  }
}
