// Auto-generated by Agentuity - do not edit manually
// This file augments @agentuity/react with your project's agent types
import type helloAgent from '../agents/hello/agent';
import type { Agent } from '@agentuity/react';

declare module '@agentuity/react' {
	interface AgentRegistry {
		'hello': Agent<typeof helloAgent['inputSchema'], typeof helloAgent['outputSchema']>;
	}
}
