// Auto-generated by scripts/generate-nav-data.ts — DO NOT EDIT

export interface NavItem {
	title: string;
	url?: string;
	isActive?: boolean;
	/** Short description from MDX frontmatter, used in search results */
	description?: string;
	/** Nested items for subsections */
	items?: NavItem[];
}

export interface NavSection {
	title: string;
	url?: string;
	items: NavItem[];
	/** If true, items are hidden from sidebar but still used for breadcrumb/search */
	hideItems?: boolean;
}

export const navData: NavSection[] = [
	{
		title: 'Home',
		url: '/',
		hideItems: true,
		items: [],
	},
	{
		title: 'SDK Explorer',
		url: '/explorer',
		hideItems: true,
		items: [
			{
				title: 'Hello Agent',
				url: '/explorer/hello',
				description: 'Your first agent - send input, get output',
			},
			{
				title: 'Handler Context',
				url: '/explorer/handler-context',
				description: "See what's available inside your agent handler",
			},
			{
				title: 'Chat',
				url: '/explorer/chat',
				description: 'Conversation memory that persists across messages',
			},
			{
				title: 'KV Storage',
				url: '/explorer/key-value',
				description: 'Store and retrieve data by key, with auto-expiration',
			},
			{
				title: 'Vector Search',
				url: '/explorer/vector-storage',
				description: 'Find content by meaning, not just keywords',
			},
			{
				title: 'Object Storage',
				url: '/explorer/object-storage',
				description: 'Store files with presigned URLs for sharing',
			},
			{
				title: 'AI Gateway',
				url: '/explorer/ai-gateway',
				description: 'Use any AI provider with a single API key',
			},
			{
				title: 'Text Stream',
				url: '/explorer/streaming',
				description: "Stream responses as they're generated",
			},
			{
				title: 'SSE Stream',
				url: '/explorer/sse-stream',
				description: 'Structured streaming with event types and auto-reconnect',
			},
			{
				title: 'WebSocket',
				url: '/explorer/websocket',
				description: 'Real-time bidirectional messaging over a persistent connection',
			},
			{
				title: 'Durable Streams',
				url: '/explorer/durable-stream',
				description: 'Generate content and get a permanent, shareable URL',
			},
			{
				title: 'Agent Calls',
				url: '/explorer/agent-calls',
				description: 'Call agents from routes or other agents',
			},
			{
				title: 'Schedules',
				url: '/explorer/schedules',
				description: 'Create managed schedules and inspect delivery attempts',
			},
			{
				title: 'Model Arena',
				url: '/explorer/model-arena',
				description: 'Compare AI models using another AI as judge',
			},
			{
				title: 'Queues',
				url: '/explorer/queue',
				description: 'Publish, consume, retry, and inspect dead-letter messages',
			},
			{
				title: 'Email',
				url: '/explorer/email',
				description: 'Send transactional emails with platform-managed delivery',
			},
			{
				title: 'Database',
				url: '/explorer/database',
				description: 'Query PostgreSQL with Drizzle ORM and typed schema definitions',
			},
		],
	},
	{
		title: 'Get Started',
		url: '/get-started',
		items: [
			{
				title: 'Quickstart',
				url: '/get-started/quickstart',
				description: 'Create a framework app, add an AI route, and deploy it to Agentuity',
			},
			{
				title: 'Installation',
				url: '/get-started/installation',
				description: 'Install the Agentuity CLI and create a framework project',
			},
			{
				title: 'Project Structure',
				url: '/get-started/project-structure',
				description: 'Understand how Agentuity fits into framework projects',
			},
			{
				title: 'App Configuration',
				url: '/get-started/app-configuration',
				description: 'Configure a v3 Agentuity framework project',
			},
			{
				title: 'What is Agentuity?',
				url: '/get-started/what-is-agentuity',
				description:
					'Build, deploy, and operate TypeScript framework apps with Agentuity services',
			},
		],
	},
	{
		title: 'Frameworks',
		url: '/frameworks',
		items: [
			{
				title: 'Next.js',
				url: '/frameworks/nextjs',
				description:
					'Add Agentuity service clients, local development, and deployment metadata to a Next.js app',
			},
			{
				title: 'Nuxt',
				url: '/frameworks/nuxt',
				description: 'Add Agentuity CLI wiring and deployment validation to a Nuxt app',
			},
			{
				title: 'React Router',
				url: '/frameworks/react-router',
				description: 'Add Agentuity CLI wiring and deployment validation to a React Router app',
			},
			{
				title: 'SvelteKit',
				url: '/frameworks/sveltekit',
				description: 'Add Agentuity CLI wiring and deployment validation to a SvelteKit app',
			},
			{
				title: 'Astro',
				url: '/frameworks/astro',
				description: 'Add Agentuity CLI wiring and deployment validation to an Astro app',
			},
			{
				title: 'Hono',
				url: '/frameworks/hono',
				description: 'Add Agentuity services and deployment context to a Hono app',
			},
			{
				title: 'Vite + React',
				url: '/frameworks/vite-react',
				description: 'Add Agentuity CLI wiring and deployment validation to a Vite React app',
			},
			{
				title: 'TanStack Start',
				url: '/frameworks/tanstack-start',
				description:
					'Add Agentuity service clients to a TanStack Start app and validate the detected build path',
			},
		],
	},
	{
		title: 'Build',
		url: '/build',
		items: [
			{
				title: 'Build Agents',
				url: '/build/agents',
				description:
					'Build model-backed workflows with framework routes and Agentuity service clients',
			},
			{
				title: 'Chat and Streaming',
				url: '/build/chat-and-streaming',
				description:
					'Stream model output from framework routes and persist chat state with Agentuity clients',
			},
			{
				title: 'Tool Calling',
				url: '/build/tool-calling',
				description: 'Let models call bounded app functions from framework routes',
			},
			{
				title: 'State and Memory',
				url: '/build/state-and-memory',
				description:
					'Store app state explicitly with KV, databases, cookies, and service clients',
			},
			{
				title: 'Background Work',
				url: '/build/background-work',
				description:
					'Use queues, status records, and durable streams for work that should outlive a request',
			},
		],
	},
	{
		title: 'Services',
		url: '/services',
		items: [
			{
				title: 'Storage',
				url: '/services/storage',
				items: [
					{
						title: 'Key-Value',
						url: '/services/storage/key-value',
						description: 'Store small durable values by namespace and key with optional TTL',
					},
					{
						title: 'Vector',
						url: '/services/storage/vector',
						description: 'Store documents and embeddings for semantic search and retrieval',
					},
					{
						title: 'Object',
						url: '/services/storage/object',
						description: "Store files and binary data with Bun's native S3 APIs",
					},
					{
						title: 'Durable Streams',
						url: '/services/storage/durable-streams',
						description: 'Write generated output incrementally and keep it available by URL',
					},
					{
						title: 'Custom',
						url: '/services/storage/custom',
						description: 'Swap storage backends behind small app-owned interfaces',
					},
				],
			},
			{
				title: 'Database',
				url: '/services/database',
				items: [
					{
						title: 'Postgres',
						url: '/services/database/postgres',
						description: 'Use Bun-native tagged SQL with Agentuity-managed Postgres',
					},
					{
						title: 'Drizzle',
						url: '/services/database/drizzle',
						description: 'Type-safe database access with Drizzle ORM',
					},
				],
			},
			{
				title: 'Queues',
				url: '/services/queues',
				description:
					'Publish messages for async processing, webhooks, and event-driven workflows',
			},
			{
				title: 'Email',
				url: '/services/email',
				description:
					'Send and receive emails with managed addresses, destinations, and delivery tracking',
			},
			{
				title: 'Tasks',
				url: '/services/tasks',
				description: 'Track work items, issues, and agent activity with lifecycle management',
			},
			{
				title: 'Schedules',
				url: '/services/schedules',
				description: 'Create platform-managed cron jobs with HTTP and sandbox destinations',
			},
			{
				title: 'Webhooks',
				url: '/services/webhooks',
				description:
					'Create webhook endpoints to receive HTTP callbacks with delivery tracking and retry',
			},
			{
				title: 'Sandbox',
				url: '/services/sandbox',
				items: [
					{
						title: 'SDK Usage',
						url: '/services/sandbox/sdk-usage',
						description:
							'Create, execute, inspect, and clean up sandboxes with SandboxClient',
					},
					{
						title: 'Snapshots',
						url: '/services/sandbox/snapshots',
						description:
							'Save sandbox filesystem states and reuse them as bases for new sandboxes',
					},
				],
			},
			{
				title: 'AI Gateway',
				url: '/services/ai-gateway',
				description: 'Route supported LLM SDK calls through Agentuity during local development',
			},
			{
				title: 'Coder',
				url: '/services/coder',
				description:
					'Run coding agents in cloud sessions you can start, inspect, share, and resume',
			},
			{
				title: 'Observability',
				url: '/services/observability',
				items: [
					{
						title: 'Logging',
						url: '/services/observability/logging',
						description: 'Write structured logs from framework apps and Hono routes',
					},
					{
						title: 'Tracing',
						url: '/services/observability/tracing',
						description:
							'OpenTelemetry spans for performance debugging and operation tracking',
					},
					{
						title: 'Sessions & Debugging',
						url: '/services/observability/sessions-debugging',
						description: 'Inspect session records, logs, and timelines',
					},
					{
						title: 'Web Analytics',
						url: '/services/observability/web-analytics',
						description:
							'Track page views, user engagement, and custom events in your frontend',
					},
				],
			},
			{
				title: 'Authentication',
				url: '/services/authentication',
				description:
					'Choose between Agentuity OIDC and framework-owned authentication for v3 apps',
			},
			{
				title: 'OIDC Provider',
				url: '/services/oidc-provider',
				description:
					'Add Agentuity account sign-in and scoped access to your app with OAuth 2.0 and OIDC',
			},
		],
	},
	{
		title: 'Deploy & Operate',
		url: '/deploy-operate',
		items: [
			{
				title: 'Local Development',
				url: '/deploy-operate/local-development',
				description: 'Run your framework dev script with Agentuity environment wiring.',
			},
			{
				title: 'Deploy Framework Apps',
				url: '/deploy-operate/deploy-framework-apps',
				description: 'Build and deploy framework projects with the v3 Agentuity CLI.',
			},
			{
				title: 'Environment Variables',
				url: '/deploy-operate/environment-variables',
				description:
					'Manage local .env files, cloud environment variables, public variables, and secrets.',
			},
		],
	},
	{
		title: 'Cookbook',
		url: '/cookbook',
		items: [
			{
				title: 'Patterns',
				items: [
					{
						title: 'Coder',
						items: [
							{
								title: 'Manage Sessions',
								url: '/cookbook/patterns/creating-coder-sessions-with-sdk',
								description:
									'Create a Coder session, read its state, and manage its lifecycle with CoderClient',
							},
							{
								title: 'Loop-Mode Sessions',
								url: '/cookbook/patterns/creating-loop-mode-coder-sessions',
								description:
									'Create a loop-mode Coder session and inspect its workflow state with getLoopState',
							},
							{
								title: 'Built-In Agents',
								url: '/cookbook/patterns/choosing-built-in-agents-for-a-coder-session',
								description:
									'Use enabledAgents and defaultAgent to choose which built-in Coder agents are available in a session',
							},
							{
								title: 'Attach Skills',
								url: '/cookbook/patterns/attaching-skills-to-a-coder-session',
								description:
									'Save skills, group them into buckets, and attach them to a Coder session with CoderClient',
							},
							{
								title: 'Use Workspaces',
								url: '/cookbook/patterns/using-workspaces-to-reuse-repos-skills-and-agent-selection',
								description:
									'Store reusable Coder selections in a workspace and attach them to sessions with workspaceId',
							},
							{
								title: 'Reconnect Sessions',
								url: '/cookbook/patterns/preparing-coder-sessions-for-remote-attach',
								description:
									'Use listConnectableSessions and prepareSessionForRemoteAttach to find sessions you can still reconnect to',
							},
							{
								title: 'Observe Sessions',
								url: '/cookbook/patterns/observing-a-coder-session-through-the-hub',
								description:
									"Subscribe to a session's live event stream, page through its event history, and hydrate a client from the durable replay stream",
							},
						],
					},
					{
						title: 'Chat with History',
						url: '/cookbook/patterns/chat-with-history',
						description: 'Store chat history with key-value storage from a framework route',
					},
					{
						title: 'Hono RPC + TanStack',
						url: '/cookbook/patterns/hono-rpc-tanstack-query',
						description:
							'Share Hono route types with a React client and wrap calls in TanStack Query',
					},
					{
						title: 'Server Utilities',
						url: '/cookbook/patterns/server-utilities',
						description:
							'Use storage, queues, logging, and error handling utilities from external backends like Next.js or Express',
					},
					{
						title: 'Tailwind Setup',
						url: '/cookbook/patterns/tailwind-setup',
						description: 'Add Tailwind CSS to the framework app you deploy with Agentuity',
					},
				],
			},
		],
	},
	{
		title: 'Community',
		url: '/community',
		items: [],
	},
	{
		title: 'Reference',
		url: '/reference',
		items: [
			{
				title: 'Standalone Packages',
				url: '/reference/standalone-packages',
				description:
					'Use Agentuity service clients from Node.js, Bun, and server framework code',
			},
			{
				title: 'SDK Reference',
				url: '/reference/sdk-reference',
				items: [
					{
						title: 'Coder',
						url: '/reference/sdk-reference/coder',
						description: 'Manage AI coding sessions, workspaces, and skills with CoderClient',
					},
					{
						title: 'Communication',
						url: '/reference/sdk-reference/communication',
						description:
							'Call shared workflow functions from routes, workers, scripts, and other server code',
					},
					{
						title: 'Schema',
						url: '/reference/sdk-reference/schema',
						description:
							'Validate route inputs, shared function inputs, and structured outputs with StandardSchema support',
					},
				],
			},
			{
				title: 'API Reference',
				url: '/reference/api',
				items: [
					{
						title: 'API Keys',
						url: '/reference/api/api-keys',
						description: 'Create and manage API keys for authentication',
					},
					{
						title: 'Coder',
						url: '/reference/api/coder',
						description:
							'Manage Coder sessions, custom agents, session data, loop state, and known users through the REST API',
					},
					{
						title: 'Databases',
						url: '/reference/api/database',
						description: 'Execute queries, inspect tables, and monitor database performance',
					},
					{
						title: 'Durable Streams',
						url: '/reference/api/streams',
						description: 'Create durable, resumable data streams with public URLs',
					},
					{
						title: 'Emails',
						url: '/reference/api/email',
						description:
							'Send and receive emails with managed addresses and webhook destinations',
					},
					{
						title: 'Key-Value Storage',
						url: '/reference/api/key-value',
						description: 'Store and retrieve arbitrary data by key within namespaces',
					},
					{
						title: 'Machines',
						url: '/reference/api/machines',
						description: 'Manage compute nodes and organization authentication enrollment',
					},
					{
						title: 'Message Queues',
						url: '/reference/api/queues',
						description:
							'Publish, consume, and manage messages with worker and pub/sub queues',
					},
					{
						title: 'OAuth Applications',
						url: '/reference/api/oauth',
						description:
							'Manage OAuth 2.0/OIDC applications, client credentials, user consent, and authorization scopes',
					},
					{
						title: 'Object Storage',
						url: '/reference/api/object-storage',
						description: 'Store and manage files and binary objects in buckets',
					},
					{
						title: 'Organizations',
						url: '/reference/api/organizations',
						description:
							'Manage organizations, environment variables, and org-level resources',
					},
					{
						title: 'Projects',
						url: '/reference/api/projects',
						description:
							'Full project lifecycle management including deployments, agents, environment variables, and hostnames',
					},
					{
						title: 'Regions',
						url: '/reference/api/regions',
						description: 'List available cloud regions and manage per-region resources',
					},
					{
						title: 'Sandboxes',
						url: '/reference/api/sandboxes',
						description:
							'Create and manage isolated execution environments with full lifecycle, file system, snapshot, and checkpoint support',
					},
					{
						title: 'Schedules',
						url: '/reference/api/schedules',
						description:
							'Create and manage cron-based scheduled jobs with destinations and delivery tracking',
					},
					{
						title: 'Sessions',
						url: '/reference/api/sessions',
						description:
							'View agent execution sessions with timing, cost, and observability data',
					},
					{
						title: 'Tasks',
						url: '/reference/api/tasks',
						description:
							'Full-featured task management with epics, features, bugs, comments, tags, attachments, and activity tracking',
					},
					{
						title: 'Threads',
						url: '/reference/api/threads',
						description: 'Manage conversation threads for agent session state and user data',
					},
					{
						title: 'Users',
						url: '/reference/api/user',
						description: 'Get authenticated user information and organization memberships',
					},
					{
						title: 'Vector Search',
						url: '/reference/api/vector',
						description: 'Semantic search with automatic embedding generation',
					},
					{
						title: 'Webhooks',
						url: '/reference/api/webhooks',
						description:
							'Manage webhook endpoints, destinations, receipts, deliveries, and analytics',
					},
				],
			},
			{
				title: 'CLI',
				url: '/reference/cli',
				items: [
					{
						title: 'AI Commands',
						url: '/reference/cli/ai-commands',
						description:
							'CLI commands for AI agents, IDE integration, and schema inspection.',
					},
					{
						title: 'Build Configuration',
						url: '/reference/cli/build-configuration',
						description:
							'Build framework apps into Agentuity deployment bundles with launch metadata and static assets.',
					},
					{
						title: 'Claude Code Plugin',
						url: '/reference/cli/claude-code-plugin',
						description:
							'Install the Agentuity plugin for Claude Code to get auto-activated skills for deploying and building on Agentuity.',
					},
					{
						title: 'Coder',
						url: '/reference/cli/coder',
						description: 'Start and manage AI coding sessions connected to the Coder Hub',
					},
					{
						title: 'Configuration',
						url: '/reference/cli/configuration',
						description: 'Manage environment variables, secrets, and API keys from the CLI.',
					},
					{
						title: 'Debugging',
						url: '/reference/cli/debugging',
						description:
							'SSH into containers, inspect sessions, and troubleshoot issues in your deployed agents.',
					},
					{
						title: 'Deployment',
						url: '/reference/cli/deployment',
						description: 'Deploy registered framework apps to Agentuity Cloud.',
					},
					{
						title: 'Development',
						url: '/reference/cli/development',
						description:
							'Run your framework development server with Agentuity environment wiring.',
					},
					{
						title: 'Getting Started',
						url: '/reference/cli/getting-started',
						description:
							'Install the Agentuity CLI, sign in, create framework projects, and register existing apps.',
					},
					{
						title: 'Git Integration',
						url: '/reference/cli/git-integration',
						description:
							'Link your GitHub account and repositories to enable preview deployments and CI/CD.',
					},
					{
						title: 'Infrastructure Monitoring',
						url: '/reference/cli/monitoring',
						description:
							'Monitor machine health and resource usage from the CLI in real time or as a snapshot',
					},
					{
						title: 'Managing OAuth Apps',
						url: '/reference/cli/oauth',
						description: 'Create and manage OAuth/OIDC applications from the CLI',
					},
					{
						title: 'OpenCode Plugin',
						url: '/reference/cli/opencode-plugin',
						description:
							'Install the Agentuity plugin for OpenCode and configure Agentuity Coder agents',
					},
					{
						title: 'Profiles',
						url: '/reference/cli/profiles',
						description:
							'Use separate CLI profiles for different accounts, organizations, and environments.',
					},
					{
						title: 'Sandbox',
						url: '/reference/cli/sandbox',
						description: 'Create and manage isolated execution environments from the CLI',
					},
					{
						title: 'Storage',
						url: '/reference/cli/storage',
						description:
							'Manage Key-Value, S3, Vector, Database, and Stream storage from the CLI.',
					},
				],
			},
			{
				title: 'GitHub App',
				url: '/reference/github-app',
				description:
					'How the Agentuity GitHub App automates deployments from your repositories.',
			},
			{
				title: 'Gravity Network',
				url: '/reference/gravity-network',
				description: "The layered infrastructure powering Agentuity's services",
			},
		],
	},
	{
		title: 'Migration',
		url: '/migration',
		items: [
			{
				title: 'From v2',
				url: '/migration/from-v2',
				description: 'Move a v2 runtime app toward the v3 framework-first app shape.',
			},
			{
				title: 'Runtime to Frameworks',
				url: '/migration/runtime-to-frameworks',
				description: 'Translate v2 runtime concepts into the v3 framework-first model.',
			},
			{
				title: 'Migration CLI',
				url: '/migration/migrate-cli',
				description: 'Run the Agentuity migration tool for v2 to v3 projects.',
			},
		],
	},
];

// Recursively search for a nav item by URL
function findItemByUrl(items: NavItem[], url: string): NavItem | undefined {
	for (const item of items) {
		if (item.url === url) {
			return item;
		}
		if (item.items) {
			const found = findItemByUrl(item.items, url);
			if (found) return found;
		}
	}
	return undefined;
}

// Helper to find current nav item and section
export function findCurrentNav(currentPage: string): { section?: NavSection; item?: NavItem } {
	const url = currentPage === 'home' ? '/' : `/${currentPage}`;
	for (const section of navData) {
		// Check section URL
		if (section.url === url) {
			return { section };
		}
		// Check items recursively
		const item = findItemByUrl(section.items, url);
		if (item) {
			return { section, item };
		}
	}
	return {};
}

// Recursively collect all leaf nav items (items with URLs, no sub-items or sub-items without URLs)
function collectLeafItems(
	items: NavItem[],
	sectionTitle: string
): Array<NavItem & { section: string }> {
	const result: Array<NavItem & { section: string }> = [];
	for (const item of items) {
		// If item has a URL, it's navigable
		if (item.url) {
			result.push({ ...item, url: item.url, section: sectionTitle });
		}
		// Also recurse into nested items
		if (item.items) {
			result.push(...collectLeafItems(item.items, sectionTitle));
		}
	}
	return result;
}

// Get flat list of all nav items for prev/next navigation
export function getAllNavItems(): Array<NavItem & { section: string; url: string }> {
	const items: Array<NavItem & { section: string; url: string }> = [];
	for (const section of navData) {
		items.push(
			...(collectLeafItems(section.items, section.title) as Array<
				NavItem & { section: string; url: string }
			>)
		);
	}
	return items;
}

// Helper to find prev/next pages
export function findPrevNext(currentPage: string): {
	prev?: NavItem & { section: string; url: string };
	next?: NavItem & { section: string; url: string };
} {
	const allItems = getAllNavItems();
	const url = currentPage === 'home' ? '/' : `/${currentPage}`;
	const currentIndex = allItems.findIndex((item) => item.url === url);

	if (currentIndex === -1) {
		return {};
	}

	return {
		prev: currentIndex > 0 ? allItems[currentIndex - 1] : undefined,
		next: currentIndex < allItems.length - 1 ? allItems[currentIndex + 1] : undefined,
	};
}

// Find the full breadcrumb chain from root section to current page
export function findBreadcrumbChain(currentPage: string): Array<{ title: string; url?: string }> {
	const url = currentPage === 'home' ? '/' : `/${currentPage}`;

	// Home page — no breadcrumbs
	if (url === '/') return [];

	for (const section of navData) {
		// Check if this is the section index page
		if (section.url === url) {
			return [{ title: section.title, url: section.url }];
		}

		// Recursively search items, accumulating ancestors
		const chain = findChainInItems(section.items, url, [
			{ title: section.title, url: section.url },
		]);
		if (chain) return chain;
	}

	return [];
}

// Recursive helper — searches NavItem[] for a matching URL, building up the ancestor chain
function findChainInItems(
	items: NavItem[],
	targetUrl: string,
	ancestors: Array<{ title: string; url?: string }>
): Array<{ title: string; url?: string }> | null {
	for (const item of items) {
		if (item.url === targetUrl) {
			return [...ancestors, { title: item.title, url: item.url }];
		}
		if (item.items) {
			const chain = findChainInItems(item.items, targetUrl, [
				...ancestors,
				{ title: item.title, url: item.url },
			]);
			if (chain) return chain;
		}
	}
	return null;
}

// Check if any item in the tree is active (matches current URL)
export function hasActiveChild(items: NavItem[], currentUrl: string): boolean {
	for (const item of items) {
		if (item.url === currentUrl) return true;
		if (item.items && hasActiveChild(item.items, currentUrl)) return true;
	}
	return false;
}
