/**
 * Build script to create the minified analytics beacon
 * This runs as part of the frontend package build and creates dist/beacon.js
 */

import { join, dirname } from 'node:path';

const srcDir = join(dirname(import.meta.dir), 'src');
const distDir = join(dirname(import.meta.dir), 'dist');

const beaconEntryPath = join(srcDir, 'analytics', 'beacon-standalone.ts');
const beaconOutputPath = join(distDir, 'beacon.js');

async function buildBeacon() {
	console.log('Building analytics beacon...');

	const result = await Bun.build({
		entrypoints: [beaconEntryPath],
		minify: true,
		target: 'browser',
		format: 'iife',
	});

	if (!result.success) {
		const errors = result.logs.map((log) => log.message).join('\n');
		console.error('Failed to build beacon:', errors);
		process.exit(1);
	}

	const output = result.outputs[0];
	if (!output) {
		console.error('No output from beacon build');
		process.exit(1);
	}

	const beaconCode = await output.text();

	// Validate beacon content is non-empty
	if (!beaconCode || beaconCode.length === 0) {
		console.error('ERROR: Generated beacon code is empty');
		process.exit(1);
	}

	// Write the minified beacon as a JS file
	await Bun.write(beaconOutputPath, beaconCode);

	// Overwrite the TypeScript-compiled beacon-script.js with the actual minified beacon
	// TypeScript compiles src/beacon-script.ts -> dist/beacon-script.js with empty string
	// We overwrite it with the actual minified beacon code
	const beaconModulePath = join(distDir, 'beacon-script.js');
	const moduleContent = `// Auto-generated - do not edit
// Minified analytics beacon script (overwrites TypeScript output)
export const BEACON_SCRIPT = ${JSON.stringify(beaconCode)};

export function validateBeaconScript() {
	if (!BEACON_SCRIPT || BEACON_SCRIPT.length === 0) {
		throw new Error(
			'BEACON_SCRIPT is empty. The frontend package was not built correctly. ' +
				'Run "bun run build" in @agentuity/frontend to generate the beacon script.'
		);
	}
}
`;
	await Bun.write(beaconModulePath, moduleContent);
	// Note: .d.ts is generated by TypeScript from src/beacon-script.ts

	console.log(`Built beacon: ${beaconCode.length} bytes`);
	console.log(`Output: ${beaconOutputPath}`);
	console.log(`Module: ${beaconModulePath}`);

	// Verify the written file exists and has content
	const writtenFile = Bun.file(beaconModulePath);
	if (!(await writtenFile.exists())) {
		console.error(`ERROR: Failed to write ${beaconModulePath}`);
		process.exit(1);
	}

	const writtenContent = await writtenFile.text();
	if (!writtenContent.includes('BEACON_SCRIPT') || writtenContent.includes('BEACON_SCRIPT = ""')) {
		console.error('ERROR: dist/beacon-script.js does not contain valid BEACON_SCRIPT');
		process.exit(1);
	}

	console.log('✓ Beacon script verified');
}

buildBeacon();
