/**
 * Route Registry Types for @agentuity/react
 *
 * These empty interfaces are augmented by generated code (src/generated/routes.ts)
 * to provide type-safe routing for useAPI, useWebsocket, useEventStream, and createAPIClient.
 *
 * IMPORTANT: The generated code uses `declare module '@agentuity/react'` to augment
 * these interfaces. This is why they must be defined here (in @agentuity/react) rather
 * than imported from @agentuity/frontend.
 */

/**
 * Route registry containing all typed API routes in the application.
 * Auto-generated by the build tool from routes that use validator() middleware.
 *
 * Used by useAPI() hook for type-safe HTTP requests.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface RouteRegistry {
	// Will be augmented by generated code
	// Format: 'METHOD /path': { inputSchema: ..., outputSchema: ..., stream?: boolean }
}

/**
 * WebSocket route registry containing all typed WebSocket routes in the application.
 * Auto-generated by the build tool from routes that use validator() middleware.
 *
 * Used by useWebsocket() hook for type-safe WebSocket connections.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface WebSocketRouteRegistry {
	// Will be augmented by generated code
	// Format: '/path': { inputSchema: ..., outputSchema: ... }
}

/**
 * SSE route registry containing all typed SSE routes in the application.
 * Auto-generated by the build tool from routes that use validator() middleware.
 *
 * Used by useEventStream() hook for type-safe Server-Sent Events.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface SSERouteRegistry {
	// Will be augmented by generated code
	// Format: '/path': { inputSchema: ..., outputSchema: ... }
}

/**
 * RPC route registry containing all typed RPC routes in the application.
 * Used by createClient() and createAPIClient() for type-safe RPC-style API calls.
 * Auto-generated by the build tool from route discovery.
 *
 * Used by createAPIClient() for type-safe RPC-style calls.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface RPCRouteRegistry {
	// Will be augmented by generated code
	// Format: { path: { method: { input: ..., output: ..., type: ... } } }
}
