/**
 * Route registry containing all typed API routes in the application.
 * Auto-generated by the build tool from routes that use validator() middleware.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface RouteRegistry {
	// Will be augmented by generated code
	// Format: 'METHOD /path': { inputSchema: ..., outputSchema: ... }
}

/**
 * WebSocket route registry containing all typed WebSocket routes in the application.
 * Auto-generated by the build tool from routes that use validator() middleware.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface WebSocketRouteRegistry {
	// Will be augmented by generated code
	// Format: '/path': { inputSchema: ..., outputSchema: ... }
}

/**
 * SSE route registry containing all typed SSE routes in the application.
 * Auto-generated by the build tool from routes that use validator() middleware.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface SSERouteRegistry {
	// Will be augmented by generated code
	// Format: '/path': { inputSchema: ..., outputSchema: ... }
}
