/**
 * Route registry containing all typed API routes in the application.
 * Auto-generated by the build tool from routes that use validator() middleware.
 *
 * @remarks
 * This interface is augmented by generated code via `declare module '@agentuity/frontend'`.
 * The augmentation provides type-safe routing for useAPI and other hooks.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface RouteRegistry {
	// Will be augmented by generated code
	// Format: 'METHOD /path': { inputSchema: ..., outputSchema: ..., stream?: boolean }
}

/**
 * WebSocket route registry containing all typed WebSocket routes in the application.
 * Auto-generated by the build tool from routes that use validator() middleware.
 *
 * @remarks
 * This interface is augmented by generated code via `declare module '@agentuity/frontend'`.
 * The augmentation provides type-safe routing for useWebsocket and other hooks.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface WebSocketRouteRegistry {
	// Will be augmented by generated code
	// Format: '/path': { inputSchema: ..., outputSchema: ... }
}

/**
 * SSE route registry containing all typed SSE routes in the application.
 * Auto-generated by the build tool from routes that use validator() middleware.
 *
 * @remarks
 * This interface is augmented by generated code via `declare module '@agentuity/frontend'`.
 * The augmentation provides type-safe routing for useEventStream and other hooks.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface SSERouteRegistry {
	// Will be augmented by generated code
	// Format: '/path': { inputSchema: ..., outputSchema: ... }
}

/**
 * RPC route registry containing all typed RPC routes in the application.
 * Used by createClient() and createAPIClient() for type-safe RPC-style API calls.
 * Auto-generated by the build tool from route discovery.
 *
 * @remarks
 * This interface is augmented by generated code via `declare module '@agentuity/frontend'`.
 * The augmentation provides type-safe routing for createClient and createAPIClient.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface RPCRouteRegistry {
	// Will be augmented by generated code
	// Format: { path: { method: { input: ..., output: ..., type: ... } } }
}
