/**
 * Validate and generate TanStack Router route files for MDX content pages.
 *
 * Each .mdx page in src/web/content/ needs a .tsx route file in
 * src/web/routes/_docs/ to be accessible. Without the route file, the page
 * shows "Not Found" at runtime even though the build passes.
 *
 * By default, generates missing route files automatically. Use --check to
 * validate without generating (exits non-zero if any are missing).
 *
 * Run: bun run scripts/validate-routes.ts [--check]
 */

import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { join, dirname, relative } from 'node:path';
import { Glob } from 'bun';
import matter from 'gray-matter';

const docsRoot = join(import.meta.dir, '..');
const contentDir = join(docsRoot, 'src/web/content');
const routesDir = join(docsRoot, 'src/web/routes/_docs');
const frontmatterOutput = join(docsRoot, 'src/web/components/docs/generated/frontmatter-data.ts');

const checkOnly = process.argv.includes('--check');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Compute the relative import path from a route file to another source file. */
function sourceImport(routeFilePath: string, targetPath: string): string {
	const routeFileDir = dirname(routeFilePath);
	const rel = relative(routeFileDir, targetPath).replace(/\\/g, '/');
	return rel.startsWith('.') ? rel : `./${rel}`;
}

/** Convert a slug like "calling-agents" to title case: "Calling Agents". */
function slugToTitle(slug: string): string {
	return slug
		.split('-')
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
		.join(' ');
}

/** Read the frontmatter title (short_title preferred) from an MDX file. */
async function getCrumb(mdxPath: string): Promise<string> {
	const slug =
		mdxPath
			.replace(/\.mdx$/, '')
			.split('/')
			.pop() || 'page';
	try {
		const content = await readFile(join(contentDir, mdxPath), 'utf-8');
		const { data } = matter(content);
		return data.short_title || data.title || slugToTitle(slug);
	} catch {
		return slugToTitle(slug);
	}
}

function getRouteDetails(mdxPath: string): {
	routeFile: string;
	routePath: string;
	urlPath: string;
} | null {
	if (mdxPath.endsWith('/index.mdx') || mdxPath === 'index.mdx') {
		const dir = mdxPath.replace(/\/?index\.mdx$/, '');
		if (!dir) {
			return null;
		}
		return {
			routeFile: join(routesDir, dir, 'index.tsx'),
			routePath: `${dir}/`,
			urlPath: `/${dir}`,
		};
	}

	const withoutExt = mdxPath.replace(/\.mdx$/, '');
	return {
		routeFile: join(routesDir, `${withoutExt}.tsx`),
		routePath: withoutExt,
		urlPath: `/${withoutExt}`,
	};
}

function routeDeclaration(routePath: string): string {
	const singleLine = `export const Route = createFileRoute('/_docs/${routePath}')({`;
	if (singleLine.length <= 100) {
		return singleLine;
	}
	return `export const Route = createFileRoute(
\t'/_docs/${routePath}'
)({`;
}

/** Generate the content for a route .tsx file. */
function generateRouteFile(
	routePath: string,
	mdxImportPath: string,
	crumb: string,
	importPath: string
): string {
	return `import { createFileRoute } from '@tanstack/react-router';
import { MDXPage } from '${importPath}';
import type { MDXModule } from '${importPath}';
import Content, {
\tfrontmatter,
\ttableOfContents,
} from '${mdxImportPath}';

const mdxModule = {
\tdefault: Content,
\tfrontmatter,
\ttableOfContents,
} satisfies MDXModule;

${routeDeclaration(routePath)}
\tcomponent: () => <MDXPage module={mdxModule} />,
\tstaticData: { crumb: '${crumb.replace(/'/g, "\\'")}' },
});
`;
}

interface FrontmatterData {
	title?: string;
	short_title?: string;
	description?: string;
}

async function readFrontmatterData(mdxPath: string): Promise<FrontmatterData> {
	const content = await readFile(join(contentDir, mdxPath), 'utf-8');
	const { data } = matter(content);
	const frontmatter: FrontmatterData = {};
	if (typeof data.title === 'string') {
		frontmatter.title = data.title;
	}
	if (typeof data.short_title === 'string') {
		frontmatter.short_title = data.short_title;
	}
	if (typeof data.description === 'string') {
		frontmatter.description = data.description;
	}
	return frontmatter;
}

function serializeFrontmatterValue(data: FrontmatterData): string {
	const entries = Object.entries(data)
		.filter(([, value]) => value !== undefined)
		.map(([key, value]) => `\t\t${JSON.stringify(key)}: ${JSON.stringify(value)}`);
	return `{\n${entries.join(',\n')}\n\t}`;
}

function generateFrontmatterData(
	entries: Array<{ urlPath: string; frontmatter: FrontmatterData }>
) {
	const lines = entries
		.sort((a, b) => a.urlPath.localeCompare(b.urlPath))
		.map(
			({ urlPath, frontmatter }) =>
				`\t${JSON.stringify(urlPath)}: ${serializeFrontmatterValue(frontmatter)}`
		);

	return `// Auto-generated by scripts/validate-routes.ts — DO NOT EDIT

export interface FrontmatterData {
\ttitle?: string;
\tshort_title?: string;
\tdescription?: string;
}

export const frontmatterByPath: Record<string, FrontmatterData> = {
${lines.join(',\n')}
};

export function getFrontmatterForRoute(pathname: string): FrontmatterData | null {
\tconst pathOnly = pathname.split('#')[0]?.split('?')[0] || '/';
\tconst normalized = pathOnly !== '/' && pathOnly.endsWith('/') ? pathOnly.slice(0, -1) : pathOnly;
\treturn frontmatterByPath[normalized] || null;
}
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
	const contentGlob = new Glob('**/*.mdx');
	const mdxPaths: string[] = [];
	for await (const mdxPath of contentGlob.scan(contentDir)) {
		mdxPaths.push(mdxPath);
	}
	mdxPaths.sort();

	const staleRoutes: {
		mdxPath: string;
		routeFile: string;
		reason: 'missing' | 'stale';
	}[] = [];
	const frontmatterEntries: Array<{ urlPath: string; frontmatter: FrontmatterData }> = [];
	let checked = 0;

	for (const mdxPath of mdxPaths) {
		const details = getRouteDetails(mdxPath);
		if (!details) {
			checked++;
			continue;
		}

		const crumb = await getCrumb(mdxPath);
		const importPath = sourceImport(
			details.routeFile,
			join(docsRoot, 'src/web/components/docs/mdx-page')
		);
		const mdxImportPath = sourceImport(details.routeFile, join(contentDir, mdxPath));
		const expected = generateRouteFile(details.routePath, mdxImportPath, crumb, importPath);
		const existingFile = Bun.file(details.routeFile);

		if (!(await existingFile.exists())) {
			staleRoutes.push({ mdxPath, routeFile: details.routeFile, reason: 'missing' });
		} else if ((await existingFile.text()) !== expected) {
			staleRoutes.push({ mdxPath, routeFile: details.routeFile, reason: 'stale' });
		}

		frontmatterEntries.push({
			urlPath: details.urlPath,
			frontmatter: await readFrontmatterData(mdxPath),
		});
		checked++;
	}

	const expectedFrontmatterData = generateFrontmatterData(frontmatterEntries);
	const frontmatterFile = Bun.file(frontmatterOutput);
	const frontmatterStale =
		!(await frontmatterFile.exists()) ||
		(await frontmatterFile.text()) !== expectedFrontmatterData;

	if (staleRoutes.length === 0 && !frontmatterStale) {
		console.log(`All ${checked} content pages have current route files.`);
		process.exit(0);
	}

	if (checkOnly) {
		if (staleRoutes.length > 0) {
			console.error(`\nMissing or stale route files for ${staleRoutes.length} page(s):\n`);
			for (const m of staleRoutes) {
				const relRoute = relative(docsRoot, m.routeFile);
				console.error(`  ${m.mdxPath}`);
				console.error(`  -> ${m.reason}: ${relRoute}\n`);
			}
		}

		if (frontmatterStale) {
			console.error(
				`\nFrontmatter data is missing or stale: ${relative(docsRoot, frontmatterOutput)}\n`
			);
		}
		console.error(`${checked} pages checked.\n`);
		process.exit(1);
	}

	// Generate missing or stale route files
	let generated = 0;
	for (const m of staleRoutes) {
		const details = getRouteDetails(m.mdxPath);
		if (!details) continue;
		const crumb = await getCrumb(m.mdxPath);
		const importPath = sourceImport(
			m.routeFile,
			join(docsRoot, 'src/web/components/docs/mdx-page')
		);
		const mdxImportPath = sourceImport(m.routeFile, join(contentDir, m.mdxPath));
		const content = generateRouteFile(details.routePath, mdxImportPath, crumb, importPath);

		await mkdir(dirname(m.routeFile), { recursive: true });
		await writeFile(m.routeFile, content);
		generated++;

		const relRoute = relative(docsRoot, m.routeFile);
		console.log(`${m.reason === 'missing' ? 'Generated' : 'Updated'}: ${relRoute}`);
	}

	if (frontmatterStale) {
		await mkdir(dirname(frontmatterOutput), { recursive: true });
		await writeFile(frontmatterOutput, expectedFrontmatterData);
		console.log(`Updated: ${relative(docsRoot, frontmatterOutput)}`);
	}

	console.log(`\n${checked} pages checked, ${generated} route files updated.`);
}

main().catch((err) => {
	console.error('Failed to validate routes:', err);
	process.exit(1);
});
