/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/_docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoDemoIdRouteImport } from './routes/demo/$demoId'
import { Route as DocsServicesIndexRouteImport } from './routes/_docs/services/index'
import { Route as DocsRoutesIndexRouteImport } from './routes/_docs/routes/index'
import { Route as DocsReferenceIndexRouteImport } from './routes/_docs/reference/index'
import { Route as DocsGetStartedIndexRouteImport } from './routes/_docs/get-started/index'
import { Route as DocsFrontendIndexRouteImport } from './routes/_docs/frontend/index'
import { Route as DocsCookbookIndexRouteImport } from './routes/_docs/cookbook/index'
import { Route as DocsCommunityIndexRouteImport } from './routes/_docs/community/index'
import { Route as DocsApisIndexRouteImport } from './routes/_docs/apis/index'
import { Route as DocsAgentsIndexRouteImport } from './routes/_docs/agents/index'
import { Route as DocsServicesQueuesRouteImport } from './routes/_docs/services/queues'
import { Route as DocsRoutesWebsocketsRouteImport } from './routes/_docs/routes/websockets'
import { Route as DocsRoutesSseRouteImport } from './routes/_docs/routes/sse'
import { Route as DocsRoutesMiddlewareRouteImport } from './routes/_docs/routes/middleware'
import { Route as DocsRoutesHttpRouteImport } from './routes/_docs/routes/http'
import { Route as DocsRoutesCronRouteImport } from './routes/_docs/routes/cron'
import { Route as DocsReferenceSdkReferenceRouteImport } from './routes/_docs/reference/sdk-reference'
import { Route as DocsReferenceMigrationGuideRouteImport } from './routes/_docs/reference/migration-guide'
import { Route as DocsReferenceMdxFeaturesRouteImport } from './routes/_docs/reference/mdx-features'
import { Route as DocsReferenceGravityNetworkRouteImport } from './routes/_docs/reference/gravity-network'
import { Route as DocsGetStartedWhatIsAgentuityRouteImport } from './routes/_docs/get-started/what-is-agentuity'
import { Route as DocsGetStartedQuickstartRouteImport } from './routes/_docs/get-started/quickstart'
import { Route as DocsGetStartedProjectStructureRouteImport } from './routes/_docs/get-started/project-structure'
import { Route as DocsGetStartedInstallationRouteImport } from './routes/_docs/get-started/installation'
import { Route as DocsGetStartedAppConfigurationRouteImport } from './routes/_docs/get-started/app-configuration'
import { Route as DocsFrontendWorkbenchRouteImport } from './routes/_docs/frontend/workbench'
import { Route as DocsFrontendRpcClientRouteImport } from './routes/_docs/frontend/rpc-client'
import { Route as DocsFrontendReactHooksRouteImport } from './routes/_docs/frontend/react-hooks'
import { Route as DocsFrontendProviderSetupRouteImport } from './routes/_docs/frontend/provider-setup'
import { Route as DocsFrontendDeploymentScenariosRouteImport } from './routes/_docs/frontend/deployment-scenarios'
import { Route as DocsFrontendAuthenticationRouteImport } from './routes/_docs/frontend/authentication'
import { Route as DocsFrontendAdvancedHooksRouteImport } from './routes/_docs/frontend/advanced-hooks'
import { Route as DocsApisWhenToUseRouteImport } from './routes/_docs/apis/when-to-use'
import { Route as DocsApisCallingAgentsRouteImport } from './routes/_docs/apis/calling-agents'
import { Route as DocsAgentsWorkbenchRouteImport } from './routes/_docs/agents/workbench'
import { Route as DocsAgentsStreamingResponsesRouteImport } from './routes/_docs/agents/streaming-responses'
import { Route as DocsAgentsStateManagementRouteImport } from './routes/_docs/agents/state-management'
import { Route as DocsAgentsStandaloneExecutionRouteImport } from './routes/_docs/agents/standalone-execution'
import { Route as DocsAgentsSchemaLibrariesRouteImport } from './routes/_docs/agents/schema-libraries'
import { Route as DocsAgentsEventsLifecycleRouteImport } from './routes/_docs/agents/events-lifecycle'
import { Route as DocsAgentsEvaluationsRouteImport } from './routes/_docs/agents/evaluations'
import { Route as DocsAgentsCreatingAgentsRouteImport } from './routes/_docs/agents/creating-agents'
import { Route as DocsAgentsCallingOtherAgentsRouteImport } from './routes/_docs/agents/calling-other-agents'
import { Route as DocsAgentsAiSdkIntegrationRouteImport } from './routes/_docs/agents/ai-sdk-integration'
import { Route as DocsAgentsAiGatewayRouteImport } from './routes/_docs/agents/ai-gateway'
import { Route as DocsServicesStorageIndexRouteImport } from './routes/_docs/services/storage/index'
import { Route as DocsServicesSandboxIndexRouteImport } from './routes/_docs/services/sandbox/index'
import { Route as DocsServicesObservabilityIndexRouteImport } from './routes/_docs/services/observability/index'
import { Route as DocsServicesDatabaseIndexRouteImport } from './routes/_docs/services/database/index'
import { Route as DocsReferenceCliIndexRouteImport } from './routes/_docs/reference/cli/index'
import { Route as DocsCookbookTutorialsIndexRouteImport } from './routes/_docs/cookbook/tutorials/index'
import { Route as DocsCookbookPatternsIndexRouteImport } from './routes/_docs/cookbook/patterns/index'
import { Route as DocsServicesStorageVectorRouteImport } from './routes/_docs/services/storage/vector'
import { Route as DocsServicesStorageObjectRouteImport } from './routes/_docs/services/storage/object'
import { Route as DocsServicesStorageKeyValueRouteImport } from './routes/_docs/services/storage/key-value'
import { Route as DocsServicesStorageDurableStreamsRouteImport } from './routes/_docs/services/storage/durable-streams'
import { Route as DocsServicesStorageDatabaseRouteImport } from './routes/_docs/services/storage/database'
import { Route as DocsServicesStorageCustomRouteImport } from './routes/_docs/services/storage/custom'
import { Route as DocsServicesSandboxSnapshotsRouteImport } from './routes/_docs/services/sandbox/snapshots'
import { Route as DocsServicesSandboxSdkUsageRouteImport } from './routes/_docs/services/sandbox/sdk-usage'
import { Route as DocsServicesObservabilityTracingRouteImport } from './routes/_docs/services/observability/tracing'
import { Route as DocsServicesObservabilitySessionsDebuggingRouteImport } from './routes/_docs/services/observability/sessions-debugging'
import { Route as DocsServicesObservabilityLoggingRouteImport } from './routes/_docs/services/observability/logging'
import { Route as DocsServicesDatabasePostgresRouteImport } from './routes/_docs/services/database/postgres'
import { Route as DocsServicesDatabaseDrizzleRouteImport } from './routes/_docs/services/database/drizzle'
import { Route as DocsReferenceCliStorageRouteImport } from './routes/_docs/reference/cli/storage'
import { Route as DocsReferenceCliSandboxRouteImport } from './routes/_docs/reference/cli/sandbox'
import { Route as DocsReferenceCliOpencodePluginRouteImport } from './routes/_docs/reference/cli/opencode-plugin'
import { Route as DocsReferenceCliGettingStartedRouteImport } from './routes/_docs/reference/cli/getting-started'
import { Route as DocsReferenceCliDevelopmentRouteImport } from './routes/_docs/reference/cli/development'
import { Route as DocsReferenceCliDeploymentRouteImport } from './routes/_docs/reference/cli/deployment'
import { Route as DocsReferenceCliDebuggingRouteImport } from './routes/_docs/reference/cli/debugging'
import { Route as DocsReferenceCliConfigurationRouteImport } from './routes/_docs/reference/cli/configuration'
import { Route as DocsReferenceCliBuildConfigurationRouteImport } from './routes/_docs/reference/cli/build-configuration'
import { Route as DocsReferenceCliAiCommandsRouteImport } from './routes/_docs/reference/cli/ai-commands'
import { Route as DocsCookbookTutorialsUnderstandingAgentsRouteImport } from './routes/_docs/cookbook/tutorials/understanding-agents'
import { Route as DocsCookbookTutorialsRagAgentRouteImport } from './routes/_docs/cookbook/tutorials/rag-agent'
import { Route as DocsCookbookPatternsWebhookHandlerRouteImport } from './routes/_docs/cookbook/patterns/webhook-handler'
import { Route as DocsCookbookPatternsTailwindSetupRouteImport } from './routes/_docs/cookbook/patterns/tailwind-setup'
import { Route as DocsCookbookPatternsServerUtilitiesRouteImport } from './routes/_docs/cookbook/patterns/server-utilities'
import { Route as DocsCookbookPatternsProductSearchRouteImport } from './routes/_docs/cookbook/patterns/product-search'
import { Route as DocsCookbookPatternsLlmAsAJudgeRouteImport } from './routes/_docs/cookbook/patterns/llm-as-a-judge'
import { Route as DocsCookbookPatternsCronWithStorageRouteImport } from './routes/_docs/cookbook/patterns/cron-with-storage'
import { Route as DocsCookbookPatternsChatWithHistoryRouteImport } from './routes/_docs/cookbook/patterns/chat-with-history'
import { Route as DocsCookbookPatternsBackgroundTasksRouteImport } from './routes/_docs/cookbook/patterns/background-tasks'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDemoIdRoute = DemoDemoIdRouteImport.update({
  id: '/demo/$demoId',
  path: '/demo/$demoId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsServicesIndexRoute = DocsServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsRoutesIndexRoute = DocsRoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReferenceIndexRoute = DocsReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGetStartedIndexRoute = DocsGetStartedIndexRouteImport.update({
  id: '/get-started/',
  path: '/get-started/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFrontendIndexRoute = DocsFrontendIndexRouteImport.update({
  id: '/frontend/',
  path: '/frontend/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsCookbookIndexRoute = DocsCookbookIndexRouteImport.update({
  id: '/cookbook/',
  path: '/cookbook/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsCommunityIndexRoute = DocsCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsApisIndexRoute = DocsApisIndexRouteImport.update({
  id: '/apis/',
  path: '/apis/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsAgentsIndexRoute = DocsAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsServicesQueuesRoute = DocsServicesQueuesRouteImport.update({
  id: '/services/queues',
  path: '/services/queues',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsRoutesWebsocketsRoute = DocsRoutesWebsocketsRouteImport.update({
  id: '/routes/websockets',
  path: '/routes/websockets',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsRoutesSseRoute = DocsRoutesSseRouteImport.update({
  id: '/routes/sse',
  path: '/routes/sse',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsRoutesMiddlewareRoute = DocsRoutesMiddlewareRouteImport.update({
  id: '/routes/middleware',
  path: '/routes/middleware',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsRoutesHttpRoute = DocsRoutesHttpRouteImport.update({
  id: '/routes/http',
  path: '/routes/http',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsRoutesCronRoute = DocsRoutesCronRouteImport.update({
  id: '/routes/cron',
  path: '/routes/cron',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReferenceSdkReferenceRoute =
  DocsReferenceSdkReferenceRouteImport.update({
    id: '/reference/sdk-reference',
    path: '/reference/sdk-reference',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceMigrationGuideRoute =
  DocsReferenceMigrationGuideRouteImport.update({
    id: '/reference/migration-guide',
    path: '/reference/migration-guide',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceMdxFeaturesRoute =
  DocsReferenceMdxFeaturesRouteImport.update({
    id: '/reference/mdx-features',
    path: '/reference/mdx-features',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceGravityNetworkRoute =
  DocsReferenceGravityNetworkRouteImport.update({
    id: '/reference/gravity-network',
    path: '/reference/gravity-network',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGetStartedWhatIsAgentuityRoute =
  DocsGetStartedWhatIsAgentuityRouteImport.update({
    id: '/get-started/what-is-agentuity',
    path: '/get-started/what-is-agentuity',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGetStartedQuickstartRoute =
  DocsGetStartedQuickstartRouteImport.update({
    id: '/get-started/quickstart',
    path: '/get-started/quickstart',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGetStartedProjectStructureRoute =
  DocsGetStartedProjectStructureRouteImport.update({
    id: '/get-started/project-structure',
    path: '/get-started/project-structure',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGetStartedInstallationRoute =
  DocsGetStartedInstallationRouteImport.update({
    id: '/get-started/installation',
    path: '/get-started/installation',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGetStartedAppConfigurationRoute =
  DocsGetStartedAppConfigurationRouteImport.update({
    id: '/get-started/app-configuration',
    path: '/get-started/app-configuration',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsFrontendWorkbenchRoute = DocsFrontendWorkbenchRouteImport.update({
  id: '/frontend/workbench',
  path: '/frontend/workbench',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFrontendRpcClientRoute = DocsFrontendRpcClientRouteImport.update({
  id: '/frontend/rpc-client',
  path: '/frontend/rpc-client',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFrontendReactHooksRoute = DocsFrontendReactHooksRouteImport.update({
  id: '/frontend/react-hooks',
  path: '/frontend/react-hooks',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFrontendProviderSetupRoute =
  DocsFrontendProviderSetupRouteImport.update({
    id: '/frontend/provider-setup',
    path: '/frontend/provider-setup',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsFrontendDeploymentScenariosRoute =
  DocsFrontendDeploymentScenariosRouteImport.update({
    id: '/frontend/deployment-scenarios',
    path: '/frontend/deployment-scenarios',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsFrontendAuthenticationRoute =
  DocsFrontendAuthenticationRouteImport.update({
    id: '/frontend/authentication',
    path: '/frontend/authentication',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsFrontendAdvancedHooksRoute =
  DocsFrontendAdvancedHooksRouteImport.update({
    id: '/frontend/advanced-hooks',
    path: '/frontend/advanced-hooks',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsApisWhenToUseRoute = DocsApisWhenToUseRouteImport.update({
  id: '/apis/when-to-use',
  path: '/apis/when-to-use',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsApisCallingAgentsRoute = DocsApisCallingAgentsRouteImport.update({
  id: '/apis/calling-agents',
  path: '/apis/calling-agents',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsAgentsWorkbenchRoute = DocsAgentsWorkbenchRouteImport.update({
  id: '/agents/workbench',
  path: '/agents/workbench',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsAgentsStreamingResponsesRoute =
  DocsAgentsStreamingResponsesRouteImport.update({
    id: '/agents/streaming-responses',
    path: '/agents/streaming-responses',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsAgentsStateManagementRoute =
  DocsAgentsStateManagementRouteImport.update({
    id: '/agents/state-management',
    path: '/agents/state-management',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsAgentsStandaloneExecutionRoute =
  DocsAgentsStandaloneExecutionRouteImport.update({
    id: '/agents/standalone-execution',
    path: '/agents/standalone-execution',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsAgentsSchemaLibrariesRoute =
  DocsAgentsSchemaLibrariesRouteImport.update({
    id: '/agents/schema-libraries',
    path: '/agents/schema-libraries',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsAgentsEventsLifecycleRoute =
  DocsAgentsEventsLifecycleRouteImport.update({
    id: '/agents/events-lifecycle',
    path: '/agents/events-lifecycle',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsAgentsEvaluationsRoute = DocsAgentsEvaluationsRouteImport.update({
  id: '/agents/evaluations',
  path: '/agents/evaluations',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsAgentsCreatingAgentsRoute =
  DocsAgentsCreatingAgentsRouteImport.update({
    id: '/agents/creating-agents',
    path: '/agents/creating-agents',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsAgentsCallingOtherAgentsRoute =
  DocsAgentsCallingOtherAgentsRouteImport.update({
    id: '/agents/calling-other-agents',
    path: '/agents/calling-other-agents',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsAgentsAiSdkIntegrationRoute =
  DocsAgentsAiSdkIntegrationRouteImport.update({
    id: '/agents/ai-sdk-integration',
    path: '/agents/ai-sdk-integration',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsAgentsAiGatewayRoute = DocsAgentsAiGatewayRouteImport.update({
  id: '/agents/ai-gateway',
  path: '/agents/ai-gateway',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsServicesStorageIndexRoute =
  DocsServicesStorageIndexRouteImport.update({
    id: '/services/storage/',
    path: '/services/storage/',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesSandboxIndexRoute =
  DocsServicesSandboxIndexRouteImport.update({
    id: '/services/sandbox/',
    path: '/services/sandbox/',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesObservabilityIndexRoute =
  DocsServicesObservabilityIndexRouteImport.update({
    id: '/services/observability/',
    path: '/services/observability/',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesDatabaseIndexRoute =
  DocsServicesDatabaseIndexRouteImport.update({
    id: '/services/database/',
    path: '/services/database/',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceCliIndexRoute = DocsReferenceCliIndexRouteImport.update({
  id: '/reference/cli/',
  path: '/reference/cli/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsCookbookTutorialsIndexRoute =
  DocsCookbookTutorialsIndexRouteImport.update({
    id: '/cookbook/tutorials/',
    path: '/cookbook/tutorials/',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookPatternsIndexRoute =
  DocsCookbookPatternsIndexRouteImport.update({
    id: '/cookbook/patterns/',
    path: '/cookbook/patterns/',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesStorageVectorRoute =
  DocsServicesStorageVectorRouteImport.update({
    id: '/services/storage/vector',
    path: '/services/storage/vector',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesStorageObjectRoute =
  DocsServicesStorageObjectRouteImport.update({
    id: '/services/storage/object',
    path: '/services/storage/object',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesStorageKeyValueRoute =
  DocsServicesStorageKeyValueRouteImport.update({
    id: '/services/storage/key-value',
    path: '/services/storage/key-value',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesStorageDurableStreamsRoute =
  DocsServicesStorageDurableStreamsRouteImport.update({
    id: '/services/storage/durable-streams',
    path: '/services/storage/durable-streams',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesStorageDatabaseRoute =
  DocsServicesStorageDatabaseRouteImport.update({
    id: '/services/storage/database',
    path: '/services/storage/database',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesStorageCustomRoute =
  DocsServicesStorageCustomRouteImport.update({
    id: '/services/storage/custom',
    path: '/services/storage/custom',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesSandboxSnapshotsRoute =
  DocsServicesSandboxSnapshotsRouteImport.update({
    id: '/services/sandbox/snapshots',
    path: '/services/sandbox/snapshots',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesSandboxSdkUsageRoute =
  DocsServicesSandboxSdkUsageRouteImport.update({
    id: '/services/sandbox/sdk-usage',
    path: '/services/sandbox/sdk-usage',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesObservabilityTracingRoute =
  DocsServicesObservabilityTracingRouteImport.update({
    id: '/services/observability/tracing',
    path: '/services/observability/tracing',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesObservabilitySessionsDebuggingRoute =
  DocsServicesObservabilitySessionsDebuggingRouteImport.update({
    id: '/services/observability/sessions-debugging',
    path: '/services/observability/sessions-debugging',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesObservabilityLoggingRoute =
  DocsServicesObservabilityLoggingRouteImport.update({
    id: '/services/observability/logging',
    path: '/services/observability/logging',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesDatabasePostgresRoute =
  DocsServicesDatabasePostgresRouteImport.update({
    id: '/services/database/postgres',
    path: '/services/database/postgres',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsServicesDatabaseDrizzleRoute =
  DocsServicesDatabaseDrizzleRouteImport.update({
    id: '/services/database/drizzle',
    path: '/services/database/drizzle',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceCliStorageRoute = DocsReferenceCliStorageRouteImport.update({
  id: '/reference/cli/storage',
  path: '/reference/cli/storage',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReferenceCliSandboxRoute = DocsReferenceCliSandboxRouteImport.update({
  id: '/reference/cli/sandbox',
  path: '/reference/cli/sandbox',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReferenceCliOpencodePluginRoute =
  DocsReferenceCliOpencodePluginRouteImport.update({
    id: '/reference/cli/opencode-plugin',
    path: '/reference/cli/opencode-plugin',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceCliGettingStartedRoute =
  DocsReferenceCliGettingStartedRouteImport.update({
    id: '/reference/cli/getting-started',
    path: '/reference/cli/getting-started',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceCliDevelopmentRoute =
  DocsReferenceCliDevelopmentRouteImport.update({
    id: '/reference/cli/development',
    path: '/reference/cli/development',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceCliDeploymentRoute =
  DocsReferenceCliDeploymentRouteImport.update({
    id: '/reference/cli/deployment',
    path: '/reference/cli/deployment',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceCliDebuggingRoute =
  DocsReferenceCliDebuggingRouteImport.update({
    id: '/reference/cli/debugging',
    path: '/reference/cli/debugging',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceCliConfigurationRoute =
  DocsReferenceCliConfigurationRouteImport.update({
    id: '/reference/cli/configuration',
    path: '/reference/cli/configuration',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceCliBuildConfigurationRoute =
  DocsReferenceCliBuildConfigurationRouteImport.update({
    id: '/reference/cli/build-configuration',
    path: '/reference/cli/build-configuration',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsReferenceCliAiCommandsRoute =
  DocsReferenceCliAiCommandsRouteImport.update({
    id: '/reference/cli/ai-commands',
    path: '/reference/cli/ai-commands',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookTutorialsUnderstandingAgentsRoute =
  DocsCookbookTutorialsUnderstandingAgentsRouteImport.update({
    id: '/cookbook/tutorials/understanding-agents',
    path: '/cookbook/tutorials/understanding-agents',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookTutorialsRagAgentRoute =
  DocsCookbookTutorialsRagAgentRouteImport.update({
    id: '/cookbook/tutorials/rag-agent',
    path: '/cookbook/tutorials/rag-agent',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookPatternsWebhookHandlerRoute =
  DocsCookbookPatternsWebhookHandlerRouteImport.update({
    id: '/cookbook/patterns/webhook-handler',
    path: '/cookbook/patterns/webhook-handler',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookPatternsTailwindSetupRoute =
  DocsCookbookPatternsTailwindSetupRouteImport.update({
    id: '/cookbook/patterns/tailwind-setup',
    path: '/cookbook/patterns/tailwind-setup',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookPatternsServerUtilitiesRoute =
  DocsCookbookPatternsServerUtilitiesRouteImport.update({
    id: '/cookbook/patterns/server-utilities',
    path: '/cookbook/patterns/server-utilities',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookPatternsProductSearchRoute =
  DocsCookbookPatternsProductSearchRouteImport.update({
    id: '/cookbook/patterns/product-search',
    path: '/cookbook/patterns/product-search',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookPatternsLlmAsAJudgeRoute =
  DocsCookbookPatternsLlmAsAJudgeRouteImport.update({
    id: '/cookbook/patterns/llm-as-a-judge',
    path: '/cookbook/patterns/llm-as-a-judge',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookPatternsCronWithStorageRoute =
  DocsCookbookPatternsCronWithStorageRouteImport.update({
    id: '/cookbook/patterns/cron-with-storage',
    path: '/cookbook/patterns/cron-with-storage',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookPatternsChatWithHistoryRoute =
  DocsCookbookPatternsChatWithHistoryRouteImport.update({
    id: '/cookbook/patterns/chat-with-history',
    path: '/cookbook/patterns/chat-with-history',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsCookbookPatternsBackgroundTasksRoute =
  DocsCookbookPatternsBackgroundTasksRouteImport.update({
    id: '/cookbook/patterns/background-tasks',
    path: '/cookbook/patterns/background-tasks',
    getParentRoute: () => DocsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/$demoId': typeof DemoDemoIdRoute
  '/agents/ai-gateway': typeof DocsAgentsAiGatewayRoute
  '/agents/ai-sdk-integration': typeof DocsAgentsAiSdkIntegrationRoute
  '/agents/calling-other-agents': typeof DocsAgentsCallingOtherAgentsRoute
  '/agents/creating-agents': typeof DocsAgentsCreatingAgentsRoute
  '/agents/evaluations': typeof DocsAgentsEvaluationsRoute
  '/agents/events-lifecycle': typeof DocsAgentsEventsLifecycleRoute
  '/agents/schema-libraries': typeof DocsAgentsSchemaLibrariesRoute
  '/agents/standalone-execution': typeof DocsAgentsStandaloneExecutionRoute
  '/agents/state-management': typeof DocsAgentsStateManagementRoute
  '/agents/streaming-responses': typeof DocsAgentsStreamingResponsesRoute
  '/agents/workbench': typeof DocsAgentsWorkbenchRoute
  '/apis/calling-agents': typeof DocsApisCallingAgentsRoute
  '/apis/when-to-use': typeof DocsApisWhenToUseRoute
  '/frontend/advanced-hooks': typeof DocsFrontendAdvancedHooksRoute
  '/frontend/authentication': typeof DocsFrontendAuthenticationRoute
  '/frontend/deployment-scenarios': typeof DocsFrontendDeploymentScenariosRoute
  '/frontend/provider-setup': typeof DocsFrontendProviderSetupRoute
  '/frontend/react-hooks': typeof DocsFrontendReactHooksRoute
  '/frontend/rpc-client': typeof DocsFrontendRpcClientRoute
  '/frontend/workbench': typeof DocsFrontendWorkbenchRoute
  '/get-started/app-configuration': typeof DocsGetStartedAppConfigurationRoute
  '/get-started/installation': typeof DocsGetStartedInstallationRoute
  '/get-started/project-structure': typeof DocsGetStartedProjectStructureRoute
  '/get-started/quickstart': typeof DocsGetStartedQuickstartRoute
  '/get-started/what-is-agentuity': typeof DocsGetStartedWhatIsAgentuityRoute
  '/reference/gravity-network': typeof DocsReferenceGravityNetworkRoute
  '/reference/mdx-features': typeof DocsReferenceMdxFeaturesRoute
  '/reference/migration-guide': typeof DocsReferenceMigrationGuideRoute
  '/reference/sdk-reference': typeof DocsReferenceSdkReferenceRoute
  '/routes/cron': typeof DocsRoutesCronRoute
  '/routes/http': typeof DocsRoutesHttpRoute
  '/routes/middleware': typeof DocsRoutesMiddlewareRoute
  '/routes/sse': typeof DocsRoutesSseRoute
  '/routes/websockets': typeof DocsRoutesWebsocketsRoute
  '/services/queues': typeof DocsServicesQueuesRoute
  '/agents/': typeof DocsAgentsIndexRoute
  '/apis/': typeof DocsApisIndexRoute
  '/community/': typeof DocsCommunityIndexRoute
  '/cookbook/': typeof DocsCookbookIndexRoute
  '/frontend/': typeof DocsFrontendIndexRoute
  '/get-started/': typeof DocsGetStartedIndexRoute
  '/reference/': typeof DocsReferenceIndexRoute
  '/routes/': typeof DocsRoutesIndexRoute
  '/services/': typeof DocsServicesIndexRoute
  '/cookbook/patterns/background-tasks': typeof DocsCookbookPatternsBackgroundTasksRoute
  '/cookbook/patterns/chat-with-history': typeof DocsCookbookPatternsChatWithHistoryRoute
  '/cookbook/patterns/cron-with-storage': typeof DocsCookbookPatternsCronWithStorageRoute
  '/cookbook/patterns/llm-as-a-judge': typeof DocsCookbookPatternsLlmAsAJudgeRoute
  '/cookbook/patterns/product-search': typeof DocsCookbookPatternsProductSearchRoute
  '/cookbook/patterns/server-utilities': typeof DocsCookbookPatternsServerUtilitiesRoute
  '/cookbook/patterns/tailwind-setup': typeof DocsCookbookPatternsTailwindSetupRoute
  '/cookbook/patterns/webhook-handler': typeof DocsCookbookPatternsWebhookHandlerRoute
  '/cookbook/tutorials/rag-agent': typeof DocsCookbookTutorialsRagAgentRoute
  '/cookbook/tutorials/understanding-agents': typeof DocsCookbookTutorialsUnderstandingAgentsRoute
  '/reference/cli/ai-commands': typeof DocsReferenceCliAiCommandsRoute
  '/reference/cli/build-configuration': typeof DocsReferenceCliBuildConfigurationRoute
  '/reference/cli/configuration': typeof DocsReferenceCliConfigurationRoute
  '/reference/cli/debugging': typeof DocsReferenceCliDebuggingRoute
  '/reference/cli/deployment': typeof DocsReferenceCliDeploymentRoute
  '/reference/cli/development': typeof DocsReferenceCliDevelopmentRoute
  '/reference/cli/getting-started': typeof DocsReferenceCliGettingStartedRoute
  '/reference/cli/opencode-plugin': typeof DocsReferenceCliOpencodePluginRoute
  '/reference/cli/sandbox': typeof DocsReferenceCliSandboxRoute
  '/reference/cli/storage': typeof DocsReferenceCliStorageRoute
  '/services/database/drizzle': typeof DocsServicesDatabaseDrizzleRoute
  '/services/database/postgres': typeof DocsServicesDatabasePostgresRoute
  '/services/observability/logging': typeof DocsServicesObservabilityLoggingRoute
  '/services/observability/sessions-debugging': typeof DocsServicesObservabilitySessionsDebuggingRoute
  '/services/observability/tracing': typeof DocsServicesObservabilityTracingRoute
  '/services/sandbox/sdk-usage': typeof DocsServicesSandboxSdkUsageRoute
  '/services/sandbox/snapshots': typeof DocsServicesSandboxSnapshotsRoute
  '/services/storage/custom': typeof DocsServicesStorageCustomRoute
  '/services/storage/database': typeof DocsServicesStorageDatabaseRoute
  '/services/storage/durable-streams': typeof DocsServicesStorageDurableStreamsRoute
  '/services/storage/key-value': typeof DocsServicesStorageKeyValueRoute
  '/services/storage/object': typeof DocsServicesStorageObjectRoute
  '/services/storage/vector': typeof DocsServicesStorageVectorRoute
  '/cookbook/patterns/': typeof DocsCookbookPatternsIndexRoute
  '/cookbook/tutorials/': typeof DocsCookbookTutorialsIndexRoute
  '/reference/cli/': typeof DocsReferenceCliIndexRoute
  '/services/database/': typeof DocsServicesDatabaseIndexRoute
  '/services/observability/': typeof DocsServicesObservabilityIndexRoute
  '/services/sandbox/': typeof DocsServicesSandboxIndexRoute
  '/services/storage/': typeof DocsServicesStorageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/$demoId': typeof DemoDemoIdRoute
  '/agents/ai-gateway': typeof DocsAgentsAiGatewayRoute
  '/agents/ai-sdk-integration': typeof DocsAgentsAiSdkIntegrationRoute
  '/agents/calling-other-agents': typeof DocsAgentsCallingOtherAgentsRoute
  '/agents/creating-agents': typeof DocsAgentsCreatingAgentsRoute
  '/agents/evaluations': typeof DocsAgentsEvaluationsRoute
  '/agents/events-lifecycle': typeof DocsAgentsEventsLifecycleRoute
  '/agents/schema-libraries': typeof DocsAgentsSchemaLibrariesRoute
  '/agents/standalone-execution': typeof DocsAgentsStandaloneExecutionRoute
  '/agents/state-management': typeof DocsAgentsStateManagementRoute
  '/agents/streaming-responses': typeof DocsAgentsStreamingResponsesRoute
  '/agents/workbench': typeof DocsAgentsWorkbenchRoute
  '/apis/calling-agents': typeof DocsApisCallingAgentsRoute
  '/apis/when-to-use': typeof DocsApisWhenToUseRoute
  '/frontend/advanced-hooks': typeof DocsFrontendAdvancedHooksRoute
  '/frontend/authentication': typeof DocsFrontendAuthenticationRoute
  '/frontend/deployment-scenarios': typeof DocsFrontendDeploymentScenariosRoute
  '/frontend/provider-setup': typeof DocsFrontendProviderSetupRoute
  '/frontend/react-hooks': typeof DocsFrontendReactHooksRoute
  '/frontend/rpc-client': typeof DocsFrontendRpcClientRoute
  '/frontend/workbench': typeof DocsFrontendWorkbenchRoute
  '/get-started/app-configuration': typeof DocsGetStartedAppConfigurationRoute
  '/get-started/installation': typeof DocsGetStartedInstallationRoute
  '/get-started/project-structure': typeof DocsGetStartedProjectStructureRoute
  '/get-started/quickstart': typeof DocsGetStartedQuickstartRoute
  '/get-started/what-is-agentuity': typeof DocsGetStartedWhatIsAgentuityRoute
  '/reference/gravity-network': typeof DocsReferenceGravityNetworkRoute
  '/reference/mdx-features': typeof DocsReferenceMdxFeaturesRoute
  '/reference/migration-guide': typeof DocsReferenceMigrationGuideRoute
  '/reference/sdk-reference': typeof DocsReferenceSdkReferenceRoute
  '/routes/cron': typeof DocsRoutesCronRoute
  '/routes/http': typeof DocsRoutesHttpRoute
  '/routes/middleware': typeof DocsRoutesMiddlewareRoute
  '/routes/sse': typeof DocsRoutesSseRoute
  '/routes/websockets': typeof DocsRoutesWebsocketsRoute
  '/services/queues': typeof DocsServicesQueuesRoute
  '/agents': typeof DocsAgentsIndexRoute
  '/apis': typeof DocsApisIndexRoute
  '/community': typeof DocsCommunityIndexRoute
  '/cookbook': typeof DocsCookbookIndexRoute
  '/frontend': typeof DocsFrontendIndexRoute
  '/get-started': typeof DocsGetStartedIndexRoute
  '/reference': typeof DocsReferenceIndexRoute
  '/routes': typeof DocsRoutesIndexRoute
  '/services': typeof DocsServicesIndexRoute
  '/cookbook/patterns/background-tasks': typeof DocsCookbookPatternsBackgroundTasksRoute
  '/cookbook/patterns/chat-with-history': typeof DocsCookbookPatternsChatWithHistoryRoute
  '/cookbook/patterns/cron-with-storage': typeof DocsCookbookPatternsCronWithStorageRoute
  '/cookbook/patterns/llm-as-a-judge': typeof DocsCookbookPatternsLlmAsAJudgeRoute
  '/cookbook/patterns/product-search': typeof DocsCookbookPatternsProductSearchRoute
  '/cookbook/patterns/server-utilities': typeof DocsCookbookPatternsServerUtilitiesRoute
  '/cookbook/patterns/tailwind-setup': typeof DocsCookbookPatternsTailwindSetupRoute
  '/cookbook/patterns/webhook-handler': typeof DocsCookbookPatternsWebhookHandlerRoute
  '/cookbook/tutorials/rag-agent': typeof DocsCookbookTutorialsRagAgentRoute
  '/cookbook/tutorials/understanding-agents': typeof DocsCookbookTutorialsUnderstandingAgentsRoute
  '/reference/cli/ai-commands': typeof DocsReferenceCliAiCommandsRoute
  '/reference/cli/build-configuration': typeof DocsReferenceCliBuildConfigurationRoute
  '/reference/cli/configuration': typeof DocsReferenceCliConfigurationRoute
  '/reference/cli/debugging': typeof DocsReferenceCliDebuggingRoute
  '/reference/cli/deployment': typeof DocsReferenceCliDeploymentRoute
  '/reference/cli/development': typeof DocsReferenceCliDevelopmentRoute
  '/reference/cli/getting-started': typeof DocsReferenceCliGettingStartedRoute
  '/reference/cli/opencode-plugin': typeof DocsReferenceCliOpencodePluginRoute
  '/reference/cli/sandbox': typeof DocsReferenceCliSandboxRoute
  '/reference/cli/storage': typeof DocsReferenceCliStorageRoute
  '/services/database/drizzle': typeof DocsServicesDatabaseDrizzleRoute
  '/services/database/postgres': typeof DocsServicesDatabasePostgresRoute
  '/services/observability/logging': typeof DocsServicesObservabilityLoggingRoute
  '/services/observability/sessions-debugging': typeof DocsServicesObservabilitySessionsDebuggingRoute
  '/services/observability/tracing': typeof DocsServicesObservabilityTracingRoute
  '/services/sandbox/sdk-usage': typeof DocsServicesSandboxSdkUsageRoute
  '/services/sandbox/snapshots': typeof DocsServicesSandboxSnapshotsRoute
  '/services/storage/custom': typeof DocsServicesStorageCustomRoute
  '/services/storage/database': typeof DocsServicesStorageDatabaseRoute
  '/services/storage/durable-streams': typeof DocsServicesStorageDurableStreamsRoute
  '/services/storage/key-value': typeof DocsServicesStorageKeyValueRoute
  '/services/storage/object': typeof DocsServicesStorageObjectRoute
  '/services/storage/vector': typeof DocsServicesStorageVectorRoute
  '/cookbook/patterns': typeof DocsCookbookPatternsIndexRoute
  '/cookbook/tutorials': typeof DocsCookbookTutorialsIndexRoute
  '/reference/cli': typeof DocsReferenceCliIndexRoute
  '/services/database': typeof DocsServicesDatabaseIndexRoute
  '/services/observability': typeof DocsServicesObservabilityIndexRoute
  '/services/sandbox': typeof DocsServicesSandboxIndexRoute
  '/services/storage': typeof DocsServicesStorageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_docs': typeof DocsRouteRouteWithChildren
  '/demo/$demoId': typeof DemoDemoIdRoute
  '/_docs/agents/ai-gateway': typeof DocsAgentsAiGatewayRoute
  '/_docs/agents/ai-sdk-integration': typeof DocsAgentsAiSdkIntegrationRoute
  '/_docs/agents/calling-other-agents': typeof DocsAgentsCallingOtherAgentsRoute
  '/_docs/agents/creating-agents': typeof DocsAgentsCreatingAgentsRoute
  '/_docs/agents/evaluations': typeof DocsAgentsEvaluationsRoute
  '/_docs/agents/events-lifecycle': typeof DocsAgentsEventsLifecycleRoute
  '/_docs/agents/schema-libraries': typeof DocsAgentsSchemaLibrariesRoute
  '/_docs/agents/standalone-execution': typeof DocsAgentsStandaloneExecutionRoute
  '/_docs/agents/state-management': typeof DocsAgentsStateManagementRoute
  '/_docs/agents/streaming-responses': typeof DocsAgentsStreamingResponsesRoute
  '/_docs/agents/workbench': typeof DocsAgentsWorkbenchRoute
  '/_docs/apis/calling-agents': typeof DocsApisCallingAgentsRoute
  '/_docs/apis/when-to-use': typeof DocsApisWhenToUseRoute
  '/_docs/frontend/advanced-hooks': typeof DocsFrontendAdvancedHooksRoute
  '/_docs/frontend/authentication': typeof DocsFrontendAuthenticationRoute
  '/_docs/frontend/deployment-scenarios': typeof DocsFrontendDeploymentScenariosRoute
  '/_docs/frontend/provider-setup': typeof DocsFrontendProviderSetupRoute
  '/_docs/frontend/react-hooks': typeof DocsFrontendReactHooksRoute
  '/_docs/frontend/rpc-client': typeof DocsFrontendRpcClientRoute
  '/_docs/frontend/workbench': typeof DocsFrontendWorkbenchRoute
  '/_docs/get-started/app-configuration': typeof DocsGetStartedAppConfigurationRoute
  '/_docs/get-started/installation': typeof DocsGetStartedInstallationRoute
  '/_docs/get-started/project-structure': typeof DocsGetStartedProjectStructureRoute
  '/_docs/get-started/quickstart': typeof DocsGetStartedQuickstartRoute
  '/_docs/get-started/what-is-agentuity': typeof DocsGetStartedWhatIsAgentuityRoute
  '/_docs/reference/gravity-network': typeof DocsReferenceGravityNetworkRoute
  '/_docs/reference/mdx-features': typeof DocsReferenceMdxFeaturesRoute
  '/_docs/reference/migration-guide': typeof DocsReferenceMigrationGuideRoute
  '/_docs/reference/sdk-reference': typeof DocsReferenceSdkReferenceRoute
  '/_docs/routes/cron': typeof DocsRoutesCronRoute
  '/_docs/routes/http': typeof DocsRoutesHttpRoute
  '/_docs/routes/middleware': typeof DocsRoutesMiddlewareRoute
  '/_docs/routes/sse': typeof DocsRoutesSseRoute
  '/_docs/routes/websockets': typeof DocsRoutesWebsocketsRoute
  '/_docs/services/queues': typeof DocsServicesQueuesRoute
  '/_docs/agents/': typeof DocsAgentsIndexRoute
  '/_docs/apis/': typeof DocsApisIndexRoute
  '/_docs/community/': typeof DocsCommunityIndexRoute
  '/_docs/cookbook/': typeof DocsCookbookIndexRoute
  '/_docs/frontend/': typeof DocsFrontendIndexRoute
  '/_docs/get-started/': typeof DocsGetStartedIndexRoute
  '/_docs/reference/': typeof DocsReferenceIndexRoute
  '/_docs/routes/': typeof DocsRoutesIndexRoute
  '/_docs/services/': typeof DocsServicesIndexRoute
  '/_docs/cookbook/patterns/background-tasks': typeof DocsCookbookPatternsBackgroundTasksRoute
  '/_docs/cookbook/patterns/chat-with-history': typeof DocsCookbookPatternsChatWithHistoryRoute
  '/_docs/cookbook/patterns/cron-with-storage': typeof DocsCookbookPatternsCronWithStorageRoute
  '/_docs/cookbook/patterns/llm-as-a-judge': typeof DocsCookbookPatternsLlmAsAJudgeRoute
  '/_docs/cookbook/patterns/product-search': typeof DocsCookbookPatternsProductSearchRoute
  '/_docs/cookbook/patterns/server-utilities': typeof DocsCookbookPatternsServerUtilitiesRoute
  '/_docs/cookbook/patterns/tailwind-setup': typeof DocsCookbookPatternsTailwindSetupRoute
  '/_docs/cookbook/patterns/webhook-handler': typeof DocsCookbookPatternsWebhookHandlerRoute
  '/_docs/cookbook/tutorials/rag-agent': typeof DocsCookbookTutorialsRagAgentRoute
  '/_docs/cookbook/tutorials/understanding-agents': typeof DocsCookbookTutorialsUnderstandingAgentsRoute
  '/_docs/reference/cli/ai-commands': typeof DocsReferenceCliAiCommandsRoute
  '/_docs/reference/cli/build-configuration': typeof DocsReferenceCliBuildConfigurationRoute
  '/_docs/reference/cli/configuration': typeof DocsReferenceCliConfigurationRoute
  '/_docs/reference/cli/debugging': typeof DocsReferenceCliDebuggingRoute
  '/_docs/reference/cli/deployment': typeof DocsReferenceCliDeploymentRoute
  '/_docs/reference/cli/development': typeof DocsReferenceCliDevelopmentRoute
  '/_docs/reference/cli/getting-started': typeof DocsReferenceCliGettingStartedRoute
  '/_docs/reference/cli/opencode-plugin': typeof DocsReferenceCliOpencodePluginRoute
  '/_docs/reference/cli/sandbox': typeof DocsReferenceCliSandboxRoute
  '/_docs/reference/cli/storage': typeof DocsReferenceCliStorageRoute
  '/_docs/services/database/drizzle': typeof DocsServicesDatabaseDrizzleRoute
  '/_docs/services/database/postgres': typeof DocsServicesDatabasePostgresRoute
  '/_docs/services/observability/logging': typeof DocsServicesObservabilityLoggingRoute
  '/_docs/services/observability/sessions-debugging': typeof DocsServicesObservabilitySessionsDebuggingRoute
  '/_docs/services/observability/tracing': typeof DocsServicesObservabilityTracingRoute
  '/_docs/services/sandbox/sdk-usage': typeof DocsServicesSandboxSdkUsageRoute
  '/_docs/services/sandbox/snapshots': typeof DocsServicesSandboxSnapshotsRoute
  '/_docs/services/storage/custom': typeof DocsServicesStorageCustomRoute
  '/_docs/services/storage/database': typeof DocsServicesStorageDatabaseRoute
  '/_docs/services/storage/durable-streams': typeof DocsServicesStorageDurableStreamsRoute
  '/_docs/services/storage/key-value': typeof DocsServicesStorageKeyValueRoute
  '/_docs/services/storage/object': typeof DocsServicesStorageObjectRoute
  '/_docs/services/storage/vector': typeof DocsServicesStorageVectorRoute
  '/_docs/cookbook/patterns/': typeof DocsCookbookPatternsIndexRoute
  '/_docs/cookbook/tutorials/': typeof DocsCookbookTutorialsIndexRoute
  '/_docs/reference/cli/': typeof DocsReferenceCliIndexRoute
  '/_docs/services/database/': typeof DocsServicesDatabaseIndexRoute
  '/_docs/services/observability/': typeof DocsServicesObservabilityIndexRoute
  '/_docs/services/sandbox/': typeof DocsServicesSandboxIndexRoute
  '/_docs/services/storage/': typeof DocsServicesStorageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/$demoId'
    | '/agents/ai-gateway'
    | '/agents/ai-sdk-integration'
    | '/agents/calling-other-agents'
    | '/agents/creating-agents'
    | '/agents/evaluations'
    | '/agents/events-lifecycle'
    | '/agents/schema-libraries'
    | '/agents/standalone-execution'
    | '/agents/state-management'
    | '/agents/streaming-responses'
    | '/agents/workbench'
    | '/apis/calling-agents'
    | '/apis/when-to-use'
    | '/frontend/advanced-hooks'
    | '/frontend/authentication'
    | '/frontend/deployment-scenarios'
    | '/frontend/provider-setup'
    | '/frontend/react-hooks'
    | '/frontend/rpc-client'
    | '/frontend/workbench'
    | '/get-started/app-configuration'
    | '/get-started/installation'
    | '/get-started/project-structure'
    | '/get-started/quickstart'
    | '/get-started/what-is-agentuity'
    | '/reference/gravity-network'
    | '/reference/mdx-features'
    | '/reference/migration-guide'
    | '/reference/sdk-reference'
    | '/routes/cron'
    | '/routes/http'
    | '/routes/middleware'
    | '/routes/sse'
    | '/routes/websockets'
    | '/services/queues'
    | '/agents/'
    | '/apis/'
    | '/community/'
    | '/cookbook/'
    | '/frontend/'
    | '/get-started/'
    | '/reference/'
    | '/routes/'
    | '/services/'
    | '/cookbook/patterns/background-tasks'
    | '/cookbook/patterns/chat-with-history'
    | '/cookbook/patterns/cron-with-storage'
    | '/cookbook/patterns/llm-as-a-judge'
    | '/cookbook/patterns/product-search'
    | '/cookbook/patterns/server-utilities'
    | '/cookbook/patterns/tailwind-setup'
    | '/cookbook/patterns/webhook-handler'
    | '/cookbook/tutorials/rag-agent'
    | '/cookbook/tutorials/understanding-agents'
    | '/reference/cli/ai-commands'
    | '/reference/cli/build-configuration'
    | '/reference/cli/configuration'
    | '/reference/cli/debugging'
    | '/reference/cli/deployment'
    | '/reference/cli/development'
    | '/reference/cli/getting-started'
    | '/reference/cli/opencode-plugin'
    | '/reference/cli/sandbox'
    | '/reference/cli/storage'
    | '/services/database/drizzle'
    | '/services/database/postgres'
    | '/services/observability/logging'
    | '/services/observability/sessions-debugging'
    | '/services/observability/tracing'
    | '/services/sandbox/sdk-usage'
    | '/services/sandbox/snapshots'
    | '/services/storage/custom'
    | '/services/storage/database'
    | '/services/storage/durable-streams'
    | '/services/storage/key-value'
    | '/services/storage/object'
    | '/services/storage/vector'
    | '/cookbook/patterns/'
    | '/cookbook/tutorials/'
    | '/reference/cli/'
    | '/services/database/'
    | '/services/observability/'
    | '/services/sandbox/'
    | '/services/storage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/$demoId'
    | '/agents/ai-gateway'
    | '/agents/ai-sdk-integration'
    | '/agents/calling-other-agents'
    | '/agents/creating-agents'
    | '/agents/evaluations'
    | '/agents/events-lifecycle'
    | '/agents/schema-libraries'
    | '/agents/standalone-execution'
    | '/agents/state-management'
    | '/agents/streaming-responses'
    | '/agents/workbench'
    | '/apis/calling-agents'
    | '/apis/when-to-use'
    | '/frontend/advanced-hooks'
    | '/frontend/authentication'
    | '/frontend/deployment-scenarios'
    | '/frontend/provider-setup'
    | '/frontend/react-hooks'
    | '/frontend/rpc-client'
    | '/frontend/workbench'
    | '/get-started/app-configuration'
    | '/get-started/installation'
    | '/get-started/project-structure'
    | '/get-started/quickstart'
    | '/get-started/what-is-agentuity'
    | '/reference/gravity-network'
    | '/reference/mdx-features'
    | '/reference/migration-guide'
    | '/reference/sdk-reference'
    | '/routes/cron'
    | '/routes/http'
    | '/routes/middleware'
    | '/routes/sse'
    | '/routes/websockets'
    | '/services/queues'
    | '/agents'
    | '/apis'
    | '/community'
    | '/cookbook'
    | '/frontend'
    | '/get-started'
    | '/reference'
    | '/routes'
    | '/services'
    | '/cookbook/patterns/background-tasks'
    | '/cookbook/patterns/chat-with-history'
    | '/cookbook/patterns/cron-with-storage'
    | '/cookbook/patterns/llm-as-a-judge'
    | '/cookbook/patterns/product-search'
    | '/cookbook/patterns/server-utilities'
    | '/cookbook/patterns/tailwind-setup'
    | '/cookbook/patterns/webhook-handler'
    | '/cookbook/tutorials/rag-agent'
    | '/cookbook/tutorials/understanding-agents'
    | '/reference/cli/ai-commands'
    | '/reference/cli/build-configuration'
    | '/reference/cli/configuration'
    | '/reference/cli/debugging'
    | '/reference/cli/deployment'
    | '/reference/cli/development'
    | '/reference/cli/getting-started'
    | '/reference/cli/opencode-plugin'
    | '/reference/cli/sandbox'
    | '/reference/cli/storage'
    | '/services/database/drizzle'
    | '/services/database/postgres'
    | '/services/observability/logging'
    | '/services/observability/sessions-debugging'
    | '/services/observability/tracing'
    | '/services/sandbox/sdk-usage'
    | '/services/sandbox/snapshots'
    | '/services/storage/custom'
    | '/services/storage/database'
    | '/services/storage/durable-streams'
    | '/services/storage/key-value'
    | '/services/storage/object'
    | '/services/storage/vector'
    | '/cookbook/patterns'
    | '/cookbook/tutorials'
    | '/reference/cli'
    | '/services/database'
    | '/services/observability'
    | '/services/sandbox'
    | '/services/storage'
  id:
    | '__root__'
    | '/'
    | '/_docs'
    | '/demo/$demoId'
    | '/_docs/agents/ai-gateway'
    | '/_docs/agents/ai-sdk-integration'
    | '/_docs/agents/calling-other-agents'
    | '/_docs/agents/creating-agents'
    | '/_docs/agents/evaluations'
    | '/_docs/agents/events-lifecycle'
    | '/_docs/agents/schema-libraries'
    | '/_docs/agents/standalone-execution'
    | '/_docs/agents/state-management'
    | '/_docs/agents/streaming-responses'
    | '/_docs/agents/workbench'
    | '/_docs/apis/calling-agents'
    | '/_docs/apis/when-to-use'
    | '/_docs/frontend/advanced-hooks'
    | '/_docs/frontend/authentication'
    | '/_docs/frontend/deployment-scenarios'
    | '/_docs/frontend/provider-setup'
    | '/_docs/frontend/react-hooks'
    | '/_docs/frontend/rpc-client'
    | '/_docs/frontend/workbench'
    | '/_docs/get-started/app-configuration'
    | '/_docs/get-started/installation'
    | '/_docs/get-started/project-structure'
    | '/_docs/get-started/quickstart'
    | '/_docs/get-started/what-is-agentuity'
    | '/_docs/reference/gravity-network'
    | '/_docs/reference/mdx-features'
    | '/_docs/reference/migration-guide'
    | '/_docs/reference/sdk-reference'
    | '/_docs/routes/cron'
    | '/_docs/routes/http'
    | '/_docs/routes/middleware'
    | '/_docs/routes/sse'
    | '/_docs/routes/websockets'
    | '/_docs/services/queues'
    | '/_docs/agents/'
    | '/_docs/apis/'
    | '/_docs/community/'
    | '/_docs/cookbook/'
    | '/_docs/frontend/'
    | '/_docs/get-started/'
    | '/_docs/reference/'
    | '/_docs/routes/'
    | '/_docs/services/'
    | '/_docs/cookbook/patterns/background-tasks'
    | '/_docs/cookbook/patterns/chat-with-history'
    | '/_docs/cookbook/patterns/cron-with-storage'
    | '/_docs/cookbook/patterns/llm-as-a-judge'
    | '/_docs/cookbook/patterns/product-search'
    | '/_docs/cookbook/patterns/server-utilities'
    | '/_docs/cookbook/patterns/tailwind-setup'
    | '/_docs/cookbook/patterns/webhook-handler'
    | '/_docs/cookbook/tutorials/rag-agent'
    | '/_docs/cookbook/tutorials/understanding-agents'
    | '/_docs/reference/cli/ai-commands'
    | '/_docs/reference/cli/build-configuration'
    | '/_docs/reference/cli/configuration'
    | '/_docs/reference/cli/debugging'
    | '/_docs/reference/cli/deployment'
    | '/_docs/reference/cli/development'
    | '/_docs/reference/cli/getting-started'
    | '/_docs/reference/cli/opencode-plugin'
    | '/_docs/reference/cli/sandbox'
    | '/_docs/reference/cli/storage'
    | '/_docs/services/database/drizzle'
    | '/_docs/services/database/postgres'
    | '/_docs/services/observability/logging'
    | '/_docs/services/observability/sessions-debugging'
    | '/_docs/services/observability/tracing'
    | '/_docs/services/sandbox/sdk-usage'
    | '/_docs/services/sandbox/snapshots'
    | '/_docs/services/storage/custom'
    | '/_docs/services/storage/database'
    | '/_docs/services/storage/durable-streams'
    | '/_docs/services/storage/key-value'
    | '/_docs/services/storage/object'
    | '/_docs/services/storage/vector'
    | '/_docs/cookbook/patterns/'
    | '/_docs/cookbook/tutorials/'
    | '/_docs/reference/cli/'
    | '/_docs/services/database/'
    | '/_docs/services/observability/'
    | '/_docs/services/sandbox/'
    | '/_docs/services/storage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  DemoDemoIdRoute: typeof DemoDemoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$demoId': {
      id: '/demo/$demoId'
      path: '/demo/$demoId'
      fullPath: '/demo/$demoId'
      preLoaderRoute: typeof DemoDemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/services/': {
      id: '/_docs/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof DocsServicesIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/routes/': {
      id: '/_docs/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof DocsRoutesIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/': {
      id: '/_docs/reference/'
      path: '/reference'
      fullPath: '/reference/'
      preLoaderRoute: typeof DocsReferenceIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/get-started/': {
      id: '/_docs/get-started/'
      path: '/get-started'
      fullPath: '/get-started/'
      preLoaderRoute: typeof DocsGetStartedIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/frontend/': {
      id: '/_docs/frontend/'
      path: '/frontend'
      fullPath: '/frontend/'
      preLoaderRoute: typeof DocsFrontendIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/': {
      id: '/_docs/cookbook/'
      path: '/cookbook'
      fullPath: '/cookbook/'
      preLoaderRoute: typeof DocsCookbookIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/community/': {
      id: '/_docs/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof DocsCommunityIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/apis/': {
      id: '/_docs/apis/'
      path: '/apis'
      fullPath: '/apis/'
      preLoaderRoute: typeof DocsApisIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/': {
      id: '/_docs/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof DocsAgentsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/queues': {
      id: '/_docs/services/queues'
      path: '/services/queues'
      fullPath: '/services/queues'
      preLoaderRoute: typeof DocsServicesQueuesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/routes/websockets': {
      id: '/_docs/routes/websockets'
      path: '/routes/websockets'
      fullPath: '/routes/websockets'
      preLoaderRoute: typeof DocsRoutesWebsocketsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/routes/sse': {
      id: '/_docs/routes/sse'
      path: '/routes/sse'
      fullPath: '/routes/sse'
      preLoaderRoute: typeof DocsRoutesSseRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/routes/middleware': {
      id: '/_docs/routes/middleware'
      path: '/routes/middleware'
      fullPath: '/routes/middleware'
      preLoaderRoute: typeof DocsRoutesMiddlewareRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/routes/http': {
      id: '/_docs/routes/http'
      path: '/routes/http'
      fullPath: '/routes/http'
      preLoaderRoute: typeof DocsRoutesHttpRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/routes/cron': {
      id: '/_docs/routes/cron'
      path: '/routes/cron'
      fullPath: '/routes/cron'
      preLoaderRoute: typeof DocsRoutesCronRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/sdk-reference': {
      id: '/_docs/reference/sdk-reference'
      path: '/reference/sdk-reference'
      fullPath: '/reference/sdk-reference'
      preLoaderRoute: typeof DocsReferenceSdkReferenceRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/migration-guide': {
      id: '/_docs/reference/migration-guide'
      path: '/reference/migration-guide'
      fullPath: '/reference/migration-guide'
      preLoaderRoute: typeof DocsReferenceMigrationGuideRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/mdx-features': {
      id: '/_docs/reference/mdx-features'
      path: '/reference/mdx-features'
      fullPath: '/reference/mdx-features'
      preLoaderRoute: typeof DocsReferenceMdxFeaturesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/gravity-network': {
      id: '/_docs/reference/gravity-network'
      path: '/reference/gravity-network'
      fullPath: '/reference/gravity-network'
      preLoaderRoute: typeof DocsReferenceGravityNetworkRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/get-started/what-is-agentuity': {
      id: '/_docs/get-started/what-is-agentuity'
      path: '/get-started/what-is-agentuity'
      fullPath: '/get-started/what-is-agentuity'
      preLoaderRoute: typeof DocsGetStartedWhatIsAgentuityRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/get-started/quickstart': {
      id: '/_docs/get-started/quickstart'
      path: '/get-started/quickstart'
      fullPath: '/get-started/quickstart'
      preLoaderRoute: typeof DocsGetStartedQuickstartRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/get-started/project-structure': {
      id: '/_docs/get-started/project-structure'
      path: '/get-started/project-structure'
      fullPath: '/get-started/project-structure'
      preLoaderRoute: typeof DocsGetStartedProjectStructureRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/get-started/installation': {
      id: '/_docs/get-started/installation'
      path: '/get-started/installation'
      fullPath: '/get-started/installation'
      preLoaderRoute: typeof DocsGetStartedInstallationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/get-started/app-configuration': {
      id: '/_docs/get-started/app-configuration'
      path: '/get-started/app-configuration'
      fullPath: '/get-started/app-configuration'
      preLoaderRoute: typeof DocsGetStartedAppConfigurationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/frontend/workbench': {
      id: '/_docs/frontend/workbench'
      path: '/frontend/workbench'
      fullPath: '/frontend/workbench'
      preLoaderRoute: typeof DocsFrontendWorkbenchRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/frontend/rpc-client': {
      id: '/_docs/frontend/rpc-client'
      path: '/frontend/rpc-client'
      fullPath: '/frontend/rpc-client'
      preLoaderRoute: typeof DocsFrontendRpcClientRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/frontend/react-hooks': {
      id: '/_docs/frontend/react-hooks'
      path: '/frontend/react-hooks'
      fullPath: '/frontend/react-hooks'
      preLoaderRoute: typeof DocsFrontendReactHooksRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/frontend/provider-setup': {
      id: '/_docs/frontend/provider-setup'
      path: '/frontend/provider-setup'
      fullPath: '/frontend/provider-setup'
      preLoaderRoute: typeof DocsFrontendProviderSetupRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/frontend/deployment-scenarios': {
      id: '/_docs/frontend/deployment-scenarios'
      path: '/frontend/deployment-scenarios'
      fullPath: '/frontend/deployment-scenarios'
      preLoaderRoute: typeof DocsFrontendDeploymentScenariosRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/frontend/authentication': {
      id: '/_docs/frontend/authentication'
      path: '/frontend/authentication'
      fullPath: '/frontend/authentication'
      preLoaderRoute: typeof DocsFrontendAuthenticationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/frontend/advanced-hooks': {
      id: '/_docs/frontend/advanced-hooks'
      path: '/frontend/advanced-hooks'
      fullPath: '/frontend/advanced-hooks'
      preLoaderRoute: typeof DocsFrontendAdvancedHooksRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/apis/when-to-use': {
      id: '/_docs/apis/when-to-use'
      path: '/apis/when-to-use'
      fullPath: '/apis/when-to-use'
      preLoaderRoute: typeof DocsApisWhenToUseRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/apis/calling-agents': {
      id: '/_docs/apis/calling-agents'
      path: '/apis/calling-agents'
      fullPath: '/apis/calling-agents'
      preLoaderRoute: typeof DocsApisCallingAgentsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/workbench': {
      id: '/_docs/agents/workbench'
      path: '/agents/workbench'
      fullPath: '/agents/workbench'
      preLoaderRoute: typeof DocsAgentsWorkbenchRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/streaming-responses': {
      id: '/_docs/agents/streaming-responses'
      path: '/agents/streaming-responses'
      fullPath: '/agents/streaming-responses'
      preLoaderRoute: typeof DocsAgentsStreamingResponsesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/state-management': {
      id: '/_docs/agents/state-management'
      path: '/agents/state-management'
      fullPath: '/agents/state-management'
      preLoaderRoute: typeof DocsAgentsStateManagementRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/standalone-execution': {
      id: '/_docs/agents/standalone-execution'
      path: '/agents/standalone-execution'
      fullPath: '/agents/standalone-execution'
      preLoaderRoute: typeof DocsAgentsStandaloneExecutionRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/schema-libraries': {
      id: '/_docs/agents/schema-libraries'
      path: '/agents/schema-libraries'
      fullPath: '/agents/schema-libraries'
      preLoaderRoute: typeof DocsAgentsSchemaLibrariesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/events-lifecycle': {
      id: '/_docs/agents/events-lifecycle'
      path: '/agents/events-lifecycle'
      fullPath: '/agents/events-lifecycle'
      preLoaderRoute: typeof DocsAgentsEventsLifecycleRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/evaluations': {
      id: '/_docs/agents/evaluations'
      path: '/agents/evaluations'
      fullPath: '/agents/evaluations'
      preLoaderRoute: typeof DocsAgentsEvaluationsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/creating-agents': {
      id: '/_docs/agents/creating-agents'
      path: '/agents/creating-agents'
      fullPath: '/agents/creating-agents'
      preLoaderRoute: typeof DocsAgentsCreatingAgentsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/calling-other-agents': {
      id: '/_docs/agents/calling-other-agents'
      path: '/agents/calling-other-agents'
      fullPath: '/agents/calling-other-agents'
      preLoaderRoute: typeof DocsAgentsCallingOtherAgentsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/ai-sdk-integration': {
      id: '/_docs/agents/ai-sdk-integration'
      path: '/agents/ai-sdk-integration'
      fullPath: '/agents/ai-sdk-integration'
      preLoaderRoute: typeof DocsAgentsAiSdkIntegrationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/agents/ai-gateway': {
      id: '/_docs/agents/ai-gateway'
      path: '/agents/ai-gateway'
      fullPath: '/agents/ai-gateway'
      preLoaderRoute: typeof DocsAgentsAiGatewayRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/storage/': {
      id: '/_docs/services/storage/'
      path: '/services/storage'
      fullPath: '/services/storage/'
      preLoaderRoute: typeof DocsServicesStorageIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/sandbox/': {
      id: '/_docs/services/sandbox/'
      path: '/services/sandbox'
      fullPath: '/services/sandbox/'
      preLoaderRoute: typeof DocsServicesSandboxIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/observability/': {
      id: '/_docs/services/observability/'
      path: '/services/observability'
      fullPath: '/services/observability/'
      preLoaderRoute: typeof DocsServicesObservabilityIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/database/': {
      id: '/_docs/services/database/'
      path: '/services/database'
      fullPath: '/services/database/'
      preLoaderRoute: typeof DocsServicesDatabaseIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/': {
      id: '/_docs/reference/cli/'
      path: '/reference/cli'
      fullPath: '/reference/cli/'
      preLoaderRoute: typeof DocsReferenceCliIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/tutorials/': {
      id: '/_docs/cookbook/tutorials/'
      path: '/cookbook/tutorials'
      fullPath: '/cookbook/tutorials/'
      preLoaderRoute: typeof DocsCookbookTutorialsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/patterns/': {
      id: '/_docs/cookbook/patterns/'
      path: '/cookbook/patterns'
      fullPath: '/cookbook/patterns/'
      preLoaderRoute: typeof DocsCookbookPatternsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/storage/vector': {
      id: '/_docs/services/storage/vector'
      path: '/services/storage/vector'
      fullPath: '/services/storage/vector'
      preLoaderRoute: typeof DocsServicesStorageVectorRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/storage/object': {
      id: '/_docs/services/storage/object'
      path: '/services/storage/object'
      fullPath: '/services/storage/object'
      preLoaderRoute: typeof DocsServicesStorageObjectRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/storage/key-value': {
      id: '/_docs/services/storage/key-value'
      path: '/services/storage/key-value'
      fullPath: '/services/storage/key-value'
      preLoaderRoute: typeof DocsServicesStorageKeyValueRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/storage/durable-streams': {
      id: '/_docs/services/storage/durable-streams'
      path: '/services/storage/durable-streams'
      fullPath: '/services/storage/durable-streams'
      preLoaderRoute: typeof DocsServicesStorageDurableStreamsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/storage/database': {
      id: '/_docs/services/storage/database'
      path: '/services/storage/database'
      fullPath: '/services/storage/database'
      preLoaderRoute: typeof DocsServicesStorageDatabaseRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/storage/custom': {
      id: '/_docs/services/storage/custom'
      path: '/services/storage/custom'
      fullPath: '/services/storage/custom'
      preLoaderRoute: typeof DocsServicesStorageCustomRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/sandbox/snapshots': {
      id: '/_docs/services/sandbox/snapshots'
      path: '/services/sandbox/snapshots'
      fullPath: '/services/sandbox/snapshots'
      preLoaderRoute: typeof DocsServicesSandboxSnapshotsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/sandbox/sdk-usage': {
      id: '/_docs/services/sandbox/sdk-usage'
      path: '/services/sandbox/sdk-usage'
      fullPath: '/services/sandbox/sdk-usage'
      preLoaderRoute: typeof DocsServicesSandboxSdkUsageRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/observability/tracing': {
      id: '/_docs/services/observability/tracing'
      path: '/services/observability/tracing'
      fullPath: '/services/observability/tracing'
      preLoaderRoute: typeof DocsServicesObservabilityTracingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/observability/sessions-debugging': {
      id: '/_docs/services/observability/sessions-debugging'
      path: '/services/observability/sessions-debugging'
      fullPath: '/services/observability/sessions-debugging'
      preLoaderRoute: typeof DocsServicesObservabilitySessionsDebuggingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/observability/logging': {
      id: '/_docs/services/observability/logging'
      path: '/services/observability/logging'
      fullPath: '/services/observability/logging'
      preLoaderRoute: typeof DocsServicesObservabilityLoggingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/database/postgres': {
      id: '/_docs/services/database/postgres'
      path: '/services/database/postgres'
      fullPath: '/services/database/postgres'
      preLoaderRoute: typeof DocsServicesDatabasePostgresRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/services/database/drizzle': {
      id: '/_docs/services/database/drizzle'
      path: '/services/database/drizzle'
      fullPath: '/services/database/drizzle'
      preLoaderRoute: typeof DocsServicesDatabaseDrizzleRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/storage': {
      id: '/_docs/reference/cli/storage'
      path: '/reference/cli/storage'
      fullPath: '/reference/cli/storage'
      preLoaderRoute: typeof DocsReferenceCliStorageRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/sandbox': {
      id: '/_docs/reference/cli/sandbox'
      path: '/reference/cli/sandbox'
      fullPath: '/reference/cli/sandbox'
      preLoaderRoute: typeof DocsReferenceCliSandboxRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/opencode-plugin': {
      id: '/_docs/reference/cli/opencode-plugin'
      path: '/reference/cli/opencode-plugin'
      fullPath: '/reference/cli/opencode-plugin'
      preLoaderRoute: typeof DocsReferenceCliOpencodePluginRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/getting-started': {
      id: '/_docs/reference/cli/getting-started'
      path: '/reference/cli/getting-started'
      fullPath: '/reference/cli/getting-started'
      preLoaderRoute: typeof DocsReferenceCliGettingStartedRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/development': {
      id: '/_docs/reference/cli/development'
      path: '/reference/cli/development'
      fullPath: '/reference/cli/development'
      preLoaderRoute: typeof DocsReferenceCliDevelopmentRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/deployment': {
      id: '/_docs/reference/cli/deployment'
      path: '/reference/cli/deployment'
      fullPath: '/reference/cli/deployment'
      preLoaderRoute: typeof DocsReferenceCliDeploymentRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/debugging': {
      id: '/_docs/reference/cli/debugging'
      path: '/reference/cli/debugging'
      fullPath: '/reference/cli/debugging'
      preLoaderRoute: typeof DocsReferenceCliDebuggingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/configuration': {
      id: '/_docs/reference/cli/configuration'
      path: '/reference/cli/configuration'
      fullPath: '/reference/cli/configuration'
      preLoaderRoute: typeof DocsReferenceCliConfigurationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/build-configuration': {
      id: '/_docs/reference/cli/build-configuration'
      path: '/reference/cli/build-configuration'
      fullPath: '/reference/cli/build-configuration'
      preLoaderRoute: typeof DocsReferenceCliBuildConfigurationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/reference/cli/ai-commands': {
      id: '/_docs/reference/cli/ai-commands'
      path: '/reference/cli/ai-commands'
      fullPath: '/reference/cli/ai-commands'
      preLoaderRoute: typeof DocsReferenceCliAiCommandsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/tutorials/understanding-agents': {
      id: '/_docs/cookbook/tutorials/understanding-agents'
      path: '/cookbook/tutorials/understanding-agents'
      fullPath: '/cookbook/tutorials/understanding-agents'
      preLoaderRoute: typeof DocsCookbookTutorialsUnderstandingAgentsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/tutorials/rag-agent': {
      id: '/_docs/cookbook/tutorials/rag-agent'
      path: '/cookbook/tutorials/rag-agent'
      fullPath: '/cookbook/tutorials/rag-agent'
      preLoaderRoute: typeof DocsCookbookTutorialsRagAgentRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/patterns/webhook-handler': {
      id: '/_docs/cookbook/patterns/webhook-handler'
      path: '/cookbook/patterns/webhook-handler'
      fullPath: '/cookbook/patterns/webhook-handler'
      preLoaderRoute: typeof DocsCookbookPatternsWebhookHandlerRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/patterns/tailwind-setup': {
      id: '/_docs/cookbook/patterns/tailwind-setup'
      path: '/cookbook/patterns/tailwind-setup'
      fullPath: '/cookbook/patterns/tailwind-setup'
      preLoaderRoute: typeof DocsCookbookPatternsTailwindSetupRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/patterns/server-utilities': {
      id: '/_docs/cookbook/patterns/server-utilities'
      path: '/cookbook/patterns/server-utilities'
      fullPath: '/cookbook/patterns/server-utilities'
      preLoaderRoute: typeof DocsCookbookPatternsServerUtilitiesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/patterns/product-search': {
      id: '/_docs/cookbook/patterns/product-search'
      path: '/cookbook/patterns/product-search'
      fullPath: '/cookbook/patterns/product-search'
      preLoaderRoute: typeof DocsCookbookPatternsProductSearchRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/patterns/llm-as-a-judge': {
      id: '/_docs/cookbook/patterns/llm-as-a-judge'
      path: '/cookbook/patterns/llm-as-a-judge'
      fullPath: '/cookbook/patterns/llm-as-a-judge'
      preLoaderRoute: typeof DocsCookbookPatternsLlmAsAJudgeRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/patterns/cron-with-storage': {
      id: '/_docs/cookbook/patterns/cron-with-storage'
      path: '/cookbook/patterns/cron-with-storage'
      fullPath: '/cookbook/patterns/cron-with-storage'
      preLoaderRoute: typeof DocsCookbookPatternsCronWithStorageRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/patterns/chat-with-history': {
      id: '/_docs/cookbook/patterns/chat-with-history'
      path: '/cookbook/patterns/chat-with-history'
      fullPath: '/cookbook/patterns/chat-with-history'
      preLoaderRoute: typeof DocsCookbookPatternsChatWithHistoryRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/_docs/cookbook/patterns/background-tasks': {
      id: '/_docs/cookbook/patterns/background-tasks'
      path: '/cookbook/patterns/background-tasks'
      fullPath: '/cookbook/patterns/background-tasks'
      preLoaderRoute: typeof DocsCookbookPatternsBackgroundTasksRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsAgentsAiGatewayRoute: typeof DocsAgentsAiGatewayRoute
  DocsAgentsAiSdkIntegrationRoute: typeof DocsAgentsAiSdkIntegrationRoute
  DocsAgentsCallingOtherAgentsRoute: typeof DocsAgentsCallingOtherAgentsRoute
  DocsAgentsCreatingAgentsRoute: typeof DocsAgentsCreatingAgentsRoute
  DocsAgentsEvaluationsRoute: typeof DocsAgentsEvaluationsRoute
  DocsAgentsEventsLifecycleRoute: typeof DocsAgentsEventsLifecycleRoute
  DocsAgentsSchemaLibrariesRoute: typeof DocsAgentsSchemaLibrariesRoute
  DocsAgentsStandaloneExecutionRoute: typeof DocsAgentsStandaloneExecutionRoute
  DocsAgentsStateManagementRoute: typeof DocsAgentsStateManagementRoute
  DocsAgentsStreamingResponsesRoute: typeof DocsAgentsStreamingResponsesRoute
  DocsAgentsWorkbenchRoute: typeof DocsAgentsWorkbenchRoute
  DocsApisCallingAgentsRoute: typeof DocsApisCallingAgentsRoute
  DocsApisWhenToUseRoute: typeof DocsApisWhenToUseRoute
  DocsFrontendAdvancedHooksRoute: typeof DocsFrontendAdvancedHooksRoute
  DocsFrontendAuthenticationRoute: typeof DocsFrontendAuthenticationRoute
  DocsFrontendDeploymentScenariosRoute: typeof DocsFrontendDeploymentScenariosRoute
  DocsFrontendProviderSetupRoute: typeof DocsFrontendProviderSetupRoute
  DocsFrontendReactHooksRoute: typeof DocsFrontendReactHooksRoute
  DocsFrontendRpcClientRoute: typeof DocsFrontendRpcClientRoute
  DocsFrontendWorkbenchRoute: typeof DocsFrontendWorkbenchRoute
  DocsGetStartedAppConfigurationRoute: typeof DocsGetStartedAppConfigurationRoute
  DocsGetStartedInstallationRoute: typeof DocsGetStartedInstallationRoute
  DocsGetStartedProjectStructureRoute: typeof DocsGetStartedProjectStructureRoute
  DocsGetStartedQuickstartRoute: typeof DocsGetStartedQuickstartRoute
  DocsGetStartedWhatIsAgentuityRoute: typeof DocsGetStartedWhatIsAgentuityRoute
  DocsReferenceGravityNetworkRoute: typeof DocsReferenceGravityNetworkRoute
  DocsReferenceMdxFeaturesRoute: typeof DocsReferenceMdxFeaturesRoute
  DocsReferenceMigrationGuideRoute: typeof DocsReferenceMigrationGuideRoute
  DocsReferenceSdkReferenceRoute: typeof DocsReferenceSdkReferenceRoute
  DocsRoutesCronRoute: typeof DocsRoutesCronRoute
  DocsRoutesHttpRoute: typeof DocsRoutesHttpRoute
  DocsRoutesMiddlewareRoute: typeof DocsRoutesMiddlewareRoute
  DocsRoutesSseRoute: typeof DocsRoutesSseRoute
  DocsRoutesWebsocketsRoute: typeof DocsRoutesWebsocketsRoute
  DocsServicesQueuesRoute: typeof DocsServicesQueuesRoute
  DocsAgentsIndexRoute: typeof DocsAgentsIndexRoute
  DocsApisIndexRoute: typeof DocsApisIndexRoute
  DocsCommunityIndexRoute: typeof DocsCommunityIndexRoute
  DocsCookbookIndexRoute: typeof DocsCookbookIndexRoute
  DocsFrontendIndexRoute: typeof DocsFrontendIndexRoute
  DocsGetStartedIndexRoute: typeof DocsGetStartedIndexRoute
  DocsReferenceIndexRoute: typeof DocsReferenceIndexRoute
  DocsRoutesIndexRoute: typeof DocsRoutesIndexRoute
  DocsServicesIndexRoute: typeof DocsServicesIndexRoute
  DocsCookbookPatternsBackgroundTasksRoute: typeof DocsCookbookPatternsBackgroundTasksRoute
  DocsCookbookPatternsChatWithHistoryRoute: typeof DocsCookbookPatternsChatWithHistoryRoute
  DocsCookbookPatternsCronWithStorageRoute: typeof DocsCookbookPatternsCronWithStorageRoute
  DocsCookbookPatternsLlmAsAJudgeRoute: typeof DocsCookbookPatternsLlmAsAJudgeRoute
  DocsCookbookPatternsProductSearchRoute: typeof DocsCookbookPatternsProductSearchRoute
  DocsCookbookPatternsServerUtilitiesRoute: typeof DocsCookbookPatternsServerUtilitiesRoute
  DocsCookbookPatternsTailwindSetupRoute: typeof DocsCookbookPatternsTailwindSetupRoute
  DocsCookbookPatternsWebhookHandlerRoute: typeof DocsCookbookPatternsWebhookHandlerRoute
  DocsCookbookTutorialsRagAgentRoute: typeof DocsCookbookTutorialsRagAgentRoute
  DocsCookbookTutorialsUnderstandingAgentsRoute: typeof DocsCookbookTutorialsUnderstandingAgentsRoute
  DocsReferenceCliAiCommandsRoute: typeof DocsReferenceCliAiCommandsRoute
  DocsReferenceCliBuildConfigurationRoute: typeof DocsReferenceCliBuildConfigurationRoute
  DocsReferenceCliConfigurationRoute: typeof DocsReferenceCliConfigurationRoute
  DocsReferenceCliDebuggingRoute: typeof DocsReferenceCliDebuggingRoute
  DocsReferenceCliDeploymentRoute: typeof DocsReferenceCliDeploymentRoute
  DocsReferenceCliDevelopmentRoute: typeof DocsReferenceCliDevelopmentRoute
  DocsReferenceCliGettingStartedRoute: typeof DocsReferenceCliGettingStartedRoute
  DocsReferenceCliOpencodePluginRoute: typeof DocsReferenceCliOpencodePluginRoute
  DocsReferenceCliSandboxRoute: typeof DocsReferenceCliSandboxRoute
  DocsReferenceCliStorageRoute: typeof DocsReferenceCliStorageRoute
  DocsServicesDatabaseDrizzleRoute: typeof DocsServicesDatabaseDrizzleRoute
  DocsServicesDatabasePostgresRoute: typeof DocsServicesDatabasePostgresRoute
  DocsServicesObservabilityLoggingRoute: typeof DocsServicesObservabilityLoggingRoute
  DocsServicesObservabilitySessionsDebuggingRoute: typeof DocsServicesObservabilitySessionsDebuggingRoute
  DocsServicesObservabilityTracingRoute: typeof DocsServicesObservabilityTracingRoute
  DocsServicesSandboxSdkUsageRoute: typeof DocsServicesSandboxSdkUsageRoute
  DocsServicesSandboxSnapshotsRoute: typeof DocsServicesSandboxSnapshotsRoute
  DocsServicesStorageCustomRoute: typeof DocsServicesStorageCustomRoute
  DocsServicesStorageDatabaseRoute: typeof DocsServicesStorageDatabaseRoute
  DocsServicesStorageDurableStreamsRoute: typeof DocsServicesStorageDurableStreamsRoute
  DocsServicesStorageKeyValueRoute: typeof DocsServicesStorageKeyValueRoute
  DocsServicesStorageObjectRoute: typeof DocsServicesStorageObjectRoute
  DocsServicesStorageVectorRoute: typeof DocsServicesStorageVectorRoute
  DocsCookbookPatternsIndexRoute: typeof DocsCookbookPatternsIndexRoute
  DocsCookbookTutorialsIndexRoute: typeof DocsCookbookTutorialsIndexRoute
  DocsReferenceCliIndexRoute: typeof DocsReferenceCliIndexRoute
  DocsServicesDatabaseIndexRoute: typeof DocsServicesDatabaseIndexRoute
  DocsServicesObservabilityIndexRoute: typeof DocsServicesObservabilityIndexRoute
  DocsServicesSandboxIndexRoute: typeof DocsServicesSandboxIndexRoute
  DocsServicesStorageIndexRoute: typeof DocsServicesStorageIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsAgentsAiGatewayRoute: DocsAgentsAiGatewayRoute,
  DocsAgentsAiSdkIntegrationRoute: DocsAgentsAiSdkIntegrationRoute,
  DocsAgentsCallingOtherAgentsRoute: DocsAgentsCallingOtherAgentsRoute,
  DocsAgentsCreatingAgentsRoute: DocsAgentsCreatingAgentsRoute,
  DocsAgentsEvaluationsRoute: DocsAgentsEvaluationsRoute,
  DocsAgentsEventsLifecycleRoute: DocsAgentsEventsLifecycleRoute,
  DocsAgentsSchemaLibrariesRoute: DocsAgentsSchemaLibrariesRoute,
  DocsAgentsStandaloneExecutionRoute: DocsAgentsStandaloneExecutionRoute,
  DocsAgentsStateManagementRoute: DocsAgentsStateManagementRoute,
  DocsAgentsStreamingResponsesRoute: DocsAgentsStreamingResponsesRoute,
  DocsAgentsWorkbenchRoute: DocsAgentsWorkbenchRoute,
  DocsApisCallingAgentsRoute: DocsApisCallingAgentsRoute,
  DocsApisWhenToUseRoute: DocsApisWhenToUseRoute,
  DocsFrontendAdvancedHooksRoute: DocsFrontendAdvancedHooksRoute,
  DocsFrontendAuthenticationRoute: DocsFrontendAuthenticationRoute,
  DocsFrontendDeploymentScenariosRoute: DocsFrontendDeploymentScenariosRoute,
  DocsFrontendProviderSetupRoute: DocsFrontendProviderSetupRoute,
  DocsFrontendReactHooksRoute: DocsFrontendReactHooksRoute,
  DocsFrontendRpcClientRoute: DocsFrontendRpcClientRoute,
  DocsFrontendWorkbenchRoute: DocsFrontendWorkbenchRoute,
  DocsGetStartedAppConfigurationRoute: DocsGetStartedAppConfigurationRoute,
  DocsGetStartedInstallationRoute: DocsGetStartedInstallationRoute,
  DocsGetStartedProjectStructureRoute: DocsGetStartedProjectStructureRoute,
  DocsGetStartedQuickstartRoute: DocsGetStartedQuickstartRoute,
  DocsGetStartedWhatIsAgentuityRoute: DocsGetStartedWhatIsAgentuityRoute,
  DocsReferenceGravityNetworkRoute: DocsReferenceGravityNetworkRoute,
  DocsReferenceMdxFeaturesRoute: DocsReferenceMdxFeaturesRoute,
  DocsReferenceMigrationGuideRoute: DocsReferenceMigrationGuideRoute,
  DocsReferenceSdkReferenceRoute: DocsReferenceSdkReferenceRoute,
  DocsRoutesCronRoute: DocsRoutesCronRoute,
  DocsRoutesHttpRoute: DocsRoutesHttpRoute,
  DocsRoutesMiddlewareRoute: DocsRoutesMiddlewareRoute,
  DocsRoutesSseRoute: DocsRoutesSseRoute,
  DocsRoutesWebsocketsRoute: DocsRoutesWebsocketsRoute,
  DocsServicesQueuesRoute: DocsServicesQueuesRoute,
  DocsAgentsIndexRoute: DocsAgentsIndexRoute,
  DocsApisIndexRoute: DocsApisIndexRoute,
  DocsCommunityIndexRoute: DocsCommunityIndexRoute,
  DocsCookbookIndexRoute: DocsCookbookIndexRoute,
  DocsFrontendIndexRoute: DocsFrontendIndexRoute,
  DocsGetStartedIndexRoute: DocsGetStartedIndexRoute,
  DocsReferenceIndexRoute: DocsReferenceIndexRoute,
  DocsRoutesIndexRoute: DocsRoutesIndexRoute,
  DocsServicesIndexRoute: DocsServicesIndexRoute,
  DocsCookbookPatternsBackgroundTasksRoute:
    DocsCookbookPatternsBackgroundTasksRoute,
  DocsCookbookPatternsChatWithHistoryRoute:
    DocsCookbookPatternsChatWithHistoryRoute,
  DocsCookbookPatternsCronWithStorageRoute:
    DocsCookbookPatternsCronWithStorageRoute,
  DocsCookbookPatternsLlmAsAJudgeRoute: DocsCookbookPatternsLlmAsAJudgeRoute,
  DocsCookbookPatternsProductSearchRoute:
    DocsCookbookPatternsProductSearchRoute,
  DocsCookbookPatternsServerUtilitiesRoute:
    DocsCookbookPatternsServerUtilitiesRoute,
  DocsCookbookPatternsTailwindSetupRoute:
    DocsCookbookPatternsTailwindSetupRoute,
  DocsCookbookPatternsWebhookHandlerRoute:
    DocsCookbookPatternsWebhookHandlerRoute,
  DocsCookbookTutorialsRagAgentRoute: DocsCookbookTutorialsRagAgentRoute,
  DocsCookbookTutorialsUnderstandingAgentsRoute:
    DocsCookbookTutorialsUnderstandingAgentsRoute,
  DocsReferenceCliAiCommandsRoute: DocsReferenceCliAiCommandsRoute,
  DocsReferenceCliBuildConfigurationRoute:
    DocsReferenceCliBuildConfigurationRoute,
  DocsReferenceCliConfigurationRoute: DocsReferenceCliConfigurationRoute,
  DocsReferenceCliDebuggingRoute: DocsReferenceCliDebuggingRoute,
  DocsReferenceCliDeploymentRoute: DocsReferenceCliDeploymentRoute,
  DocsReferenceCliDevelopmentRoute: DocsReferenceCliDevelopmentRoute,
  DocsReferenceCliGettingStartedRoute: DocsReferenceCliGettingStartedRoute,
  DocsReferenceCliOpencodePluginRoute: DocsReferenceCliOpencodePluginRoute,
  DocsReferenceCliSandboxRoute: DocsReferenceCliSandboxRoute,
  DocsReferenceCliStorageRoute: DocsReferenceCliStorageRoute,
  DocsServicesDatabaseDrizzleRoute: DocsServicesDatabaseDrizzleRoute,
  DocsServicesDatabasePostgresRoute: DocsServicesDatabasePostgresRoute,
  DocsServicesObservabilityLoggingRoute: DocsServicesObservabilityLoggingRoute,
  DocsServicesObservabilitySessionsDebuggingRoute:
    DocsServicesObservabilitySessionsDebuggingRoute,
  DocsServicesObservabilityTracingRoute: DocsServicesObservabilityTracingRoute,
  DocsServicesSandboxSdkUsageRoute: DocsServicesSandboxSdkUsageRoute,
  DocsServicesSandboxSnapshotsRoute: DocsServicesSandboxSnapshotsRoute,
  DocsServicesStorageCustomRoute: DocsServicesStorageCustomRoute,
  DocsServicesStorageDatabaseRoute: DocsServicesStorageDatabaseRoute,
  DocsServicesStorageDurableStreamsRoute:
    DocsServicesStorageDurableStreamsRoute,
  DocsServicesStorageKeyValueRoute: DocsServicesStorageKeyValueRoute,
  DocsServicesStorageObjectRoute: DocsServicesStorageObjectRoute,
  DocsServicesStorageVectorRoute: DocsServicesStorageVectorRoute,
  DocsCookbookPatternsIndexRoute: DocsCookbookPatternsIndexRoute,
  DocsCookbookTutorialsIndexRoute: DocsCookbookTutorialsIndexRoute,
  DocsReferenceCliIndexRoute: DocsReferenceCliIndexRoute,
  DocsServicesDatabaseIndexRoute: DocsServicesDatabaseIndexRoute,
  DocsServicesObservabilityIndexRoute: DocsServicesObservabilityIndexRoute,
  DocsServicesSandboxIndexRoute: DocsServicesSandboxIndexRoute,
  DocsServicesStorageIndexRoute: DocsServicesStorageIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  DemoDemoIdRoute: DemoDemoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
