/**
 * Auto-generated sandbox script metadata.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Edit the source files in src/run/ and run: bun run scripts/generate-sandbox-scripts.ts
 *
 * @generated
 */

/** Valid script names (scripts are baked into the sandbox snapshot) */
export const SCRIPT_NAMES: ReadonlySet<string> = new Set([
	'agent-calls',
	'ai-gateway',
	'chat',
	'database',
	'durable-stream',
	'email',
	'handler-context',
	'hello',
	'kv',
	'model-arena',
	'objectstore',
	'queue',
	'schedule',
	'sse-stream',
	'streaming',
	'vector',
	'webrtc',
	'websocket',
]);

/** Default inputs for each script (extracted from source files) */
export const SCRIPT_DEFAULTS: Record<string, unknown> = {
	'agent-calls': { name: 'World' },
	'ai-gateway': { prompt: 'Tell me a joke' },
	chat: { message: 'Hello!' },
	database: { query: 'summary', seedData: true },
	'durable-stream': {},
	email: { template: 'welcome' },
	'handler-context': {},
	hello: { name: 'World' },
	kv: {},
	'model-arena': { prompt: 'Write a haiku about coding' },
	objectstore: {},
	queue: {},
	schedule: { expression: '* * * * *' },
	'sse-stream': { prompt: 'Tell me a story' },
	streaming: { prompt: 'Tell me a story' },
	vector: { query: 'comfortable chair' },
	webrtc: {},
	websocket: {},
};
